### ISSUE TITLE
Indices

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/performance#1]
Possible indices to add:
- [x] ICC
- [x] Bayes factor (?)
- [x] R2 Nakagawa
- [x] R2 for lme
- [ ] Goodness-of-Fit for Logistic Regression?
- [x] Hosmer-Lemeshow for Log. Reg.?

**Comment by strengejacke** [comment]
Would it make sense, if bayestestR is a core package, to wrap those functions in performance? We address different users with these packages, and I would like to have an end-user backend for the bayestestR functions as well.

**Comment by DominiqueMakowski** [comment]
Hum... I think the separation is interesting for code organization and clarity. However, I do agree with your point as well, about the possible overlaps of scopes and users. 

Since both packages are (almost) deps free, loading them is the same as loading one package with all in it. Thus, maybe one easy way of solving this issue could be to store the computation *per se* of performance indices in performance, while reexporting its Bayesian-related functions in BayestestR. This way, users can have them by calling only bayestestR?

**Comment by strengejacke** [comment]
I'm okay with this approach. However, we must be careful with our package hierarchy to avoid circular dependencies. Your suggestion would make bayestestR a higher hierarchy package than performance, if I understood right?

**Comment by DominiqueMakowski** [comment]
That's true, and currently performance depends on bayestestR because of `hdi`... (used only in R loo adjusted I think)

one option could be to move `hdi` here but reexport and keep the documentation and so on in bayestestR also?

**Comment by strengejacke** [comment]
I think I need to paint a small "roadmap" or "map" in general of what the purposes of the packages are and should to, to get an overview ;-) But yes, bayestestR should provide the core functionality and run "beyond" the scope of end users, and performance should aim at that group.

**Comment by strengejacke** [comment]
I think I will start transferring functions from sjstats to here... Some stuff is related and can't be really dissociated (like ICC and R2 for mixed models, which essentialy use the same computational basis).

It will require some re-writing to reduce dependencies, though.

**Comment by strengejacke** [comment]
Woiuld you like to export only the "summary" methods, or make it also possible for users to directly access certain indices, like R2?

Like, `r2(glm)` and `model_performance(glm)`, or only the latter?

**Comment by DominiqueMakowski** [comment]
I think that given the scope and aim of this package, it would make sense for users to be able to directly compute (or try computing) whatever metrics they want (i.e., export the metrics computation). `model_performance` is just a wrapper that computes several metrics (with "appropriate" defaults) for a model "at once".

**Comment by strengejacke** [comment]
> Goodness-of-Fit for Logistic Regression?

I was thinking about this one, but I'm not sure about the quality of this test. Actually, Hosmer-Lemeshow is also said to be of lower quality, but...

**Comment by strengejacke** [comment]
I think we can close this. BF is now in bayestestR, and we have another issue open regarding logistic regression.
