### ISSUE TITLE
Consistent return values for R2-functions

### ISSUE THREAD

**Issue by strengejacke** [easystats/performance#10]
We must think about the behaviour of some r-squared functions...

1. Do we want `r2()` to return different values for lm? Currently, DF etc. are also returned.
2. Do we want named vectors to be returned or unnamed?
3. Do we want a list to be returned for `r2_*()`?

I would say "yes" to 2 and 3, but not sure about 1?

**Comment by DominiqueMakowski** [comment]
I would say yes for 2 and 3 also.

for 1, there is indeed a design choice to be made... mmh.... One the one hand it looks good to have a unified output. On the other hand, it makes sense (and would be useful for users?) for the `r2()` to return "everything related to" the computed R2...

How else can we return the measures related to lm's R2? Through another function? Through attributes?

**Comment by strengejacke** [comment]
I must say I like the current implementation of functions in this package. :-)

 According the unsolved questions in this issue, maybe we could return the "extra" information as attributes? That's the most consistent way regarding what someone expects as return value ("just" the R"), and additional information needed for other functions.

**Comment by DominiqueMakowski** [comment]
(In general, for me it is a pleasant change to have narrow-scoped packages without too many different things going on 😅 it helps to focus and see potential improvements)

Right, along with a nice method to extract these relevant attributes? Like `r2_details()` or something like that? If that's a thing, maybe it would also make sense return only the median's R2 for Bayesian models, and return the posterior / the posterior indices (MAD, CIs...) through attributes?

**Comment by strengejacke** [comment]
> If that's a thing, maybe it would also make sense return only the median's R2 for Bayesian models, and return the posterior / the posterior indices (MAD, CIs...) through attributes?

Yes, definitely! We could wither add an extra class-attribute to the return value, so we know which elements are returned, or we simply check for attributes (would be more if-else-statements, I guess). The first approach might be cleaner code.

**Comment by strengejacke** [comment]
closing in favor of #19
