### ISSUE TITLE
lmer mixed models => check_model() throws error

### ISSUE THREAD

**Issue by rndjkb** [easystats/performance#104]
Hello,
based on the tutorial, shouldn't the following lead to some graphs?

```
library(lme4) 
library(performance)
str(sleepstudy)
m <- lmer(Reaction ~ Days + (Days | Subject), sleepstudy)
check_model(m)
```

I get the following error message, and no output/plots.

> Not enough model terms in the conditional part of the model to check for multicollinearity.
> Error in UseMethod("cooks.distance") : 
>   no applicable method for 'cooks.distance' applied to an object of class "c('lmerMod', 'merMod')"

I am using R version 3.4.4 and package version 0.4.4

Best wishes!

**Comment by strengejacke** [comment]
Can't reproduce. Do you have the latest lme4-package version installed?

**Comment by strengejacke** [comment]
``` r
library(lme4) 
#> Loading required package: Matrix
library(performance)
m <- lmer(Reaction ~ Days + (Days | Subject), sleepstudy)
check_model(m)
#> Not enough model terms in the conditional part of the model to check for multicollinearity.
#> `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
#> Warning: Removed 173 rows containing missing values (geom_text_repel).
```

![](https://i.imgur.com/AiZFnWp.png)

<sup>Created on 2020-03-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by rndjkb** [comment]
thank you, updating the  lme4 package indeed fixed the problem for me!
