### ISSUE TITLE
`check_heteroscedasticity` fails for `aov`

### ISSUE THREAD

**Issue by mattansb** [easystats/performance#105]
`check_heteroscedasticity` fails for `aov()` but not for the same model fit with `lm()`:

``` r
library(performance)
#> Warning: package 'performance' was built under R version 3.6.2

npk.aov <- aov(yield ~ block + N * P * K, npk)
npk.lm <- lm(yield ~ block + N * P * K, npk)

check_heteroscedasticity(npk.aov)
#> Error in model.frame.default(formula = .U ~ stats::fitted(x), drop.unused.levels = TRUE): variable lengths differ (found for 'stats::fitted(x)')
check_heteroscedasticity(npk.lm)
#> OK: Error variance appears to be homoscedastic (p = 0.378).
```

I can't use `check_homogeneity` here, as it fails:

``` r
check_homogeneity(npk.aov)
#> Error in bartlett.test.default(c(49.5, 62.8, 46.8, 57, 59.8, 58.5, 55.5, : there must be at least 2 observations in each group
check_homogeneity(npk.lm)
#> Error in bartlett.test.default(c(49.5, 62.8, 46.8, 57, 59.8, 58.5, 55.5, : there must be at least 2 observations in each group
```
---
Also, I'm not sure what the difference is between the two functions? Isn't homogeneity of variance == homoscedasticity in the general GLM framework?

**Comment by strengejacke** [comment]
I'm not 100% sure, but I think that the difference is that `check_homogeneity()` checks for equal variance of response in different groups. `check_heteroscedasticity()` performs a check on the residuals. Maybe these are related? I usually only use the check for heteroscedasticity.
