### ISSUE TITLE
Check_model gives error

### ISSUE THREAD

**Issue by bhattmaulik** [easystats/performance#106]
I am reproducing the error message I am receiving while using "check_model" function.
```r
library(performance)
library(see)
Error: package or namespace load failed for ‘see’:
 object ‘model_simulate’ is not exported by 'namespace:parameters'
> model1<- lm(mpg~., data = mtcars)
> check_model(model1)
Error in print.check_model(x) : 
  Package 'see' required to plot model assumptions. Please install it.
```

I have installed "see" package as well. I also restarted R and RStudio and re-run it.

**Comment by strengejacke** [comment]
I guess you're using the GitHub-version from _parameters_. In that case, you need to update _see_ from GitHub as well, as the namespace changed in the **GitHub** versionb of _parameters_ (function `model_simulate()` was renamed to `simulate_model()`), and the _see_ package on GitHub works with the GitHub version of parameters. ;-)

**Comment by bhattmaulik** [comment]
You were write. My "performance" package was from github, while "see" was from CRAN. I downloaded "see" from github, and now it is working fine.

**Comment by kelseygonzalez** [comment]
For others who might run into this issue: I just ran into this same issue, though both packages performance and see were from CRAN. Downloading the github version of see and restarting r  indeed fixed it.
