### ISSUE TITLE
No R2 for `aov`

### ISSUE THREAD

**Issue by mattansb** [easystats/performance#112]
``` r
library(performance)

npk.aov <- aov(yield ~ block, npk)
r2(npk.aov)
#> Error in names(out$R2) <- "R2": attempt to set an attribute on NULL

npk.lm <- lm(yield ~ block, npk)
r2(npk.lm)
#> # R2 for Linear Regression
#> 
#>        R2: 0.392
#>   adj. R2: 0.223
```

**Comment by strengejacke** [comment]
I never really understood why people would use `aov()` instead of `lm()` ;-)

**Comment by mattansb** [comment]
Better default summary method for factorial design? 🤷‍♂️😅

**Comment by DominiqueMakowski** [comment]
> I never really understood why people would use aov() instead of lm() ;-)

"Allows" people to say "the effect of X is significant" without caring whatsoever about what the effect is?

**Comment by strengejacke** [comment]
I guess you need to be a psychologist to value anovas... all others use more sophisticated methods 👅

**Comment by mattansb** [comment]
Psychologists don't jump to check if /which conditions are different from the control 😜
