### ISSUE TITLE
Enhanced `compare models` for linear models

### ISSUE THREAD

**Issue by mattansb** [easystats/performance#115]
For linear models, we can add `R2_delta`, of `Cohens_f2` (e.g. [this paper in LMM](https://doi.org/10.3389/fpsyg.2012.00111)).

**Comment by mattansb** [comment]
(For non-linear models having `R2_delta` would be weird, as the total "variance" increases with model complexity...)

**Comment by strengejacke** [comment]
is this related to https://github.com/easystats/performance/issues/28?

**Comment by mattansb** [comment]
Yes 😅
I'll take it over there...

**Comment by DominiqueMakowski** [comment]
But isn't cohens_f2 also a measure of "local" effect size (for each parameter)?

**Comment by mattansb** [comment]
Yes, similar to how eta squared can also be for a full model or per term.

--
Mattan S. Ben-Shachar, PhD student
Department of Psychology & Zlotowski Center for Neuroscience
Ben-Gurion University of the Negev
The Developmental ERP Lab
