### ISSUE TITLE
No R2 for glmmTMB objects without random terms

### ISSUE THREAD

**Issue by martin-freitag** [easystats/performance#117]
I've been fitting very simple models with the `glmmTMB` package and tried to get pseudo-R2s with the `r2` function. This works fine with random intercepts included, but without any random effects the result is NA. 
One could simply use `glm` for most of the models (for which `r2` works perfectly fine) but `glm` unfortunately doesn't support the beta family. It might be that I am missing something, but it would be great to use the `r2` function for such simple `glmmTMB` models.

Reproducible example:
```R
library(glmmTMB)      # version 0.4.5
library(performance)  #version 1.0.1 

# model with random intercept
m1 <- glmmTMB(count ~ mined + (1|site), zi=~mined, family=poisson, data=Salamanders)
r2(m1)
># R2 for Mixed Models
>
>  Conditional R2: 0.414
>     Marginal R2: 0.333

# model without random intercept
m2 <- glmmTMB(count ~ mined, zi=~mined, family=poisson, data=Salamanders)
r2(m2)
>  [1] NA
```

**Comment by strengejacke** [comment]
Should be fixed now after updating [*insight*](https://easystats.github.io/insight/) from CRAN.

``` r
library(glmmTMB)      # version 0.4.5
library(performance)  #version 1.0.1 
m2 <- glmmTMB(count ~ mined, zi=~mined, family=poisson, data=Salamanders)
r2(m2)
#> Warning: mu of 3.2 is too close to zero, estimate of random effect variances may be unreliable.
#> Random effect variances not available. Returned R2 does not account for random effects.
#> # R2 for Mixed Models
#> 
#>   Conditional R2: NA
#>      Marginal R2: 0.455
```

<sup>Created on 2020-05-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
