### ISSUE TITLE
References in docs

### ISSUE THREAD

**Issue by strengejacke** [easystats/performance#118]
@mattansb @DominiqueMakowski 
A question for you psychos: which references would you recommend for the method itself as well as for the cur-offs / thresholds?

- https://easystats.github.io/performance/reference/item_difficulty.html
- https://easystats.github.io/performance/reference/item_reliability.html

?

**Comment by mattansb** [comment]
I've don't really do either... I'm closer to cogsci than psych I guess 🤷‍♂️

**Comment by strengejacke** [comment]
@DominiqueMakowski ?

**Comment by strengejacke** [comment]
_bump_ @DominiqueMakowski

**Comment by DominiqueMakowski** [comment]
> I'm closer to cogsci than psych I guess 

Lol nice parade 😁 

I know that a lot of good documentation regarding this kind of stuff is within the psych package ([doc](https://cran.r-project.org/web/packages/psych/psych.pdf)) but it's usually organized by index type (and it has a ton of them, so I'm not sure which one would apply)

**Comment by strengejacke** [comment]
Guys, thanks for your valuable input! I mean it! 😄
