### ISSUE TITLE
ICC

### ISSUE THREAD

**Issue by strengejacke** [easystats/performance#12]
Currently, `icc()` works for the packages *lme4*, * glmmTMB*  and *rstanarm*. *brms* calculates the ICC in a different way, based on a variance-decomposition. For non-Gaussian models, this approach is also recommended by Stan team members. For non-Bayesian models (lme4/glmmTMB), the ICC for non-Gaussian models is based on some approximations of the variances (which is not perfect, but apparently the current state of the art).

Questions:

1) Do we want rstanarm models behave like lme4 or brms? The latter would mean that non-Gaussian models fitted with rstanarm would return a more "Bayesian correct" ICC.

2) For brms, we can't use the variance-calculation we use for the `r2_nagakawa()`. We could only calculate a comparable ICC for brms models when they are Gaussian and only have one random intercept. Do we want to cover this "edge case" by implementing extra code particularly for these types of models, or do we always want the variance decomposition for brms?

Let me give a comparison, only for the same brms-model

```r
model4 <- brms::brm(Petal.Length ~ Petal.Width + (1 | Species), data = iris)

# Variance decomposition
performance::icc(model4)
#> $ICC_decomposed
#> [1] 0.7477364
#> 
#> $CI
#>      2.5%     97.5% 
#> 0.8543512 0.6156847 

# ICC only for linear models, with only random intercept
sjstats::icc(model4)
#> ## Species
#>           ICC: 0.94  HDI 89%: [0.86  1.00]
```

If you would use the current `icc()` for a mixed model from `rstanarm`, you get the ICC based on Nagakawa, as it would be returned for lme4 etc. as well:

```r
performance::icc(model2)
#> $ICC_adjusted
#> [1] 0.8786005
#> 
#> $ICC_conditional
#> [1] 0.5603696
```

So, method 1) (Variance Decomposition) gives an ICC of .75, method 2) (simple ICC for linear models with random intercept only) gives ans ICC of .94 while method 3) (Nagakawa ICC) returns .88 and .56.

We could use method 1) or 3) for brms linear models with random intercept only, where method 1) is below (or between those two ICC values) and method 3) is above the values of method 2)...

3) What values should be returned? We have the CI for brms-models, but only one "ICC" (which is not exactly an ICC, but something comparable, the variance decomposition in a Bayesian way...)

4) How do we call what `icc()` returns for brms models? Still ICC, and explain this in the docs of `icc()`?

**Comment by strengejacke** [comment]
Any thoughts on 1), 2), 3) and 4)?

**Comment by strengejacke** [comment]
My opinion:

1) Leave it as it's implemented now (i.e. ICC for rstanarm = ICC for lme4)

2) No, keep it as it currently is. ICC for brms returns a variance decomposition. No special treatment of the simple linear mixed model with random intercept only. We'll have a `get_variances()` function in _insight_ later, anyway, where you can compute ICC by hand, if required.

3) In line with https://github.com/easystats/performance/issues/10, I would say we just return the main value and other information like CI as attributes.

4) I would keep the name "ICC", even if it's not a "classical" ICC. Docs explain it quite well, I think

**Comment by DominiqueMakowski** [comment]
I trust your opinion. Let's go for it! (although as you said it's quite annoying, in general, that different indices have the same name, but hey we cannot change everything either)

**Comment by strengejacke** [comment]
Closing in favor of #19
