### ISSUE TITLE
performance_roc and performance_accuracy do not match auc values from other packages

### ISSUE THREAD

**Issue by ManuelSpinola** [easystats/performance#121]
library(performance)
library(ModelMetrics)
library(epiDisplay)

model <- glm(vs ~ wt + mpg, data = mtcars, family = "binomial")

> performance_roc(model)
AUC: 8.73%

> performance_accuracy(model)
# Accuracy of Model Predictions

Accuracy: 5.83%
      SE: 8.12%-points
  Method: Area under Curve

> library(epiDisplay)
> resloc <- lroc(model)
> resloc$auc
[1] 0.9126984

> library(ModelMetrics)
> ModelMetrics::auc(model)
[1] 0.9126984

**Comment by strengejacke** [comment]
Thanks, looks like we swapped sensivity and specifity when calculating the AUC, resulting in our value being 1 - AUC as compared to other packages.
