### ISSUE TITLE
Package not loading

### ISSUE THREAD

**Issue by Reizor1989** [easystats/performance#122]
I've uninstalled and reinstalled the package (v.0.4.6) with/without dependencies but I'm not able to load it into the library without getting the error message:

Error: package or namespace load failed for ‘performance’:
 object ‘null_model’ is not exported by 'namespace:insight'
In addition: Warning message:
package ‘performance’ was built under R version 3.6.3 

I'm wondering if another loaded package is interfering with it or some internal but I'm not entirely sure how to diagnose this issue.

**Comment by strengejacke** [comment]
Sounds like you need to update your packages, in particular _insight_.
