### ISSUE TITLE
Outlier test for glmmTMB

### ISSUE THREAD

**Issue by klattbk** [easystats/performance#123]
Hi!

I am running glmmTMB models with tweedie, poisson and negbin families. While many other functions (r2, icc, etc.) in performance are functional, the check_outliers() function returns NULL. What could be the reason?

Thanks and best,
Björn

**Comment by strengejacke** [comment]
Duplicate of #95
The reason is that the available method to detect outliers do not work for glmmTMB objects, so we have to write an own implementation, which is not done yet. But it's on our to-do list ;-)
