### ISSUE TITLE
Syntax for re.form argument and difference between that and by_group argument

### ISSUE THREAD

**Issue by kkdobbin** [easystats/performance#125]
**Question and context**
Hi - I've been looking for sometime and I can find no guidance about how to use the re.form  argument in icc() beyond the package documentation which says "formula containing group-level effects to be considered in the prediction. If NULL (default), include all group-level effects. Else, for instance for nested models, name a specific group-level effect to calculate the variance decomposition for this group-level". Any chance you can provide more information on what that formula should look like? I'm striking out on all of my attempts. Further, when I try to use the by_group argument for a brms object I get the same output as when I don't include it. In other words, by_group = TRUE doesn't yield variance ratios by group. Is this a limitation for brms models specifically? Lastly, even if I could get both of these elements to work I'm not sure I fully understand what the difference between the two would be. Any additional information would be very welcome, thank you!
-- | --

**Comment by strengejacke** [comment]
We have revised the docs and added more details. Does this help?
