### ISSUE TITLE
Change appearance of check_models panel output

### ISSUE THREAD

**Issue by TheDom42** [easystats/performance#126]
First of all: thank you for the great functionality of the `check_model` method! Very helpful in determining possible problems with the LMM I fitted.

However, I would like to propose an enhancement to the method as in my case, the plot produced by it, was not really "publication-ready" (see below).
Unfortunately many labels and titles were cut off or overlapped up to the point of being unreadable.

![grafik](https://user-images.githubusercontent.com/26472356/83421281-21be7b00-a428-11ea-8542-d3bccf7a3889.png)

As such assumption plots are mostly going to an appendix or additional material anyways (and are therefore not bound to very strict size restrictions), it would (IMHO) probably be possible to resolve these issues by being able to specify the number of rows and/or columns in the function call.
I am aware of the possibility to produce single plots using `panel = F` and I actually tried to plot them together manually using `ggarrange`, however I failed as I could not generate the required `grub`s from `performance` or `see`.

As I have seen that you use the `plots` method from `see` in the backend anyways (which offers the `n_rows` and `n_columns` arguments), I think, this should be possible to do.

Looking forward to your thoughts!

**Comment by strengejacke** [comment]
Most of the plots can be directly created via the related functions, see [this vignette](https://easystats.github.io/see/articles/performance.html) for an overview. I now also added the normality-check for mixed models/random effects, so once you update _performance_ and _see_ from CRAN, you can also create this plot:

``` r
library("lme4")
#> Loading required package: Matrix
library("performance")

m <- lmer(Reaction ~ Days + (Days | Subject), sleepstudy)

check_normality(m)
#> Warning: Non-normality of residuals detected (p < .001).

check_normality(m, effects = "random")
#> Group: Subject
#> (Intercept) OK: random effects appear as normally distributed (p = 0.428).
#>        Days OK: random effects appear as normally distributed (p = 0.898).

plot(check_normality(m))
#> Warning: Non-normality of residuals detected (p < .001).
```

![](https://i.imgur.com/xDizm0u.png)

``` r

plot(check_normality(m, effects = "random"))
#> Group: Subject
#> (Intercept) OK: random effects appear as normally distributed (p = 0.428).
#>        Days OK: random effects appear as normally distributed (p = 0.898).
#> [[1]]
#> `geom_smooth()` using formula 'y ~ x'
```

![](https://i.imgur.com/zC7sxV3.png)

<sup>Created on 2020-06-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by TheDom42** [comment]
Sorry for the long wait with an update on the situation.
Thank you for the explanation.

Unfortunately the "split" approach to generate the plots does not seem to work as intended.
I'm not working with "regular" `lmer` or `lmerTest` models but with `mixed` objects from the `afex` [package](https://github.com/singmann/afex), which provides an interface for the full `lmer` model object via the `$` operator.

The multicollinearity test works but the other two (normality and heteroscedasticity) require a separate `data` argument, which I cannot seem to get working (in the `reprex` below, the multicollinearity is left out because the data set is not suitable, with my regular data set it works out). The actual tests do seem to run but the plot rendering does not. Running `check_model` on the exact same model works like a charm.

Packages are up to date (see session info below, I left out the irrelevant packages).

``` r
library(afex)
#> Loading required package: lme4
#> Loading required package: Matrix
#> Registered S3 methods overwritten by 'car':
#>   method                          from
#>   influence.merMod                lme4
#>   cooks.distance.influence.merMod lme4
#>   dfbeta.influence.merMod         lme4
#>   dfbetas.influence.merMod        lme4
#> ************
#> Welcome to afex. For support visit: http://afex.singmann.science/
#> - Functions for ANOVAs: aov_car(), aov_ez(), and aov_4()
#> - Methods for calculating p-values with mixed(): 'KR', 'S', 'LRT', and 'PB'
#> - 'afex_aov' and 'mixed' objects can be passed to emmeans() for follow-up tests
#> - NEWS: library('emmeans') now needs to be called explicitly!
#> - Get and set global package options with: afex_options()
#> - Set orthogonal sum-to-zero contrasts globally: set_sum_contrasts()
#> - For example analyses see: browseVignettes("afex")
#> ************
#> 
#> Attaching package: 'afex'
#> The following object is masked from 'package:lme4':
#> 
#>     lmer
library(performance)

m <- mixed(Reaction ~ Days + (Days | Subject), sleepstudy)
#> Contrasts set to contr.sum for the following variables: Subject
#> Numerical variables NOT centered on 0: Days
#> If in interactions, interpretation of lower order (e.g., main) effects difficult.
#> Fitting one lmer() model. [DONE]
#> Calculating p-values. [DONE]

#### Normality ####
## does not work
check_normality(m$full_model)
#> Warning: Non-normality of residuals detected (p < .001).
plot(check_normality(m$full_model))
#> Warning: Non-normality of residuals detected (p < .001).
#> Error: Failed at retrieving data :( Please provide original model or data through the `data` argument
plot(check_normality(m$full_model, effects = "random"))
#> Group: Subject
#> (Intercept) OK: random effects appear as normally distributed (p = 0.428).
#>        Days OK: random effects appear as normally distributed (p = 0.898).
#> Error: Failed at retrieving data :( Please provide original model or data through the `data` argument
plot(check_normality(m$full_model, type = "qq"))
#> Warning: Non-normality of residuals detected (p < .001).
#> Error: Failed at retrieving data :( Please provide original model or data through the `data` argument

#### Heteroscedasticity ####
## does not work
plot(check_heteroscedasticity(m$full_model))
#> Warning in deviance.merMod(x): deviance() is deprecated for REML fits;
#> use REMLcrit for the REML criterion or deviance(.,REML=FALSE) for deviance
#> calculated at the REML fit
#> Warning: Heteroscedasticity (non-constant error variance) detected (p = 0.000).
#> Error: Failed at retrieving data :( Please provide original model or data through the `data` argument

#### Check Model ####
check_model(m$full_model)
#> Not enough model terms in the conditional part of the model to check for multicollinearity.
#> `geom_smooth()` using formula 'y ~ x'
#> `geom_smooth()` using formula 'y ~ x'
#> `geom_smooth()` using formula 'y ~ x'
#> `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
#> Warning: Removed 173 rows containing missing values (geom_text_repel).
#> `geom_smooth()` using formula 'y ~ x'
```

![](https://i.imgur.com/9vbTBw5.png)

<sup>Created on 2020-07-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

<details>

<summary>Session info</summary>

``` r
devtools::session_info()
#> - Session info ---------------------------------------------------------------
#>  setting  value                       
#>  version  R version 4.0.0 (2020-04-24)
#>  os       Windows 10 x64              
#>  system   x86_64, mingw32             
#>  ui       RTerm                       
#>  language (EN)                                     
#>  date     2020-07-03                  
#> 
#> - Packages -------------------------------------------------------------------
#>  package      * version     date       lib source                                         
#>  afex         * 0.27-2      2020-03-28 [1] CRAN (R 4.0.0)                                    
#>  lme4         * 1.1-23      2020-04-07 [1] CRAN (R 4.0.0)                                   
#>  Matrix       * 1.2-18      2019-11-27 [2] CRAN (R 4.0.0)                                    
#>  performance  * 0.4.7       2020-06-14 [1] CRAN (R 4.0.0)                                   
#>  see            0.5.1       2020-06-13 [1] CRAN (R 4.0.0)                  
```

</details>
