### ISSUE TITLE
Multi-response models +  performance +  see  = 😍

### ISSUE THREAD

**Issue by jacopastorius** [easystats/performance#129]
❤️ your work, and I also ❤️ multi-response models. Any thoughts about when such models might be supported? 

e.g.: 
```r
data("BTdata", package = "MCMCglmm")
library(brms)
library(performance)
library(see)
fit1 <- brm(
  mvbind(tarsus, back) ~ sex + hatchdate + (1|p|fosternest) + (1|q|dam),
  data = BTdata)
mf1 <-model_peformance(fit1)
plot(mf1)
```

**Comment by strengejacke** [comment]
Did you really mean a `plot()` method for `model_performance()`? There's no plot-method yet, for any model. But yes, we cannot postpone https://github.com/easystats/bayestestR/issues/31 forever...

**Comment by strengejacke** [comment]
_bump_

**Comment by jacopastorius** [comment]
I'm sorry @strengejacke, I was not clear. I meant:

library(see)
see::plot(mf1)

I wish I could contribute myself, and will try to upskill eventually to help at that level. For now, I am grateful for the time that you've put into these and your other wonderful packages.

**Comment by strengejacke** [comment]
I wonder what kind of plot you would expect? `model_performance()` returns AIC, BIC, R2 etc., and I cannot imagine how to plot these fit measures - in particular, since these are on very different scales, it would be rather confusing having these indices on the same axis.

There is a `plot()` method for `compare_performance()`: https://easystats.github.io/see/articles/performance.html#compare-model-performances-1

But you don't mean that one, do you?

**Comment by jacopastorius** [comment]
Sorry for the confusion @strengejacke, I misstated the issue. I think the following single response model would return a graph.

fit1 <- brm(
tarsus ~ sex  + (1|dam),
  data = BTdata)

s1<-parameters::model_parameters(fit1, effects = "all")
see::plot(s1,  sort = TRUE)

**Comment by strengejacke** [comment]
There were some issues with brms-multiple-response models, however, I think these are fixed now. Once _parameters_ and _see_ are updated (for now, on GitHub, but CRAN submission planned soon), it should work:

``` r
data("BTdata", package = "MCMCglmm")
library(brms)
#> Loading required package: Rcpp
#> Loading 'brms' package (version 2.13.5). Useful instructions
#> can be found by typing help('brms'). A more detailed introduction
#> to the package is available through vignette('brms_overview').
#> 
#> Attaching package: 'brms'
#> The following object is masked from 'package:stats':
#> 
#>     ar
library(parameters)
library(see)
fit1 <- brm(
  mvbind(tarsus, back) ~ sex + hatchdate + (1|p|fosternest) + (1|q|dam),
  data = BTdata, cores = 6, refresh = 0)
#> Setting 'rescor' to TRUE by default for this model
#> Warning: In the future, 'rescor' will be set to FALSE by default for all models.
#> It is thus recommended to explicitely set 'rescor' via 'set_recor' instead of
#> using the default.
#> Compiling Stan program...
#> Start sampling
mf1 <- model_parameters(fit1, test = NULL)
plot(mf1)
```

![](https://i.imgur.com/qnqtu0g.png)

<sup>Created on 2020-08-31 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by jacopastorius** [comment]
Awesome, you guys are great. V.grateful for your time.



Joseph Bulbulia
M: +64275615795
http://www.orcid.org/0000-0002-5861-2056
