### ISSUE TITLE
FR: McFadden Pseudo R2 for nnet::multinom

### ISSUE THREAD

**Issue by iago-pssjd** [easystats/performance#132]
Hi!

I think it would be a good idea to output the McFadden Pseudo R2  for the `multinom` models by library `nnet`. When I do `model_performance` applied to such a model, it prints `AIC, BIC, R2_Nagelkerke` and `RMSE`.

I also saw that library `DescTools` has a fucntion `PseudoR2` with different options, but it does not work properly.

Thank you!

**Comment by strengejacke** [comment]
We decided to show the "most appropriate" R2 value only for `model_performance()` (resp. `r2()`), where "most appropriate" is our subjective judgement. However, you can also calculate other R2:

``` r
library(MASS)
library(nnet)
library(performance)
oc <- options(contrasts = c("contr.treatment", "contr.poly"))
example(birthwt)
m <- multinom(low ~ ., bwt)
r2_mcfadden(m)
#> # R2 for Generalized Linear Regression
#> 
#>        R2: 0.167
#>   adj. R2: 0.159
```

<sup>Created on 2020-08-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by iago-pssjd** [comment]
Thank you!

I already was computing the McFadden Pseudo R2 through the formula, but with `r2_mcfadden` it will be simpler. 

The line in your code `oc <- options(contrasts = c("contr.treatment", "contr.poly"))` has some function? I get the same output without it.
