### ISSUE TITLE
Check_heteroscedasticity not working for glmmTMB on latest version of R

### ISSUE THREAD

**Issue by Vonchy** [easystats/performance#134]
I always get this error no matter the different models I try with glmmTMB: Error in model.frame.default(formula = .U ~ stats::fitted(x), drop.unused.levels = TRUE) : 
  variable lengths differ (found for 'stats::fitted(x)').

R version 4.0.2 (2020-06-22)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Other people have ran my code in their computers and the function works and they have the same version of performance package
Please I would appreciate if you could check if there could be potentially a bug . Thank you!

**Comment by strengejacke** [comment]
Thanks, should work now.
