### ISSUE TITLE
variance decomposition: cannot pass argument `ntrys` to brms::posterior_predict()

### ISSUE THREAD

**Issue by balthasarbickel** [easystats/performance#136]
Would it be possible to allow `ntrys` specifications in `variance_decomposition()` to pass to `brms::posterior_predict()`? This is helpful for truncated discrete models.

**Comment by strengejacke** [comment]
Should work now, could you please install from GitHub and check?

**Comment by balthasarbickel** [comment]
Success! Many thanks for the quick response!
