### ISSUE TITLE
Feature request to include statistical test in model fit comparison

### ISSUE THREAD

**Issue by Ohlsen** [easystats/performance#141]
In the vignette for CFA-output https://stat.ethz.ch/CRAN/web/packages/parameters/vignettes/efa_cfa.html you write 

> We’ve seen above that while an EFA with 5 latent variables works great on our dataset, a structure with 6 latent factors might in fact be more appropriate. How can we **statistically test** if that’s actually the case? 

Then you proceed to show the appealing output of performance::compare_performance(), which gives a side-by-side-comparison of model-fit of the models. 

This function is very interesting for researchers that need to do tests of measurement equivalence of CFA-models where you have an hierarchical sequence of nested models with an increasing number of parameters set to be equal across groups. How the model fit develops from each model to the next is a key question in this analysis.

I think, and this is just a suggestion for a future release, it would save these researchers some time if the performance::compare_performance() could also show results of the lavaan::lavTestLRT() function in the output table. Of course this would require some thought to the order in which models are entered. But this way, the statistical test mentioned in the quote above would in fact be included in the analysis.

**Comment by strengejacke** [comment]
Thanks! I moved this issue to the _performance_ repository, as this feature would be covered by this package.

**Comment by strengejacke** [comment]
This might be related to https://github.com/easystats/performance/issues/128

**Comment by strengejacke** [comment]
And https://github.com/easystats/performance/issues/36

**Comment by mattansb** [comment]
@DominiqueMakowski This would be resolved by #180, no?

**Comment by strengejacke** [comment]
Yes, actually addressed in #187

**Comment by DominiqueMakowski** [comment]
Yeah, it would be part of the model testing overhaul. For now I was focusing on regular regression models: my short term plan is now to add more documentation to the `test_*` explaining each test. Then, we should check / verify the support for other models types (mixed, bayesian, and especially lavaan objects indeed).
