### ISSUE TITLE
Using specific metrics for comparing performance of different model

### ISSUE THREAD

**Issue by JauntyJJS** [easystats/performance#142]
Hi,

Apologies for this naive question.
I understand from https://easystats.github.io/performance/reference/compare_performance.html that it is possible to compare different models using different metrics.

Because of my small sample size,  I want to use only adjusted R2 and the second order AIC. May I ask what should I put in `metrics` in the `compare_performance` function so that the function will compare based on these two values ?

Thank you.

**Comment by strengejacke** [comment]
Is it this you were asking for?

``` r
library(performance)
data(iris)
lm1 <- lm(Sepal.Length ~ Species, data = iris)
lm2 <- lm(Sepal.Length ~ Species + Petal.Length, data = iris)
lm3 <- lm(Sepal.Length ~ Species * Petal.Length, data = iris)
compare_performance(lm1, lm2, lm3, metrics = c("R2_adj", "AICc"), rank = TRUE)
#> # Comparison of Model Performance Indices
#> 
#> Name | Model |    AICc | R2 (adj.) | Performance-Score
#> ------------------------------------------------------
#> lm2  |    lm | 106.649 |     0.833 |            99.65%
#> lm3  |    lm | 107.556 |     0.835 |            99.64%
#> lm1  |    lm | 231.728 |     0.614 |             0.00%
```

<sup>Created on 2021-02-23 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by JauntyJJS** [comment]
Yes that is correct
