### ISSUE TITLE
Naming convention for SCORE_*

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/performance#147]
Just wanted to make sure here, was it on purpose that some of the indices are in full capital?

``` r
m2 <- glm(vs ~ wt + mpg, data = mtcars, family = "binomial")
performance::model_performance(m2)
#> # Indices of model performance
#> 
#>   AIC |   BIC | R2_Tjur | RMSE | LOGLOSS | SCORE_LOG | SCORE_SPHERICAL |  PCP
#> -----------------------------------------------------------------------------
#> 31.30 | 35.70 |    0.48 | 0.89 |    0.40 |    -14.90 |            0.10 | 0.74
```

<sup>Created on 2020-10-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

LOGLOSS SCORE_LOG instead of Logloss, Score_Log etc.

**Comment by strengejacke** [comment]
No, not on purpose.

**Comment by DominiqueMakowski** [comment]
should we change or too late?

**Comment by strengejacke** [comment]
@IndrajeetPatil ?

**Comment by strengejacke** [comment]
Logloss should probably be `Log_loss`?

**Comment by IndrajeetPatil** [comment]
Yeah, `LOG_LOSS` sounds better to me as well.

**Comment by strengejacke** [comment]
@IndrajeetPatil Mainly we think about changing the case of column names to be conform with our naming conventions. My question was if changing column names would affect your packages? In particular broom.extra?

**Comment by IndrajeetPatil** [comment]
No, not at all. Feel free to change them however you like. I am flexible to adjust to whatever naming convention you adopt. None of this will be a _breaking change_ for sure.

**Comment by strengejacke** [comment]
I hope these were all now?

**Comment by strengejacke** [comment]
Column names for `model_performance()` and `compare_performance()` were changed to be in line with the _easystats_ naming convention: `LOGLOSS` is now `Log_loss`, `SCORE_LOG` is `Score_log` and `SCORE_SPHERICAL` is now `Score_spherical`.

**Comment by strengejacke** [comment]
(`SIGMA` is `Sigma`, but since sigma column is new anyway, I didn't it mention in the news).

**Comment by DominiqueMakowski** [comment]
looks good
