### ISSUE TITLE
`model_performance` errors with one-sample BayesFactor t-test

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/performance#159]
``` r
library(BayesFactor)
#> Loading required package: coda
#> Loading required package: Matrix
#> ************
#> Welcome to BayesFactor 0.9.12-4.3. If you have questions, please contact Richard Morey (richarddmorey@gmail.com).
#> 
#> Type BFManual() to open the manual.
#> ************

mod <- ttestBF(mtcars$wt, mu = 3)

performance::model_performance(mod)
#> Error in ttestOneSample.Gibbs(y = data$y, nullModel, iterations = iterations, : unused argument (unreduce = FALSE)
```

<sup>Created on 2020-11-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by strengejacke** [comment]
@mattansb Where is the argument `unreduced` used? It's no official argument in `insight::get_parameters()`, but passed down to other methods (https://github.com/easystats/insight/blob/b948bf3281a9f3d96d048ac030f9e669ad9c481b/R/get_parameters.R#L1787).

You're calling `get_parameters(unreduced = TRUE)` from here: https://github.com/easystats/performance/blob/7b45d17710d4bc2706859439ea6f53bbca724444/R/r2_bayes.R#L211

Does this require the dev of BFBayesFactors? If so, should we "switch" the call to `get_parameters()` depending on `packageVersion()`?

**Comment by mattansb** [comment]
It get's passed to `BayesFactor::posterior()`.
R2 / model_performance is only supported for strictly linear models. Added proper error.

**Comment by mattansb** [comment]
(this does is unrelated to the version of BayesFactor. Only linear models have any indices of performance - should have caught this when I first implamented it)

**Comment by strengejacke** [comment]
Ok, @IndrajeetPatil or @mattansb, can you add a filter that returns NULL for non-supported BF objects? I'm not exactly sure what to do here.

**Comment by mattansb** [comment]
Yeah, you can assign this to me. I'll do it tomorrow 👍

**Comment by mattansb** [comment]
Done, I think...

**Comment by IndrajeetPatil** [comment]
Sorry, I can't seem to find the commit that solves this issue.

**Comment by mattansb** [comment]
Oh, you also wanted me to *push* the commit? RUDE!

**Comment by IndrajeetPatil** [comment]
One more context where this behavior is observed:

```r
library(BayesFactor)
#> Loading required package: coda
#> Loading required package: Matrix
#> ************
#> Welcome to BayesFactor 0.9.12-4.3. If you have questions, please contact Richard Morey (richarddmorey@gmail.com).
#> 
#> Type BFManual() to open the manual.
#> ************

# meta-analysis
t <- c(-.15, 2.39, 2.42, 2.43, -.15, 2.39, 2.42, 2.43)
N <- c(100, 150, 97, 99, 99, 97, 100, 150)

# Using `rscale = 1` and one-sided test to be
# consistent with Rouder & Morey (2011)
mod <- meta.ttestBF(t, N, rscale = 1, nullInterval = c(0, Inf))

performance::model_performance(mod)
#> Multiple `BFBayesFactor` models detected - posteriors are extracted from the first numerator model.
#> See help("get_parameters", package = "insight").
#> Error in meta.t.Metrop(t = data$t, n1 = data$n1, n2 = data$n2, nullModel, : unused argument (unreduce = FALSE)
```

**Comment by strengejacke** [comment]
> mod <- meta.ttestBF(t, N, rscale = 1, nullInterval = c(0, Inf))

Is this rather a meta-analysis or a t-test?

**Comment by IndrajeetPatil** [comment]
Meta-analysis

**Comment by strengejacke** [comment]
Ok, so it's detected correctly by `model_info()`.

**Comment by mattansb** [comment]
Done (even pushed this time!)
