### ISSUE TITLE
Somer's D?

### ISSUE THREAD

**Issue by bwiernik** [easystats/performance#162]
When reporting overall model fit for logistic regression models, my preferred R-squared-like statistic is Somer's D, the rank correlation between the observed response variables (0, 1) and the predicted probabilities (e.g., as in `Hmisc::somers2`). I was wondering if this statistic could be added to the family of `r2_` functions or elsewhere in _performance_?

**Comment by strengejacke** [comment]
``` r
library(performance)
model <- glm(vs ~ wt + mpg, data = mtcars, family = "binomial")

r2_somers(model)
#> Somers' Dxy 
#>   0.8253968

Hmisc::somers2(predict(model, type = "response"), mtcars$vs)
#>          C        Dxy          n    Missing 
#>  0.9126984  0.8253968 32.0000000  0.0000000
```

<sup>Created on 2020-11-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by strengejacke** [comment]
requires the latest GitHub version from the [_correlation_ package](https://github.com/easystats/correlation).

**Comment by bwiernik** [comment]
Wow! That was fast!
