### ISSUE TITLE
Error in print.check_model(x)

### ISSUE THREAD

**Issue by benjaminwnelson** [easystats/performance#163]
I tried to use the check_model function and got this error even though the see package was downloaded. Any ideas?
Error in print.check_model(x) : Package 'see' required to plot model assumptions. Please install it.

**Comment by strengejacke** [comment]
Can you please post your session info?

**Comment by strengejacke** [comment]
Like, the (reprex-)output from this code-snippet:

```r
library(performance)
m <- lm(mpg ~ wt + cyl + gear + disp, data = mtcars)
check_model(m)

sessionInfo()
```

**Comment by strengejacke** [comment]
_bump_

**Comment by strengejacke** [comment]
_bump_
