### ISSUE TITLE
Updating `model_performance()`

### ISSUE THREAD

**Issue by strengejacke** [easystats/performance#17]
Now that we have `mse()`, `rmse()` and `rse()`, we might include one of these measures in `model_performance()` as well, at least the RMSE I would say.

Maybe `error_rate()` also for `model_performace()`-glm?

**Comment by DominiqueMakowski** [comment]
I do agree! I feel like `model_performance()` should be the equivalent of `I_am_too_lazy_to_look_up_the_doc,_just_give_me_everything_suited_to_my_model!()` 

We should just eventually make a small selection in reports, which `fulltable` currently returns pretty much all indices from model_performance.

**Comment by strengejacke** [comment]
I have thought about revising `model_performance()`. We no longer have generics for different methods, but just `model_performance(...)`, that accepts multiple model objects, and returns the complete results (i.e. data frame with multiple rows, one per model - and we could add the model's name and class to the output as well).

What do you think?

**Comment by DominiqueMakowski** [comment]
totally makes sense indeed! 

I feel like this is going to lead to the addition of some arguments to e.g. arrange the models based on some indices etc :)

**Comment by strengejacke** [comment]
I have no good idea how to implement this... We could either remove all class-specific `model_performance.*()` functions, however, since we have different metrics, it makes sense to have these functions.

However, I can't have a function `model_performance()` in general, because the class-specific methods are called first.

I think we must give this function that accepts multiple models a new name, but it will exist beside the existing `model_performance()`-functions for each model-class...

Or do you have any ideas on this?

**Comment by DominiqueMakowski** [comment]
Hum I am not sure... 

The way I was imagining it was to add the ellipsis as the second argument for all methods (`model_performance.modeltype1(model, ..., args)`). Then, at the beginning of all methods, we would check if the ellipsis contains another model. If the total of models > 1, we would pass everything to a separate unified internal function, for instance `.model_performance_comparison()` that would re-apply model_performance for each individual model and merge the results... Would that make sense?

If that's not an option, having a separate function, `compare_performance()` would also be ok.

**Comment by DominiqueMakowski** [comment]
Maybe the separate function option would even be better to start with...?

**Comment by strengejacke** [comment]
> model_performance.modeltype1(model, ..., args)

This would call `model_performance()` inside `model_performance()` for different class-objects... I'm not sure if this works, at least I couldn't get it working.

> compare_performance()

That's a good name! So we have that one, and `model_performance()` for a single object.

**Comment by DominiqueMakowski** [comment]
Let's go for `compare_performance` then. This sparks the idea of a `compare_parameters` that could be used to compare coefficient across models...
