### ISSUE TITLE
Add function for model df

### ISSUE THREAD

**Issue by mattansb** [easystats/performance#173]
Talking about:

``` r
model_df <- function(model) {
  attr(logLik(model),"df")
}

m1 <- glm(Claims ~ Group + Age + Holders,
          family = poisson,
          data = MASS::Insurance)

m2 <- lm(mpg ~ ., mtcars)

m3 <- lme4::lmer(mpg ~ cyl + (1|gear), mtcars)
#> boundary (singular) fit: see ?isSingular

model_df(m1)
#> [1] 8

model_df(m2)
#> [1] 12

model_df(m3)
#> [1] 4
```

**Comment by strengejacke** [comment]
I bet there are 747.246.753.196 exceptions, if there are any possibilities at all to retrieve this information.

**Comment by DominiqueMakowski** [comment]
But it's true that we could add that to insight `get_df`, we could probably easily make it work at least for basic models?

**Comment by mattansb** [comment]
Any object that has a BIC method should have a loglik method...

> ... we could add that to insight `get_df` ...

I would name it maybe `get_df_model()` / `get_model_df()`, so as not to confuse with `df.residual()`.

**Comment by DominiqueMakowski** [comment]
Get_df could return a list of either model Dfs or residuals, unless specified in a "type" argument similar to get_parameters?

**Comment by strengejacke** [comment]
We have `degrees_of_freedom()` in _parameters_.

**Comment by strengejacke** [comment]
We have three different candidates here:

``` r
m <- lm(mpg ~ wt + cyl + gear + disp, data = mtcars)

# "model" df?
attr(logLik(m), "df")
#> [1] 6

# parameter df?
parameters::degrees_of_freedom(m)
#> [1] 27

# residual / parameter / denominator df?
df.residual(m)
#> [1] 27

# numerator df?
summary(m)$fstatistic["numdf"]
#> numdf 
#>     4
```

<sup>Created on 2020-12-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I'd like to know what you consider as "model df", as opposed to the "classical" df (residual df, or n-k)?

**Comment by DominiqueMakowski** [comment]
I think for https://github.com/easystats/performance/issues/180 it would be the one returned by `df.residuals`

https://github.com/easystats/performance/blob/1960f82eb67b35a17dd96eb9f2f600b116eeb2d5/R/performance_lrt.R#L185-L187

But then I'm not sure what's a good API for all that 😕

**Comment by DominiqueMakowski** [comment]
Maybe we should simply add ad `df_residuals()`

**Comment by mattansb** [comment]
``` r
m0 <- lm(mpg ~ 1, mtcars)
m1 <- lm(mpg ~ wt + cyl + gear + disp, data = mtcars)

# "model" df
attr(logLik(m0), "df")
#> [1] 2
attr(logLik(m1), "df")
#> [1] 6
```

This is the number of parameters in the model:
in the intercept model there are 2 parameters: the intercept *and* sigma.
in the second model, intercept + predictors (4) + sigma

The *difference* between these is the numerator DF of the F-test:

``` r
summary(m1)$fstatistic["numdf"]
#> numdf 
#>     4
```
```R
# residual df = denominator df for F test
df.residual(m1)
#> [1] 27

# for  fized effect models - the df of SE is the same
parameters::degrees_of_freedom(m1) 
#> [1] 27
```

## For LMM

``` r
library(lmerTest)

m0 <- lmer(mpg ~ 1 + (1|carb), mtcars)
m1 <- lmer(mpg ~ wt + cyl + gear + disp + (disp|carb), data = mtcars)

attr(logLik(m0), "df") # parameters: intercept + var intercept + sigma
#> [1] 3
attr(logLik(m1), "df") # parameters: intercept + fixed (4) + var disp + var intercept + cov + sigma
#> [1] 9

# residual df
df.residual(m1)
#> [1] 23

# for mixed models - the df of SE is NOT the same
parameters::degrees_of_freedom(m1)
#> [1]  6.902713 18.557534  4.347266 16.285908  4.273165
```

<sup>Created on 2020-12-24 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by strengejacke** [comment]
@mattansb to summarize: the "model df" is `n_parameters()` + 1 (for sigma), and if `insight::has_intercept() == TRUE`, +1?

**Comment by strengejacke** [comment]
hm, or is it n_parameters, and +1 for mixed models?!?

``` r
m1 <- glm(Claims ~ Group + Age + Holders,
          family = poisson,
          data = MASS::Insurance)

insight::n_parameters(m1)
#> [1] 8
attr(logLik(m1), "df")
#> [1] 8
```

<sup>Created on 2021-01-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by strengejacke** [comment]
``` r
m2 <- lm(mpg ~ ., mtcars)
insight::n_parameters(m2)
#> [1] 11
attr(logLik(m2), "df")
#> [1] 12


m3 <- glm(mpg ~ ., data = mtcars)
insight::n_parameters(m3)
#> [1] 11
attr(logLik(m3), "df")
#> [1] 12


m4 <- glm(am ~ ., data = mtcars, family = binomial)
insight::n_parameters(m4)
#> [1] 11
attr(logLik(m4), "df")
#> [1] 11
```

<sup>Created on 2021-01-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by strengejacke** [comment]
``` r
model_df <- function(x) {
  out <- insight::n_parameters(x)
  ifelse(insight::model_info(x)$is_linear, out + 1, out)
}
m2 <- lm(mpg ~ ., mtcars)
model_df(m2)
#> [1] 12
attr(logLik(m2), "df")
#> [1] 12


m3 <- glm(mpg ~ ., data = mtcars)
model_df(m3)
#> [1] 12
attr(logLik(m3), "df")
#> [1] 12


m4 <- glm(am ~ ., data = mtcars, family = binomial)
#> Warning: glm.fit: algorithm did not converge
#> Warning: glm.fit: fitted probabilities numerically 0 or 1 occurred
model_df(m4)
#> [1] 11
attr(logLik(m4), "df")
#> [1] 11
```

<sup>Created on 2021-01-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by strengejacke** [comment]
Should be closed in https://github.com/easystats/insight/commit/9d18d59ce565e9e3c40d6262d16c2155a3edf56a

**Comment by mattansb** [comment]
You seem to be working really hard not to use `attr(logLik(model), "df")` - why?

> @mattansb to summarize: the "model df" is n_parameters() + 1 (for sigma), and if insight::has_intercept() == TRUE, +1?

Doesn't `n_parameters` already account for the intercept?

model df is the number of estimated parameters in the model - all parameters, also the distributional (this is the "true" `n_parameters`!):

```R
m <- lm(mpg ~ factor(cyl) + hp, mtcars)
```
![image](https://user-images.githubusercontent.com/35330040/103608693-97da1180-4f24-11eb-82b7-3801dcb1c8f0.png)

```R
attr(logLik(m), "df")
#> [1] 5


m <- lme4::lmer(mpg ~ factor(cyl) + hp + (hp | am), 
                mtcars)
```
![image](https://user-images.githubusercontent.com/35330040/103608847-01f2b680-4f25-11eb-8e0d-ee417103e475.png)

```R
attr(logLik(m), "df")
#> [1] 8
```

**Comment by DominiqueMakowski** [comment]
but then I think people would expect `n_parameters()` to return the number of parameters as in the number of rows of the parameters table, rather than some occult number that most have no clear picture of

**Comment by mattansb** [comment]
> rather than some occult number that most have no clear picture of

🕯🕯😈🕯💀🕯

I agree, that's why I'm not calling for this to be added to `n_parameters()` (even though people from the modelling community would probably expect that there. Maybe the docs should reflect that it doesn't return all the parameters, but only the fixed conditional parameters? or something)

**Comment by strengejacke** [comment]
> You seem to be working really hard not to use `attr(logLik(model), "df")` - why?

No, the default is `attr(logLik(model), "df")`, and when this fails, it uses n_parameters().

**Comment by mattansb** [comment]
When does this fail? 🤔

**Comment by strengejacke** [comment]
For each model that does not have a `logLik()` function...

**Comment by mattansb** [comment]
Well good luck to those models!
