### ISSUE TITLE
Plot QQ-plot bands with qqplotr

### ISSUE THREAD

**Issue by mattansb** [easystats/performance#175]
I suggest switching over to qqplotr for confidence bands in QQ-plots (it is my understanding that currently we are relying on geom_smooth for this?).
The `qqplotr` package has geoms/stats for correct confidence bands in QQ-plots.

**Comment by mattansb** [comment]
I'm assuming this is in *see*? Is it okay if I make these changes?

**Comment by strengejacke** [comment]
Yeah, or we might re implement from here:
https://github.com/aloy/qqplotr/blob/14d613578c4555ddc389bedd674da8d09bc9aee1/R/stat_qq_band.R#L340

But I'm fine with both.

**Comment by DominiqueMakowski** [comment]
I'd sau if it's easy to reimplement let's do that rather than adding a dependency, especially for one feature

**Comment by mattansb** [comment]
We can add the bands conditionally - only is the package is available, but add the QQ-line either way (as it is available in ggplot).

**Comment by mattansb** [comment]
Look at the difference using these bands makes - it makes the data seem a lot less shitty! 😍

## QQ-Plot

Before:

``` r
m <- lm(am ~ ., data = mtcars)

norm_check <- performance::check_normality(m)
#> OK: residuals appear as normally distributed (p = 0.134).
plot(norm_check, type = "qq")
#> `geom_smooth()` using formula 'y ~ x'
```

![](https://i.imgur.com/Ue7LNVu.png)

<sup>Created on 2020-12-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

After:

``` r
m <- lm(am ~ ., data = mtcars)

norm_check <- performance::check_normality(m)
#> OK: residuals appear as normally distributed (p = 0.134).
plot(norm_check, type = "qq")
#> Loading required namespace: qqplotr
```

![](https://i.imgur.com/fVEUuvz.png)

<sup>Created on 2020-12-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Note that the old plot *wasn't* a qq-plot! It had the sorted fitted vs sorted residuals - which is close(ish), but not quite.

## PP-Plot

_PP-plot now requires `MASS` OR `qqplotr` (trying first qqplotr for the confidence bands)._

``` r
m <- lm(am ~ ., data = mtcars)

norm_check <- performance::check_normality(m)
#> OK: residuals appear as normally distributed (p = 0.134).
plot(norm_check, type = "pp")
#> `geom_smooth()` using formula 'y ~ x'
```

![](https://i.imgur.com/QQtAlhY.png)

<sup>Created on 2020-12-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

After:

``` r
m <- lm(am ~ ., data = mtcars)

norm_check <- performance::check_normality(m)
#> OK: residuals appear as normally distributed (p = 0.134).
plot(norm_check, type = "pp")
```

![](https://i.imgur.com/8BO5RJG.png)

<sup>Created on 2020-12-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by strengejacke** [comment]
nice, thanks!
