### ISSUE TITLE
Cannot download the package from a macbook, the download link is broken

### ISSUE THREAD

**Issue by anichanian** [easystats/performance#176]
I can't install the package from my Macbook in RStudio. The download link for Mac users from CRAN seems to be broken. Can someone help me?
Thanks!

`> install.packages('performance')
trying URL 'https://cran.rstudio.com/bin/macosx/contrib/4.0/performance_0.6.1.tgz'
Warning in install.packages :
  cannot open URL 'https://cran.rstudio.com/bin/macosx/contrib/4.0/performance_0.6.1.tgz': HTTP status was '404 Not Found'
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot open URL 'https://cran.rstudio.com/bin/macosx/contrib/4.0/performance_0.6.1.tgz'
Warning in install.packages :
  download of package ‘performance’ failed`

**Comment by strengejacke** [comment]
I think this is rather a CRAN server issue, and nothing we can actually fix. I bet this is temporary, and if not, try to download from here: https://cran.r-project.org/package=performance
