### ISSUE TITLE
performance_lrt(): no constant reference model?

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/performance#180]
``` r
m1 <- lm(Sepal.Length ~ Petal.Length * Species, data = iris)
m2 <- lm(Sepal.Length ~ Petal.Length + Species, data = iris)
m3 <- lm(Sepal.Length ~ Petal.Length, data = iris)

performance::performance_lrt(m1, m2, m3)
#> # Likelihood-Ratio-Test for Model Comparison
#> 
#> Model | Type |   RSS | Sum_Squares | df | df_error |      p
#> -----------------------------------------------------------
#> m1    |   lm | 16.30 |             |    |      144 |       
#> m2    |   lm | 16.68 |       -0.38 | -2 |      146 |  0.186
#> m3    |   lm | 24.53 |       -7.84 | -2 |      148 | < .001
```

<sup>Created on 2020-12-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Until now I thought that the first model was the "reference" model, and that subsequent comparison were done in respect to it. However, it seems like in fact m2 is compared to m1, and m3 is compared to m2 (see how the 'df' column, which is actually the difference of dfs, changes):

```r
> anova(m1, m3, test="LRT")

Analysis of Variance Table

Model 1: Sepal.Length ~ Petal.Length * Species
Model 2: Sepal.Length ~ Petal.Length
  Res.Df    RSS Df Sum of Sq  Pr(>Chi)    
1    144 16.301                           
2    148 24.525 -4   -8.2244 6.244e-15 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
```

As far as I remember, this is not the behaviour of the BF comparison which compares everything to the first right @mattansb ?

**Comment by DominiqueMakowski** [comment]
More or less related to that, anova(test="LRT") doesn't return the Chi² not the deviance, which is returned by this function:

``` r
library(report)
#> report is in alpha - help us improve by reporting bugs on github.com/easystats/report/issues

m1 <- lm(Sepal.Length ~ Petal.Length * Species, data = iris)
m2 <- lm(Sepal.Length ~ Petal.Length + Species, data = iris)
m3 <- lm(Sepal.Length ~ Petal.Length, data = iris)

anova(m1, m2, m3, test="LRT")
#> Analysis of Variance Table
#> 
#> Model 1: Sepal.Length ~ Petal.Length * Species
#> Model 2: Sepal.Length ~ Petal.Length + Species
#> Model 3: Sepal.Length ~ Petal.Length

#>   Res.Df    RSS Df Sum of Sq Pr(>Chi)    
#> 1    144 16.301                          
#> 2    146 16.682 -2   -0.3810   0.1859    
#> 3    148 24.525 -2   -7.8434    9e-16 ***
#> ---
#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1


lmtest::lrtest(m1, m2, m3)
#> Likelihood ratio test
#> 
#> Model 1: Sepal.Length ~ Petal.Length * Species
#> Model 2: Sepal.Length ~ Petal.Length + Species
#> Model 3: Sepal.Length ~ Petal.Length

#>   #Df  LogLik Df   Chisq Pr(>Chisq)    
#> 1   7 -46.384                          
#> 2   5 -48.116 -2  3.4654     0.1768    
#> 3   3 -77.020 -2 57.8077    2.8e-13 ***
#> ---
#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
```

<sup>Created on 2020-12-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

(The results are a bit different due to their method of calculation, as [explained here](https://stats.stackexchange.com/questions/155474/why-does-lrtest-not-match-anovatest-lrt))

Maybe we should actually [reimplement](https://github.com/cran/lmtest/blob/master/R/lrtest.R) the LRT for regressions altogether so that we can return whatever we want, including the Chi², which would in turn facilitates its reporting?

It could also allow us, *maybe*, to be able to expose the choice of the reference model, which could be useful if we want to keep the comparison consistent with the BF-comparison.

**Comment by mattansb** [comment]
> As far as I remember, this is not the behaviour of the BF comparison which compares everything to the first right @mattansb ?

That is correct.

**Comment by DominiqueMakowski** [comment]
> That is correct.

So it'd make sense to standardize the comparisons and have everything against the first model by default

**Comment by strengejacke** [comment]
So we can close this issue?

**Comment by mattansb** [comment]
> So it'd make sense to standardize the comparisons and have everything against the first model by default

Or to have the option to choose (and make the BF also sequential...) 🙃

**Comment by strengejacke** [comment]
The `estimator` argument is still not documented?

**Comment by DominiqueMakowski** [comment]
https://github.com/easystats/performance/blob/9c50f0d6c0fcf3b7f18c79a5c381da86de96b7f9/R/performance_lrt.R#L56

**Comment by strengejacke** [comment]
👍  Hm, there must have been a commit I missed. ;-)

**Comment by strengejacke** [comment]
Ah, ok. You added the documentation to the specific method, not the generic...

**Comment by DominiqueMakowski** [comment]
yeah coz otherwise I think it complained that it wasn't in the definition or something

**Comment by strengejacke** [comment]
So can we close this issue?

**Comment by DominiqueMakowski** [comment]
Yeah, though I'd still like to add the new likelihood functions from insight when it will go to CRAN. So maybe let's keep this open 'til then so that I have a reminder to refactor the code of LRT then

**Comment by strengejacke** [comment]
Ok, feel free to start with the refactoring now.

**Comment by strengejacke** [comment]
@DominiqueMakowski two questions related to this code:

https://github.com/easystats/performance/blob/bba584cb1e540c1ef73819e924926dbb2846d386/R/performance_lrt.R#L212-L217

1. `estimator = "ols"` is never possible, as another function will be called then.
2. Line 215, `loglik_function(model2, estim(model))` - is it correct that you use `model2` and `model` here? Is there a way to implement this in `insight::get_loglikelihood()` somehow?

**Comment by DominiqueMakowski** [comment]
> estimator = "ols" is never possible, as another function will be called then.

I know, I plan to refactoring it asap once we have all the ingredients in insight


> Line 215, loglik_function(model2, estim(model)) - is it correct that you use model2 and model here? Is there a way to implement this in insight::get_loglikelihood() somehow?

Yes, my hopes are be enable to pass the estimator directly (which could be a value from another model) in the loglikelihood function (instead of a character string), but let me try to work that out with the queen of formulas @Tam-Pham
