### ISSUE TITLE
RMSE for glms?

### ISSUE THREAD

**Issue by strengejacke** [easystats/performance#184]
``` r
library(performance)
data(sleepstudy, package = "lme4")

m1.1 <- glm(Reaction ~ Days, data = sleepstudy, family = gaussian())
m1.2 <- glm(Reaction ~ Days, data = sleepstudy, family = gaussian("log"))
m1.3 <- glm(Reaction ~ Days, data = sleepstudy, family = gaussian("inverse"))

m2.1 <- glm(Reaction ~ Days, data = sleepstudy, family = inverse.gaussian())
m2.2 <- glm(Reaction ~ Days, data = sleepstudy, family = inverse.gaussian("log"))
m2.3 <- glm(Reaction ~ Days, data = sleepstudy, family = inverse.gaussian("inverse"))

cp <- compare_performance(m1.1, m1.2, m1.3, m2.1, m2.2, m2.3)
cp
#> # Comparison of Model Performance Indices
#> 
#> Model | Type |     AIC |     BIC |     BF | Nagelkerke's R2 |     RMSE |    Sigma
#> ---------------------------------------------------------------------------------
#> m1.1  |  glm | 1906.29 | 1915.87 |   1.00 |            1.00 |    47.45 |    47.71
#> m1.2  |  glm | 1905.91 | 1915.49 |   1.21 |            1.00 |     0.15 |    47.66
#> m1.3  |  glm | 1905.82 | 1915.40 |   1.26 |            1.00 | 5.06e-04 |    47.65
#> m2.1  |  glm | 1892.06 | 1901.63 | > 1000 |            0.29 | 3.41e-06 | 9.13e-03
#> m2.2  |  glm | 1891.97 | 1901.55 | > 1000 |            0.29 |     0.15 | 9.12e-03
#> m2.3  |  glm | 1891.86 | 1901.44 | > 1000 |            0.29 | 5.06e-04 | 9.12e-03
```

<sup>Created on 2021-01-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

@mattansb @DominiqueMakowski As you can see, `m1.2` has an RMSE of 0.15 after changing `stats::residuals()` to `insight::get_residuals()` in `performance_mse()` (using `stats::residuals()` instead yields an RMSE of 47.4). The reason is that `stats::residuals.glm()` defaults to `type = "deviance"`, while `insight::get_residuals()` defaults to `type = "response"`. This brings up two questions:

1. which one is correct for the RMSE? The response- or deviance residuals?
2. should we use `type = "response"` as default in `insight::get_residuals()`? Currently, we only have this option, we do not return any other residuals here. We should definitely state this in the docs.

**Comment by strengejacke** [comment]
For now, I changed the default in `insight::get_residuals()` from `stats::residuals(type = "response")` to `stats::residuals(...)`. I think the default `type` argument should be used, however, we can always force certain types of residuals with `insight::get_residuals(type = "xyz")`.

**Comment by mattansb** [comment]
> which one is correct for the RMSE? The response- or deviance residuals?

response.

**Comment by strengejacke** [comment]
> > which one is correct for the RMSE? The response- or deviance residuals?
> 
> response.

And this is true for GLM as well?

**Comment by mattansb** [comment]
For any *quantitative* outcome, yes (categorical predictors don't have RMSE [even when they can accidentally be calculated because they are numerically coded] - ordinal, binomial, multinomial...)

**Comment by strengejacke** [comment]
Ok, but then RMSE for these two will differ a lot, and this is expected, right?

```r
m1.1 <- glm(Reaction ~ Days, data = sleepstudy, family = gaussian()) # RMSE 47.5
m1.2 <- glm(Reaction ~ Days, data = sleepstudy, family = gaussian("log")) # RMSE 0.15
```

**Comment by mattansb** [comment]
How is that possible?

``` r
data(sleepstudy, package = "lme4")


m1.1 <- glm(Reaction ~ Days, data = sleepstudy, family = gaussian()) # RMSE 47.5
m1.2 <- glm(Reaction ~ Days, data = sleepstudy, family = gaussian("log")) # RMSE 0.15


rmse <- function(m) {
  r <- residuals(m, type = "response")
  sqrt(mean(r^2))
}


rmse(m1.1)
#> [1] 47.4489
rmse(m1.2)
#> [1] 47.39881
```

<sup>Created on 2021-01-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by strengejacke** [comment]
> How is that possible?

Just saw that `get_residuals()` first tries to extract `model$residuals`, and if this fails, then calls `stats::residuals()`. However, `model$residuals` are no response residuals. Changed that order, should be fixed now.

**Comment by mattansb** [comment]
Can this be closed?

**Comment by strengejacke** [comment]
yep.
