### ISSUE TITLE
compare_performance and test_performance: scope 

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/performance#191]
Now that we have a fairly functioning test_performance, we should decide the scope of the functions. Essentially, either `compare_performance()` is the big function that returns all the indices + the tests (i.e., also runs `test_performance()`), or we keep them separate (in which case we should remove the BF col that it has currently). 

From the top of my head, arguments for having two distinct functions rather than one encompassing the other are:

- The table with all indices + tests will likely be very wide, and usually won't fit a page. So people will look for a way of separating it, and so we might as well just have them separately. 
- The comparison of indices and the testing of models are arguably conceptually different, so having it as two separate functions would make sense, and would help dissociate the steps rather than lumping everything together
- Arguments in favour of having comapre_performance() do all would be that it could be convenient in some cases to have one table for all... though you can argue that it's also quite easy to assemble them a posteriori if needed

What do you think?

**Comment by strengejacke** [comment]
I'd also vote for having two functions. Especially since row order of test columns might be messed up when using `compare_performance(rank = TRUE)`

**Comment by strengejacke** [comment]
Anything that should be addressed before submission? I just submitted _parameters_. For _performance_, I'm not sure if there's much pressure or if we should wait with submission until we have implemented the new features in a way we're satisfied with?
