### ISSUE TITLE
keeping CI in [0,1] range for `r2_bayes`

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/performance#193]
To be consistent with the rest of the `easystats` convention, the `CI` value should be in the [0,1] range.

``` r
library(BayesFactor)
library(performance)

BFM <- generalTestBF(mpg ~ qsec + gear, data = mtcars, progress = FALSE)

df <- as.data.frame(r2_bayes(BFM, average = TRUE, ci = 0.95)) 

df
#>          R2        SD CI    CI_low   CI_high
#> 1 0.4623963 0.1067465 95 0.2150859 0.6347402
```

<sup>Created on 2021-01-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by strengejacke** [comment]
?

**Comment by IndrajeetPatil** [comment]
CI here is `95`, when it should be `0.95`

**Comment by strengejacke** [comment]
The `CI` column has always been like that. It would be inconsistent to have it like `0.95`

**Comment by IndrajeetPatil** [comment]
Oh, you are right!

Sorry, I think I wanted to say that the `attributes`$ci should be `0.95`, since this attribute is missing for this object.

**Comment by IndrajeetPatil** [comment]
But is that actually true?

```r
library(effectsize)

# output contains ci width in `CI` column
as.data.frame(cohens_d(sleep$extra, sleep$group, ci = 0.99))
#>     Cohens_d   CI    CI_low   CI_high
#> 1 -0.8321811 0.99 -2.027956 0.3826775
```

**Comment by strengejacke** [comment]
Yeah, @mattansb actually is never listening to what we say...

**Comment by mattansb** [comment]
I'm a rebel!

**Comment by IndrajeetPatil** [comment]
Closing in favor of https://github.com/easystats/performance/issues/194
