### ISSUE TITLE
model_performance: argument discoverability and input checks

### ISSUE THREAD

**Issue by vincentarelbundock** [easystats/performance#209]
Two related issues:

1. In day-to-day use, I'm having a hard time discovering allowable arguments and metric names for different model types. When I type `?model_performance`, I see the generic's docs, with no mention of even the `metrics` argument. I had to lookup the code on github to figure out what was allowable for `brmsfit` models, and I'm still not sure what the faster way to find the same info would be.
2. When users supply bad arguments, it would be great if `model_performance` could return useful information about allowable values.

For sanity checks and assertions, but it would be easy enough to cook up your own version of `checkChoice`:
https://rdrr.io/cran/checkmate/man/checkChoice.html

If you give me the broad strokes of how you would like to see this evolve, I'm happy to try my hand at giving users something more useful than a `sapply`/ bracket error:

``` r
library("brms")
library("performance")

priors <- c(set_prior("normal(0, 10)", class = "Intercept"),
            set_prior("normal(0, 2.5)", class = "b"),
            set_prior("normal(0, 2.5)", class = "sd"))

tmp <- suppressMessages(capture.output(
mod <- brm(bf(mpg ~ disp + (1 | cyl)),
              data = mtcars,
              prior = priors,
              backend = "cmdstanr")))

model_performance(mod, metrics = "bad_metric")
#> Error in `[.default`(out, sapply(out, function(i) !all(is.na(i)))): invalid subscript type 'list
```

<sup>Created on 2021-03-09 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by strengejacke** [comment]
Regarding the 1. question: the help should bring you to https://easystats.github.io/performance/reference/model_performance.html, from where you can choose your "model class" and then you should be pointed to https://easystats.github.io/performance/reference/model_performance.stanreg.html - and there you find all relevant options for `metrics`.

2. question: yes, that probably makes sense. I think a simple `match()` for each `model_perfomance.xyz()` would do it to see if `metrics` has only valid options.

**Comment by strengejacke** [comment]
![help](https://user-images.githubusercontent.com/26301769/110690504-4da33400-81e4-11eb-9378-d27d862a0535.gif)

**Comment by strengejacke** [comment]
+1 for not using RStudio, but there are hardly better alternatives. Besides the standard IDE features, debugging, profiling, rmarkdown/notebooks, integratetion of Git are nice features.

**Comment by vincentarelbundock** [comment]
Thanks a lot. Sorry I didn't deliver a solution in time to save you the work, but I appreciate the improvement.

**Comment by strengejacke** [comment]
it wasn't that much work ;-)
