### ISSUE TITLE
Supporting CIs for AUC

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/performance#211]
Currently, we just return AUC values, but on Twitter, there was a feature request that we also support CIs for AUC

**Comment by strengejacke** [comment]
Is there a formula, or is it via bootstrapping?

**Comment by IndrajeetPatil** [comment]
Yes, it's done via bootstrapping. Here is an example of one implementation:
https://github.com/xrobin/pROC/blob/master/R/ci.auc.R
