### ISSUE TITLE
JOSS paper submission

### ISSUE THREAD

**Issue by strengejacke** [easystats/performance#221]
https://joss.readthedocs.io/en/latest/review_checklist.html

To do for the readme:

- [x] statement of need
- [x] community guidelines

To do for the paper:

- [x] regenerate plots
- [x] check DOIs

**Comment by IndrajeetPatil** [comment]
Partly addressed in #223

**Comment by IndrajeetPatil** [comment]
Checking `doi` for articles and `ISBN` codes for books in #225

**Comment by IndrajeetPatil** [comment]
I have never seen `Statement of Need` section in a `README`, so not sure what it should look like.

I will let you handle that point.

**Comment by strengejacke** [comment]
> I have never seen `Statement of Need` section in a `README`, so not sure what it should look like.
> 
> I will let you handle that point.

Like the first paragraph here: https://github.com/easystats/bayestestR

But I can do that.

**Comment by IndrajeetPatil** [comment]
Potential reviewers:
- RMHogervorst
- cimentadaj
- njtierney
- humanfactors

**Comment by IndrajeetPatil** [comment]
I think we just need to regenerate the figures, and then we should be all set for the submission. 

Unless, of course, @DominiqueMakowski or @mattansb have some other concerns that they want addressed before submission.

**Comment by mattansb** [comment]
I'm a bit weary of the `## Checking if a Model is Valid` section. Many assumptions can be violated and a model might still be considered "valid". E.g., homoscedasticity, normality of residuals, even independence (to some degree) can be violated and the model, as a *prediction* model will be valid (but any test within the model or any measures of fit that are based on likelihood/probability will not be valid).
So I think this section should be re-framed. Maybe just a general "Validating / Checking Assumptions"?

**Comment by IndrajeetPatil** [comment]
That's a good point. I have renamed that section to what you have suggested here.

**Comment by mattansb** [comment]
Alright 👍
I'll also edit that section a bit, if you don't mind (:

**Comment by strengejacke** [comment]
>  if you don't mind (:

You need my permission, I'm the lead author. 😈

**Comment by mattansb** [comment]
It is better to ask forgiveness, than permission :P

I made some edits (I used RStudio's *visual markdown editor* so some minor markings/white spaces may have been added/removed also).

**Comment by strengejacke** [comment]
@IndrajeetPatil can we knit a PDF in JOSS template / layout before we submit?

**Comment by IndrajeetPatil** [comment]
@strengejacke Yes, done in #228. Check out the pdf once it's merged.

**Comment by IndrajeetPatil** [comment]
Looks pretty ❤️ 

<img width="930" alt="Screenshot 2021-03-22 at 17 08 50" src="https://user-images.githubusercontent.com/11330453/112021739-e36a8780-8b31-11eb-8ef6-05b614174225.png">

**Comment by strengejacke** [comment]
@pdwaggoner is it ok for you to be listed as co author, and if so, do you have any comments on the paper? Since you contributed to the package and were involved in the development, I'd say this justifies a cop authorship, but of course only if you want to be listed on that paper.

**Comment by strengejacke** [comment]
Link to PDF: https://github.com/easystats/performance/blob/master/paper/paper.pdf

**Comment by pdwaggoner** [comment]
@strengejacke Thanks for the note and sorry I haven't been nearly as involved with easystats lately as I want to be. I have been keeping track of major changes and packages though, and love what I see and also share the goodness of easystats with others whenever possible. 

The paper looks awesome. I'd be happy to be included as a coauthor, if you think it makes sense. I defer to your judgement there. But I did look at the paper, and have a few grammatical changes that may make it a bit strong. Should I just make these via PR? Give you a list of suggested changes here? Or something else? Thanks and eager to contribute.

**Comment by strengejacke** [comment]
Philip, thank you, that sounds good! If you have suggestions, feel free to edit the paper directly or propose your changes via PR!

**Comment by pdwaggoner** [comment]
@strengejacke awesome, thanks! I just made the commit. As noted there, I have hacked it up a bit, but *didn't change any of the substance*. It looks great for the most part. I just moved some things around, corrected some grammatical issues, and streamlined some of the language to make it read a bit more fluidly. Of course feel free to revert if you don't like anything, or let me know and we can discuss. Thanks again for bringing me in on the paper. This is such a great suite of tools!

**Comment by pdwaggoner** [comment]
Oh yeah, I didn't re-render the PDF, in case you wanted to revert any of my changes. Feel free to render whenever you're happy with it.

**Comment by IndrajeetPatil** [comment]
I think we are all set for submission now (once the plots are regenerated)! 😄

**Comment by strengejacke** [comment]
which plots do we need to regenerate?

**Comment by IndrajeetPatil** [comment]
The radar chart is too big. I think we need to save it with slightly smaller dimensions. Or so I feel.

This might also help avoid the big empty space left on Page 5:
 https://github.com/easystats/performance/blob/master/paper/paper.pdf

**Comment by strengejacke** [comment]
@pdwaggoner I just read your revisions to the paper, very nice, thank you! It's always good to have a native speaker to prevent a rather "repetitive pattern language" ;-)

**Comment by strengejacke** [comment]
> The radar chart is too big. I think we need to save it with slightly smaller dimensions. Or so I feel.

![picard_make_it_so](https://user-images.githubusercontent.com/26301769/112115773-dbeec100-8bb9-11eb-95c5-63d33081a4a9.jpg)

**Comment by IndrajeetPatil** [comment]
Done! 

Nothing else on my end. :)

Unless anybody else has any other edits to make, we can go ahead with the submission!

**Comment by strengejacke** [comment]
I'll submit now.

**Comment by pdwaggoner** [comment]
Sounds great all - thanks! It's a great paper and package. Let me know if you need more from me downstream/during review.

**Comment by IndrajeetPatil** [comment]
Closing this in favor of https://github.com/openjournals/joss-reviews/issues/3132

**Comment by strengejacke** [comment]
@IndrajeetPatil can you please re-create the figure one for the paper? I always get these errors:

```r
> result1 <- plot(check_model(model))
Error in xy.coords(x, y, xlabel, ylabel, log) : 
  'x' is a list, but does not have components 'x' and 'y'
> 
> ggplot2::ggsave("figure1.png", result1, height = 10, width = 8)
Error in grid.draw(plot) : object 'result1' not found
```

@DominiqueMakowski what shall we do with your workflow figure? Include it in the paper / readme or not?

**Comment by IndrajeetPatil** [comment]
@strengejacke Strange, I get the same error. I actually didn’t generate Figure 1, only Figure 2. Not sure why we are getting this error. Maybe deserves its own issue?

**Comment by IndrajeetPatil** [comment]
I would suggest including the workflow figure in Readme, not sure about including it in the paper though.

**Comment by DominiqueMakowski** [comment]
I'd say put it in the paper too it's a summary figure that plays the role of a visual abstract

**Comment by IndrajeetPatil** [comment]
Should we make it Figure 3 as a visual summary of what we discuss before in the paper, or Figure 1 as a visual intro/summary before we discuss the specific functionality?

**Comment by DominiqueMakowski** [comment]
I'd say fig 1 just below the Features main section  with a legend like "Typical workflow using the performance R package"

**Comment by strengejacke** [comment]
We would need to rescale the font sizes. the bullet points are too small. can you make that figure more compact?

**Comment by DominiqueMakowski** [comment]
Lemme try

> Shouldn't test be last? by @mattansb 

Yes but I'm not sure to graphically make it so

**Comment by mattansb** [comment]
Like this?

[figures.pptx](https://github.com/easystats/performance/files/6241090/figures.pptx)

**Comment by DominiqueMakowski** [comment]
ok let me try to center it more

**Comment by DominiqueMakowski** [comment]
what do you think https://github.com/easystats/performance/blob/master/paper/figure_workflow.png

**Comment by mattansb** [comment]
Looks good!

**Comment by DominiqueMakowski** [comment]
@strengejacke you might want to point out that there's a typo on the issue title of the JOSS review (there's a "1" wrongly inserted).

Also, I've noticed that papers starting with the name of the package that has a lower case smetimes get mis-cited because the first letter is capitalized by default (and because people doesn't use legit bibtex). I wonder if we should change the title from:

- `performance: An R Package for Assessment, Comparison and Testing of Statistical Models` (current)

to 

- `The 'performance' R Package for Assessment, Comparison and Testing of Statistical Models` 

or (my favourite, but breaks the most common JOSS pattern even though many other papers don't follow it)

- `Assessment, Comparison and Testing of Statistical Models Using the 'performance' R Package`
