### ISSUE TITLE
model_performance.stanreg `common` definition

### ISSUE THREAD

**Issue by vincentarelbundock** [easystats/performance#231]
The documentation states that:

`Can be "all", "common" or a character vector of metrics to be computed (some of c("LOOIC", "WAIC", "R2", "R2_adj", "RMSE", "SIGMA", "LOGLOSS", "SCORE")). "common" will compute LOOIC, WAIC, R2 and RMSE.`

However, in this line of code, we see that `common` also includes `R2_adj`:

https://github.com/easystats/performance/blob/master/R/model_performance.bayesian.R#L67

Given the issue raised here: 

https://github.com/vincentarelbundock/modelsummary/issues/224

my current view is that `common` should exclude `R2_adj`. At least, the docs should be harmonized with the docs.

That said, I defer to your expertise on the topic, as I don't have much experience with these models.

**Comment by strengejacke** [comment]
And I don't have much experience with the loo-adjusted R2 ;-) But I'd say I'll remove "R2_adjusted" from the common-list.

**Comment by vincentarelbundock** [comment]
Thanks!
