### ISSUE TITLE
Residuals og GLM can't follow a normal distribution

### ISSUE THREAD

**Issue by raffaem** [easystats/performance#232]
`performance` id displaying the residual plot of logistic regression asking me to check that the dots lie on the line.

But in a logistic regression the residuals can't follow a normal distribution.

See [here](https://stats.stackexchange.com/questions/515281/how-can-i-cure-non-normality-of-residuals-in-logistic-regression)

**Comment by strengejacke** [comment]
I revised the docs (see https://easystats.github.io/performance/reference/check_model.html). According to your issue, see [following comment](https://stats.stackexchange.com/questions/515281/how-can-i-cure-non-normality-of-residuals-in-logistic-regression#comment950362_515281) and [my answer](https://stats.stackexchange.com/questions/515281/how-can-i-cure-non-normality-of-residuals-in-logistic-regression#comment950397_515281). These aren't the same residuals as for linear regression, thus the plots are "valid".
