### ISSUE TITLE
check_outliers and cooks.distance not matching up.

### ISSUE THREAD

**Issue by acircleda** [easystats/performance#239]
The maximum Cook's d are reported by `check_outliers` and the maximum Cook's d as reported by `max(cooks.distance(model))` do not align. The plot indicates a max of 1. The `cooks.distance` has a max of .214.

```
library(performance)
model <- lm(mpg ~ wt * cyl + gear, data = mtcars)
max(cooks.distance(model))
```
[1] 0.2148967

```
plot(check_outliers(model))
```
![image](https://user-images.githubusercontent.com/51770624/112334032-7e2da800-8c91-11eb-82f4-648c7d53656a.png)

**Comment by strengejacke** [comment]
@DominiqueMakowski What would you say should be the default? Re-scaling on/off? And regarding the two plot types (see https://github.com/easystats/performance/issues/237#issuecomment-805894652), what should be the default plot? The "new" one?

**Comment by DominiqueMakowski** [comment]
I'm not sure, it all depends whether the observations on Cooks' distance have an absolute or relative interpretation. If Absolute, then rescaling should be off by default but if relative (i.e., mostly used to compare values of the same model between them based on their own distribution) then scaling is okay I think?
