### ISSUE TITLE
JOSS: Method details

### ISSUE THREAD

**Issue by mikldk** [easystats/performance#241]
In the JOSS paper you give this example:

```r
data(cars)
model<-lm(dist~speed,data =cars)
check_heteroscedasticity(model)
#> Warning: Heteroscedasticity (non-constant error variance) detected (p = 0.031).
```
What statistical test is used? Is it the Breush-Pagan test? I think you need to give details, potentially in the output or at least in the documentation of the function. The above only shows `check_heteroscedasticity()` but you need to verify this for all such functions. 

I see that you have one implementation (`check_heteroscedasticity.default()`). Is it correct that this will give the correct results for all model types? Also e.g. Poisson regression? Or is it only `lm` models?

Ping openjournals/joss-reviews#3132

**Comment by mikldk** [comment]
Are you sure the test is valid for all the possible models for which your code provides a hypothesis test?

**Comment by strengejacke** [comment]
I specified the valid input. It is not limited to lm per se, but to Gaussian models, which is checked now. Some packages, like speedlm, should also work, despite probably not being of class "lm".

**Comment by mikldk** [comment]
Note that a linear model is not necessarily Gaussian (at least theoretically), but I'm not sure how you check it and how it impacts the test. Thanks for including the details 👍.
