### ISSUE TITLE
system is computationally singular: reciprocal condition number

### ISSUE THREAD

**Issue by asheetal** [easystats/performance#252]
```
mh.flag <- check_outliers(U3, method = "mahalanobis", threshold = list("mahalanobis" = mh_thres))
```
The code above raises the singularity error for the data I have. The base mahalanobis command allows for a parameter tol=1e-50 to pass down to use a different tolerance. 
```
mh <- mahalanobis(U3, colMeans(U3), cov(U3), tol=1e-50)
```

How can I get that same effect in check_outliers function?

**Comment by DominiqueMakowski** [comment]
I've allowed for optional arguments to be passed down, so you could be able to do `check_outliers(U3, method = "mahalanobis", threshold = list("mahalanobis" = mh_thres), tol = 1e-50)` now. Let me know if that works

**Comment by asheetal** [comment]
AMAZING!!!!! Thanks a tonne
