### ISSUE TITLE
Don't test assumptions that are not required

### ISSUE THREAD

**Issue by mattansb** [easystats/performance#260]
By model type.

Here are some _examples_ that should not work. (@bwiernik Can you double check me?)

``` r
m <- glm(am ~ mpg, mtcars,
         family = binomial())

performance::check_normality(m)
#> OK: residuals appear as normally distributed (p = 0.059).


m <- glm(gear ~ mpg, mtcars,
         family = poisson())

performance::check_normality(m)
#> Warning: Non-normality of residuals detected (p = 0.001).

performance::check_heteroscedasticity(m) # fails properly
#> Error in check_heteroscedasticity.default(m): This Breusch-Pagan Test currently only works Gaussian models.
```

<sup>Created on 2021-04-08 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by bwiernik** [comment]
Yeah, this is a good point. 

`performance::check_normality` should return a message indicating that no normality assumption is needed when family isn't normal. 

For heteroscedasticity, we could direct the user toward more appropriate checks, such as overdispersion.

It would be good to make a list of families each check is relevant for. 

I don't know that family-mismatch problems like this necessarily warrant errors--messages are probably more appropriate. Similarly, are warnings really needed when the assumption is violated? That might produce weirdness if someone has set warnings = error. Perhaps messages would again be better?

**Comment by strengejacke** [comment]
> when family isn't normal.

Does this include/exclude inverse-Gaussian and similar? And what about istrumental/2SLS, or truncated/censored?

**Comment by bwiernik** [comment]
Need to think through the various models/families that we support. Not sure off hand about inverse-Gaussian. IV/2SLS doesn't have a normality assumption I don't think. Tobit models have a normality assumption on the latent variable, so a different test is needed.

**Comment by strengejacke** [comment]
We could have a vignette that simply lists the available check-functions depending on model type, like:

- tests for linear regresion: `check_...`, ...
- tests for logistic regresion: `binned_residuals()`, ...

Anyone willing to do this? 😄

**Comment by IndrajeetPatil** [comment]
I think this is a good idea. I will make an entry for this [here](https://github.com/easystats/easystats/issues/112) and will work on it as I find time.
