### ISSUE TITLE
Overdispersion for binomial models

### ISSUE THREAD

**Issue by mattansb** [easystats/performance#262]
[Only applicable with a response that isn't Bernoulli (0s and 1s) (must instead be either `cbind(pos, neg)` or a fraction response with weights).](https://stats.stackexchange.com/questions/206007/can-there-be-overdispersion-in-a-logistic-regression-model-where-each-observatio)

Should be (from [here](https://bbolker.github.io/mixedmodels-misc/glmmFAQ.html#testing-for-overdispersioncomputing-overdispersion-factor)):

``` r
overdisp_fun <- function(model) {
  rdf <- df.residual(model)
  rp <- residuals(model, type = "pearson")
  Pearson.chisq <- sum(rp ^ 2)
  prat <- Pearson.chisq / rdf
  
  data.frame(
    ratio = prat,
    chisq = Pearson.chisq,
    df = rdf,
    p = pchisq(Pearson.chisq, df = rdf, lower.tail = FALSE)
  )
}

m <- glm(am ~ mpg + factor(cyl), data = mtcars,
         family = binomial())

overdisp_fun(m)
#>      ratio    chisq df         p
#> 1 1.036745 29.02886 28 0.4110653
```

<sup>Created on 2021-04-09 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by strengejacke** [comment]
Isn't your example exactly the case that isn't valid here?

**Comment by mattansb** [comment]
Hehe oops...

Here are useable examples:

``` r
library(dplyr, include.only = c("%>%" , "group_by", "summarise", "n"))
#> Warning: package 'dplyr' was built under R version 4.0.5

mtcars2 <- mtcars %>% 
  group_by(cyl) %>% 
  summarise(
    p = mean(am),
    w = n(),
    success = sum(am == 1),
    fail = sum(am == 0)
  )

m1 <- glm(p ~ factor(cyl), mtcars2,
          weights = w,
          family = binomial())

m2 <- glm(cbind(success, fail) ~ factor(cyl), mtcars2,
          family = binomial())

m3 <- glm(cbind(success, w - success) ~ factor(cyl), mtcars2,
          family = binomial())
```

<sup>Created on 2021-04-20 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>
