### ISSUE TITLE
"text equivalent" to `check_model()`

### ISSUE THREAD

**Issue by strengejacke** [easystats/performance#266]
> I really like the function check_model, which gives all appropriate visual checks for the model class. It would be very useful with a non-visual counterpart which runs all appropriate test and provides p-values etc for them. It seems you don't have that implemented. It shouldn't be too hard based on the "manual" tests already implemented, or are there problems with this approach?

(https://github.com/openjournals/joss-reviews/issues/3139#issuecomment-819005992)

**Comment by bwiernik** [comment]
Personally, I think most of the tests and their p values are pretty much worthless. I'd strongly recommend most folks stick with the graphical measures, and I'm kind of okay with getting statistical tests requiring more hoops.

**Comment by IndrajeetPatil** [comment]
If we _were_ to support something like this, wouldn't it live in `{report}`?

**Comment by bwiernik** [comment]
There's a reasonable argument that print() should show the text we already show for the individual test functions along with the plots

**Comment by strengejacke** [comment]
> Personally, I think most of the tests and their p values are pretty much worthless. I'd strongly recommend most folks stick with the graphical measures, and I'm kind of okay with getting statistical tests requiring more hoops.
