### ISSUE TITLE
check_model error

### ISSUE THREAD

**Issue by delucalab** [easystats/performance#268]
Hope you are staying safe! I am new to all this so forgive me if this is a naive question. I am using the check_model function on a model I built with lmer in the lme4 package. Some of my predictors are dummy coded variables (0, 1) which I set as factors. I then received the following error:

_**Error in 1:label.n : NA/NaN argument**_

When I don't set the predictors as factors I no longer receive the error. However, in another data set with a mix of dummy coded variables (0,1,2) and (0,1) I don't get this error if they are all set as factors. 

Therefore, I am a bit confused about the error and wanted to see if you had any insight?

Warm Regards,
Alex

**Comment by strengejacke** [comment]
Do you have a small reproducible example?

**Comment by delucalab** [comment]
Attached are the datasets and associated code to reproduce the errors/non-errors. Let me know if you need anything else. Thanks for your help!
[Dataset 1.csv](https://github.com/easystats/performance/files/6318715/Dataset.1.csv)
[Dataset 2.csv](https://github.com/easystats/performance/files/6318716/Dataset.2.csv)
[Reproducible Example.txt](https://github.com/easystats/performance/files/6318717/Reproducible.Example.txt)

**Comment by bwiernik** [comment]
(This is going to be in the new cooks distance plot, label.n controls how many points get text annotations.)

**Comment by delucalab** [comment]
I looked further and I noticed that I only get the error (Error in 1:label.n : NA/NaN argument) if the input model does not have any continuous predictors and I make the dummy variable factors. However, if I do not use the as.factor command and solely have discrete predictors or I add a continuous predictor while still using the as.factor command, I know longer get the error.

**Comment by bwiernik** [comment]
Can you please give a small reproducible example we can run?

**Comment by delucalab** [comment]
I'm attaching a dataset file (Dataset 2.csv) and the code (Reproducible Example.txt) to reproduce the situations when errors arise and don't. The text file should indicate which set of commands should produce the error and which won't (including what is different between the data). Let me know if you need anything else or if I'm not providing the right format or something (this is all new to me).
[Dataset 2.csv](https://github.com/easystats/performance/files/6319183/Dataset.2.csv)
[Reproducible Example.txt](https://github.com/easystats/performance/files/6319184/Reproducible.Example.txt)

**Comment by delucalab** [comment]
I'm attaching a dataset file (Dataset 2.csv) and the code (Reproducible Example.txt) to reproduce the situations when errors arise and don't. The text file should indicate which set of commands should produce the error and which won't (including what is different between the data). Let me know if you need anything else or if I'm not providing the right format or something (this is all new to me). I'm using RStudio Version 1.2.5033 in case that is helpful.
[Dataset 2.csv](https://github.com/easystats/performance/files/6319236/Dataset.2.csv)
[Reproducible Example.txt](https://github.com/easystats/performance/files/6319237/Reproducible.Example.txt)

**Comment by bwiernik** [comment]
@strengejacke Here is a minimal reprex that produces the cause of the problem:

```r
m <- lm(mpg ~ factor(cyl), data = mtcars)
x <- performance::check_outliers(m)
attributes(x)$threshold$cook
```

The issue is here: https://github.com/easystats/performance/blob/c53ef4fb76831360d9df5eb1076ce558b92f7e0c/R/check_outliers.R#L212

In the calculation of the thresholds, the data it uses removes factors and characters rather than using their dummy codes or contrasts. This is going to render the Cook's distance threshold NaN if there are no continuous variables, but it is also going to be invalid if there are any factor predictors. The more appropriate thing would be to call `model.matrix(x)` there instead of `get_predictors(x)`.
