### ISSUE TITLE
Error of check_outliers when lm(data$y ~ data$x)

### ISSUE THREAD

**Issue by GWeindel** [easystats/performance#270]
On the latest dev branch I get an error when creating the model with ```model <- lm(data$y ~ data$x)```

Calling :
```check_outliers(model)```
Yields : 
```Error in stats::qf(0.5, ncol(x), nrow(x) - ncol(x)): Argument non numérique pour une fonction mathématique
Traceback:

1. check_model(model)
2. check_model.default(model)
3. suppressWarnings(.check_assumptions_linear(x, minfo))
4. withCallingHandlers(expr, warning = function(w) if (inherits(w, 
 .     classes)) tryInvokeRestart("muffleWarning"))
5. .check_assumptions_linear(x, minfo)
6. check_outliers(model, method = "cook")
7. check_outliers.default(model, method = "cook")
8. .check_outliers_thresholds(data)
9. suppressWarnings(.check_outliers_thresholds_nowarn(x))
10. withCallingHandlers(expr, warning = function(w) if (inherits(w, 
  .     classes)) tryInvokeRestart("muffleWarning"))
11. .check_outliers_thresholds_nowarn(x)
12. stats::qf(0.5, ncol(x), nrow(x) - ncol(x))
```
Fixed when model is created with ```model <- lm(y ~ x, data=data)```
A small bug but might be worse to fix in order to avoid users searching for the source.

Thanks for your package :)

**Comment by bwiernik** [comment]
The issue is with `insight::get_predictors()`.

```r
m <- lm(mtcars$mpg ~ mtcars$hp)
insight::get_predictors(m)

`find_predictors(m)
# "mtcars" "hp"
#
# should be:
# "mtcars$hp"
```

`find_predictors(m)` is not handling the case of subsetted vectors `mtcars$hp` correctly. Not that assigned object names in the global environment work fine:

```r
a <- mtcars$mpg
b <- mtcars$hp
m2 <- lm(a ~ b)
insight::get_predictors(m)
```

**Comment by strengejacke** [comment]
> # should be:
> # "mtcars$hp"

I wouldn't say "should be", the behaviour is actually intended, similar to:

``` r
m <- lm(mtcars$mpg ~ mtcars$hp)
all.vars(formula(m))
#> [1] "mtcars" "mpg"    "hp"
```

<sup>Created on 2021-04-17 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

I see (at least) two options: 1) try to "educate" users towards good habits, and warn to use the "data" argument; or 2) try to evaluate the model formula and try to find the name of the data set. That's possibly something to be done in `insight::get_data()`.

**Comment by strengejacke** [comment]
I just saw that `get_data()` actually works, it's just that the column names are `mtcars$...` instead just the variable name.

**Comment by bwiernik** [comment]
I guess I meant "for this to work extracting predictors, the return from .find_predictors() should be".

But using `$` actually seems to cause huge namespace issues. Methods like `predict()` with `newdata` or `insight::get_predicted()` won't work consistently with `$` variables. 

```r
d <- mtcars
m <- lm(d$mpg ~ d$hp)
d2 <- model.frame(m)[1:5,]

predict(m, newdata = d2)
insight::get_predicted(m)
insight::get_predicted(m, data = d2)

rm(d)
predict(m, newdata = d2)
insight::get_predicted(m)
insight::get_predicted(m, data = d2)
```

I think we should just return an error in easystats functions if a variable includes `$` and then suggest a better call:

```
Error: Using `$` in model formulas can produce unexpected results. Try this instead:
  lm(mpg ~ hp, data = d)
```

**Comment by bwiernik** [comment]
Here is a basic function to check formulas for `$` then return an error:

```r
.check_formula_for_dollar <- function(f) {
  error_message <- paste(
    "Using `$` in model formulas can produce unexpected results.",
    "Specify your model using the `data` argument instead.",
    sep = "\n  "
  )
  if (any(stringr::str_detect(f, "\\$"))) {
    fc <- try(.formula_clean(f), silent = TRUE)
    if (inherits(fc, "try-error")) {
      stop(
        error_message, call. = FALSE
      )
    } else {
      stop(
        paste(
          error_message,
          "Try:",
          paste0("  ", fc$formula, ", data = ", fc$data),
          sep = "\n  "
        ), call. = FALSE
      )
    }
  }
}

.formula_clean <- function(f) {
  fc <- as.character(f)
  LHS <- fc[2]
  RHS <- fc[3]
  d_LHS <- stringr::str_extract(
    LHS, 
    "([^$+\\-*\\/ ~^()|:]+\\$)"
  )
  d_RHS <- stringr::str_extract(
    RHS, 
    "([^$+\\-*\\/ ~^()|:]+\\$)"
  )
  if (length(unique(c(d_LHS, d_RHS))) > 1) {
    stop("Multiple data objects present in formula")
  } else {
    d <- stringr::str_match(
      na.omit(d_RHS)[1],
      "(.+)\\$"
    )[,2]
  }
  LHS_clean <- stringr::str_replace_all(
    LHS, 
    "([^$+\\-*\\/ ~^()|:]+\\$)", 
    ""
  )
  RHS_clean <- stringr::str_replace_all(
    RHS, 
    "([^$+\\-*\\/ ~^()|:]+\\$)", 
    ""
  )
  return(list(data = d, formula = paste(LHS_clean, fc[1], RHS_clean)))
}
```

It currently uses stringr because I can never remember base R's regex functions without looking them up ;)

**Comment by strengejacke** [comment]
Ok, I had a simpler version, but maybe less stable? https://github.com/easystats/insight/commit/23ef65438248325d936ae1f76c6ba54f5f21181a

I'm no expert in regexp, so I can't say what this here does `"([^$+\\-*\\/ ~^()|:]+\\$)"`.

**Comment by strengejacke** [comment]
``` r
library(performance)
m <- lm(mtcars$mpg ~ mtcars$hp)
check_model(m)
#> Loading required namespace: qqplotr
```

![](https://i.imgur.com/AdTO6Jl.png)

``` r
m <- lm(mtcars$mpg ~ mtcars$hp * mtcars$cyl + mtcars$drat)
check_model(m)
```

![](https://i.imgur.com/zWXSuWb.png)

<sup>Created on 2021-04-17 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by bwiernik** [comment]
I commented on that commit. I don't think cleansing the names in `get_data()` is a good idea. It still won't produce expected behavior of the model with many functions because the predictors aren't pulled from the model frame, they are pulled from the object in the enclosing environment.

That regex is will find all of the bits in a formula that are in the position of data here: `data$`.

1. The outer parentheses `()` are the capture group used to make the `data = ...` part of the error message.
2. `[^$+\\-*\\/ ~^()|:]+` : This part finds one or more characters that are not `$`, a space, or one of the R formula syntax characters `+-*/~^()|:`
3. `\\$` : This part specifies that the above stuff must come directly before a `$`

I can swap out the functions for base R equivalents if you could commit this into insight where it would belong.

**Comment by strengejacke** [comment]
The R base equivalent would be `gsub("([^$+\\-*\\/ ~^()|:]+\\$)", "\\2", "mpg$test", perl = TRUE)`. I'll add this to `find_formula()`.

**Comment by bwiernik** [comment]
I can put it into find_formula if you like

**Comment by strengejacke** [comment]
It's a bit trickier, the regex I used captures the right part of the $, we need the left part

**Comment by strengejacke** [comment]
This seems to work:

``` r
m <- lm(mtcars$mpg ~ mtcars$hp * mtcars$cyl + poly(mtcars$drat, 2) / mtcars$disp)
f <- insight::find_formula(m)$conditional
fc <- as.character(f)
parts <- trimws(unlist(strsplit(split = "[\\s\\*\\+\\:\\-\\|\\/\\(\\)\\^,]", x = fc[3], perl = TRUE)))

gsub("(.*)\\$(.*)", "\\1", parts[grepl("(.*)\\$(.*)", parts)])
#> [1] "mtcars" "mtcars" "mtcars" "mtcars"
```

<sup>Created on 2021-04-17 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by strengejacke** [comment]
``` r
library(insight)
d <- mtcars
m <- lm(mtcars$mpg ~ mtcars$hp * mtcars$cyl + poly(mtcars$drat, 2) / mtcars$disp)
find_formula(m)
#> Warning: Using `$` in model formulas can produce unexpected results.
#>   Specify your model using the `data` argument instead.
#>   Try: mpg ~ hp * cyl + poly(drat, 2)/disp, data = mtcars
#> $conditional
#> mtcars$mpg ~ mtcars$hp * mtcars$cyl + poly(mtcars$drat, 2)/mtcars$disp
#> 
#> attr(,"class")
#> [1] "insight_formula" "list"

m <- lm(mtcars$mpg ~ d$hp * mtcars$cyl + poly(mtcars$drat, 2) / mtcars$disp)
find_formula(m)
#> Error: Multiple data objects present in formula. Specify your model using the `data` argument instead.

m <- lm(mpg ~ hp * cyl + poly(drat, 2) / disp, data = mtcars)
find_formula(m)
#> $conditional
#> mpg ~ hp * cyl + poly(drat, 2)/disp
#> 
#> attr(,"class")
#> [1] "insight_formula" "list"
```

<sup>Created on 2021-04-17 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by bwiernik** [comment]
My regex above captures the left part

**Comment by strengejacke** [comment]
yes, yes, I realized that later. That's why I strike though this comment: https://github.com/easystats/performance/issues/270#issuecomment-821877661

The new code now also captures the left part.

**Comment by bwiernik** [comment]
Your regex is too greedy. It's matching `poly(mtcars$` instead of just `mtcars`

**Comment by strengejacke** [comment]
The code I used (https://github.com/easystats/performance/issues/270#issuecomment-821879575) only returns the data name(s).

**Comment by strengejacke** [comment]
And the results (https://github.com/easystats/performance/issues/270#issuecomment-821882138) look ok?

**Comment by GWeindel** [comment]
I am so impressed by your reactivity that this example is going straight to my lecture on R as an example of the R community (even though I am usually kind of a pythonista)

**Comment by bwiernik** [comment]
@strengejacke No, that shouldn't report an error there. Your regex is capturing the poly() bit.

**Comment by bwiernik** [comment]
@strengejacke you have a few extra \\ there, but I think it's okay? Could you show the current working code--the various messages are confusing me

**Comment by strengejacke** [comment]
This is the source code:

```r
.find_formula_return <- function(f) {
  if (is.null(f)) {
    return(NULL)
  }


  .check_formula_for_dollar(f)
  class(f) <- c("insight_formula", class(f))
  f
}




# formulas with $, like "lm(mtcars$mpg ~ mtcars$hp), may cause problems
# in various functions throughout the easystats packages. We warn the user
# here...


.check_formula_for_dollar <- function(f) {
  error_message <- paste(
    "Using `$` in model formulas can produce unexpected results.",
    "Specify your model using the `data` argument instead.",
    sep = "\n  "
  )


  if (any(grepl("\\$", .safe_deparse(f[[1]])))) {
    fc <- try(.formula_clean(f[[1]]), silent = TRUE)
    if (inherits(fc, "try-error")) {
      stop(attributes(fc)$condition$message, call. = FALSE)
    } else {
      warning(
        paste(
          error_message,
          paste0("Try: ", fc$formula, ", data = ", fc$data),
          sep = "\n  "
        ), call. = FALSE
      )
    }
  }
}




.formula_clean <- function(f) {
  fc <- as.character(f)
  LHS <- fc[2]
  RHS <- fc[3]


  parts <- trimws(unlist(strsplit(split = "[\\s\\*\\+\\:\\-\\|\\/\\(\\)\\^,]", x = LHS, perl = TRUE)))
  d_LHS <- unique(gsub("(.*)\\$(.*)", "\\1", parts[grepl("(.*)\\$(.*)", parts)]))


  parts <- trimws(unlist(strsplit(split = "[\\s\\*\\+\\:\\-\\|\\/\\(\\)\\^,]", x = RHS, perl = TRUE)))
  d_RHS <- unique(gsub("(.*)\\$(.*)", "\\1", parts[grepl("(.*)\\$(.*)", parts)]))


  if (.n_unique(c(d_LHS, d_RHS)) > 1) {
    stop("Multiple data objects present in formula. Specify your model using the `data` argument instead.", call. = FALSE)
  } else {
    d <- unique(d_RHS)
  }
  LHS_clean <- gsub(paste0(d_LHS, "\\$"), "", LHS)
  RHS_clean <- gsub(paste0(d_RHS, "\\$"), "", RHS)


  list(data = d, formula = paste(LHS_clean, fc[1], RHS_clean))
}
```

I think in this pattern `"[\\s\\*\\+\\:\\-\\|\\/\\(\\)\\^,]"` some escapes can be removed, I guess it's `:`, `-`, `/`?

Current behaviour is:

```r
library(insight)
d <- mtcars
m <- lm(mtcars$mpg ~ mtcars$hp * mtcars$cyl + poly(mtcars$drat, 2) / mtcars$disp)
find_formula(m)
#> Warning: Using `$` in model formulas can produce unexpected results.
#>   Specify your model using the `data` argument instead.
#>   Try: mpg ~ hp * cyl + poly(drat, 2)/disp, data = mtcars
#> $conditional
#> mtcars$mpg ~ mtcars$hp * mtcars$cyl + poly(mtcars$drat, 2)/mtcars$disp
#> 
#> attr(,"class")
#> [1] "insight_formula" "list"

m <- lm(mtcars$mpg ~ d$hp * mtcars$cyl + poly(mtcars$drat, 2) / mtcars$disp)
find_formula(m)
#> Error: Multiple data objects present in formula. Specify your model using the `data` argument instead.

m <- lm(mpg ~ hp * cyl + poly(drat, 2) / disp, data = mtcars)
find_formula(m)
#> $conditional
#> mpg ~ hp * cyl + poly(drat, 2)/disp
#> 
#> attr(,"class")
#> [1] "insight_formula" "list"
```

**Comment by bwiernik** [comment]
Okay, I see what you are doing there with the regex. The pattern can be shortened to: `[\\s*+:()|^,\\-\\/]`. That is only `s`, `-`, and `/` need to be escaped inside of `[]`.
