### ISSUE TITLE
warnings about "invalid" model formula?

### ISSUE THREAD

**Issue by strengejacke** [easystats/performance#283]
@DominiqueMakowski @bwiernik @mattansb @IndrajeetPatil 

You may remember the issue about `check_model()` and its opaque warnings. I started to add more `verbose` arguments to _insight_ functions, so we can better trigger warnings/messages for the various functions. However, sometimes, some functions are called multiple times (in particular `find_formula()`, which now can warn about "invalid" formula specification, see example #282). I _think_ these warnings do not always make sense, but are useful to users only in particular contexts - which mostly happens for _performance_ functions (but not only here).

I think problems can occur when model formulas are ("mis-")specified in two ways:

``` r
d <- data.frame(x = rnorm(100), y = rnorm(100))
mod1<- lm(y ~ poly(x, 2, raw=T), data = d)
mod2<- lm(y ~ d$x, data = d)

insight::formula_ok(mod1)
#> Warning: Looks like you are using 'poly()' with 'raw = T'. This results in unexpected
#>   behaviour, because 'all.vars()' considers 'T' as variable. Please use 'raw =
#>   TRUE'.
#> [1] FALSE
insight::formula_ok(mod2)
#> Warning: Using `$` in model formulas can produce unexpected results. Specify your model
#>   using the `data` argument instead.
#>   Try: y ~ x, data = d
#> [1] FALSE
```

<sup>Created on 2021-04-23 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

Thus, I thought we set `verbose = FALSE` in every possible place (i.e. when the chain/level of function calls is so deep, that the user doesn't knwo why this warning is printed) , so when functions like `test_wald()` are called, we don't have 20+ warnings, all confusing to the user, but rather put this line

```r
insight::formula_ok(model)
```

at the beginning of all functions where applicable, so we get these warnings only once. What do you think? If it's a good idea, where do we need to add this code line?

**Comment by bwiernik** [comment]
That sounds like a good solution.

**Comment by DominiqueMakowski** [comment]
I think it's a good idea, and the warnings are pretty cool and helpful for new users!

**Comment by strengejacke** [comment]
I think most occurrences are covered, if we still find more redundant warnings, we can fix those then.
