### ISSUE TITLE
Pseudo R2 for pscl::zeroinfl() and pscl::hurdle() 

### ISSUE THREAD

**Issue by strengejacke** [easystats/performance#29]
Moved from https://github.com/strengejacke/sjstats/issues/49

@tbx200 Due to re-organization of packages, all "model-performance" related stuff goes now into this package...

**Comment by strengejacke** [comment]
This paper looks promising:
https://www.tandfonline.com/doi/full/10.1080/00949655.2016.1186166

The formula in equation 5 looks easy, but still I can't read and translate it into R code...

**Comment by DominiqueMakowski** [comment]
I am not good enough with equations 😕 @pdwaggoner @mattansb any mathematical background to help out?

**Comment by mattansb** [comment]
No, sorry...

**Comment by pdwaggoner** [comment]
I could give it a look - I am weird and like equations. 

But for some reason my school's firewall is preventing me from downloading the paper. Can you share a PDF so I can see it? Or a screen shot of the equation with term definitions? Can't promise anything but I'll give it a try!

**Comment by strengejacke** [comment]
![image](https://user-images.githubusercontent.com/26301769/57138808-eb8d7280-6db3-11e9-8a78-6c11fd526348.png)

![image](https://user-images.githubusercontent.com/26301769/57138841-fcd67f00-6db3-11e9-8b56-79c1a61a87cd.png)

`l0` the the likelihood of the null-model, `l1` of the full model.

**Comment by pdwaggoner** [comment]
Alright - here is my "almost-there" attempt. Note that I couldn't figure out what `p` equaled... If we can figure that out, I think this may be right, but I am not sure... As a back up, I just replicated Jackman's ML pseudo $R^2$ for glm's. Not sure if this will get us there. Again, I know this isn't quite it, but I think its close. Let me know:

```{R}
P_R2 <- function(model_obj,...){
  ll <- logLik(model_obj) # LL from fit model
  model_obj_Null <- update(model_obj, ~ 1) # intercept-only restricted (no covariates)
  llNull <- logLik(model_obj_Null) # LL from restricted model 
  n <- dim(model_obj$model)[1] # number of rows/obs 
  # k <- length(model_obj$coefficients) # k predictors
  # p <- ??? # still not sure here...
  # R2_ZIP <- 1 - (((ll - llNull) + p + k + 0.5) / (ll - llNull))
  R2_ML <- 1 - exp((2 * (llNull - ll)) / n) # ML pseudo R2 as a back up...
}
```

**Comment by strengejacke** [comment]
I'm not sure we 100% got it here. We have three different log-likelihoods in the formula. One ll corresponds  to the "full" zip-model, one to null-model and one to the poisson or logistic process only.

**Comment by pdwaggoner** [comment]
Yeah I was trying to figure out that second LL. That makes sense, but that implies that the the user would need to pass two model objects to the function? Or are you thinking to calculate the poisson/NB/logistic internally in the function?

**Comment by strengejacke** [comment]
I think this is possible. I have looked at the source code of `pscl::zeroinf()`. Not gone through it in detail...

**Comment by strengejacke** [comment]
Short update: since the _pscl_ packages allows returning Pearson-residuals, we can calculate R2 simply by using 1 - (SSfixed^2 / (SStotal^2), like described here: https://en.wikipedia.org/wiki/Coefficient_of_determination#Definitions

What do you say? As far as I understand, we just need fitted (`fitted()`) values and Pearson residuals (`residuals(type = "pearson")`) for the R2...

**Comment by strengejacke** [comment]
Just compared the formula from Zuur et al 2012 (https://github.com/glmmTMB/glmmTMB/issues/205#issuecomment-362302117) to the output from `pscl::residuals(type = "pearson")`, and both are identical.

So I think we have a useful R2 measure and can close this issue now...

**Comment by pdwaggoner** [comment]
Sounds great! So glad this worked.
