### ISSUE TITLE
"check_normality()' does not support models of class 'lmerModLmerTest'. Error in attr(p.val, "object_name") <- .safe_deparse(substitute(x)) :    attempt to set an attribute on NULL"

### ISSUE THREAD

**Issue by BeffaraBee** [easystats/performance#290]
Dear all, 

I am encountering some problems using `check_normality` with `lme4`: it only works for random effects, not for fixed effects. 

Here's my code:

```r
library(lme4)
library(lmerTest)
library(DHARMa)
library(modelbased)
library(effectsize)
library(writexl)
library(ggplot2)
library(car)
library(sjPlot)
library(performance)

CorrectBehavior$SL=as.factor(CorrectBehavior$SL)
CorrectBehavior$DISP=as.factor(CorrectBehavior$DISP)
CorrectBehavior$subj=as.factor(CorrectBehavior$subj)
fullmod=lmer(RT~DISP*SL+(1|subj),CorrectBehavior)
result <- check_normality(fullmod, effects = "fixed")`
```

I attach the relevant data :-).
[BEH.xlsx](https://github.com/easystats/performance/files/6440760/BEH.xlsx)

Any help would be highly appreciated :-) :-). 

THX!

**Comment by IndrajeetPatil** [comment]
Before we look at your data, can you please refresh the R session, run the following code, and report the output here?

```r
library(lme4)
library(performance)
library(see)

mod <- lmer(Reaction ~ Days + (Days | Subject), sleepstudy)

plot(check_normality(mod))
```

If this doesn't work, then the problem has nothing to do with your data.

**Comment by IndrajeetPatil** [comment]
Also, which lmer are you using here: `lme4::lmer()` or `lmerTest::lmer()`? 

> fullmod=lmer(RT~DISP*SL+(1|subj),CorrectBehavior)

The function works for both, but maybe it will be helpful to know to diganoze the source of this issue.

**Comment by BeffaraBee** [comment]
Hi, 

Thanks for your prompt answer. I ran the code you provided: it works well.

I use lme4::lmer() and lmerTest::lmer(), but both do not work. 

I add that I have no NA-values in my dataset.

Thanks,

**Comment by BeffaraBee** [comment]
Hi, 

Any idea of where the problem can come from? This is still not working here :-(.

Thx, 
Bertrand

**Comment by IndrajeetPatil** [comment]
Did you update the `performance` package to GitHub version?

```r
remotes::install_github("easystats/performance")
```

**Comment by strengejacke** [comment]
I checked your model, and it worked fine. If you still encounter any problems, please provide a reproducible example with your output.

**Comment by BeffaraBee** [comment]
Hi, 

Still the same problem as the beginning: same code, same data. 

Here is the output:
"> plot(check_normality(fullmod))
'check_normality()' does not support models of class 'lmerModLmerTest'.
Error in attr(p.val, "object_name") <- .safe_deparse(substitute(x)) : 
  attempt to set an attribute on NULL"

**Comment by BeffaraBee** [comment]
> ```r
> remotes::install_github("easystats/performance")
> ```

Works! :-) :-)

Thx!
