### ISSUE TITLE
check_model method conflict between lme4 and car

### ISSUE THREAD

**Issue by mjrolland** [easystats/performance#294]
Hi,

There seems to be an issue linked with methods having the same name in `lme4` and `car`  making `check_model` not work when both packages are loaded.

This seems to be an issue that will be solved in the future, but I am not sure currently how to work around it to get `check_model` to work. 

I am not too comfortable in manipulating S3 objects...

```r
library(performance)
library(lme4)
m <- lmer(Reaction ~ Days + (Days | Subject), sleepstudy)
check_model(m) # works

library(car)
check_model(m) # does not work
```

The first iteration of `check_model` works fine. Then loading the car package sends this message:

```r
Loading required package: carData
Registered S3 methods overwritten by 'car':
  method                          from
  influence.merMod                lme4
  cooks.distance.influence.merMod lme4
  dfbeta.influence.merMod         lme4
  dfbetas.influence.merMod        lme4
```

And the second iteration of `check_model` does not work with this error:

```
Error in data.frame(Hat = infl$hat, Cooks_Distance = stats::cooks.distance(model,  : 
  arguments imply differing number of rows: 0, 180
```

Do you know how I can solve this?

Thanks!!

Matthieu

**Comment by DominiqueMakowski** [comment]
@mjrolland you can call directly `performance::check_model()` to explicitly specify which function you want to use

**Comment by mjrolland** [comment]
@bwiernik I think `car` is a dependance of a package I have to use... I am not loading it explicitly, but I finally found out it came from there

@DominiqueMakowski  unfortunately the issue is not coming from the `check_model` function but (I am guessing because not very good with all this....) from one of the methods used by the `check_model` function

**Comment by mjrolland** [comment]
I am guessing the easy fix I need is the S3 method equivalent to :

```r
function_name <- package::function_name
```

**Comment by mjrolland** [comment]
@bwiernik  the reprex closest to my actual analysis which corresponds to what you had suggested but produces all the same errors:

```r
library(lme4)
library(performance)
m <- lmer(Reaction ~ Days + (Days | Subject), sleepstudy)
check_model(m) # works

car::Anova(m) 

check_model(m) # does not work
```

**Comment by strengejacke** [comment]
We need the `hat` value from the influential observations, which is no longer returns after `car` namespace is loaded.

``` r
library(lme4)
#> Loading required package: Matrix
library(performance)
m <- lmer(Reaction ~ Days + (Days | Subject), sleepstudy)
infl1 <- stats::influence(m, do.coef = FALSE)
cd1 <- stats::cooks.distance(m, infl1)

car::Anova(m) 
#> Registered S3 methods overwritten by 'car':
#>   method                          from
#>   influence.merMod                lme4
#>   cooks.distance.influence.merMod lme4
#>   dfbeta.influence.merMod         lme4
#>   dfbetas.influence.merMod        lme4
#> Analysis of Deviance Table (Type II Wald chisquare tests)
#> 
#> Response: Reaction
#>       Chisq Df Pr(>Chisq)    
#> Days 45.853  1  1.275e-11 ***
#> ---
#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
infl2 <- stats::influence(m, do.coef = FALSE)
cd2 <- stats::cooks.distance(m, infl2)

identical(infl1, infl2)
#> [1] FALSE
identical(cd1, cd2)
#> [1] TRUE

names(infl1)
#> [1] "hat"
names(infl2)
#>  [1] "fixed.effects"        "fixed.effects[-case]" "var.cov.comps"       
#>  [4] "var.cov.comps[-case]" "vcov"                 "vcov[-case]"         
#>  [7] "groups"               "deleted"              "converged"           
#> [10] "function.evals"
```

<sup>Created on 2021-05-12 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by mjrolland** [comment]
OK thanks. And so knowing this, how would it be possible for me to use `check_model` after having used `car::Anova`? Is there no way around it?

Thank you in advance for your help!

**Comment by strengejacke** [comment]
I see (at least) two solutions: 1) if `hat` not available, maybe we can calculate that manually from the car::influcence... 2) transfer this issue to the maintainer of the car-package, who probably could be responsible for not breaking code when overwriting methods.

**Comment by IndrajeetPatil** [comment]
> 2) transfer this issue to the maintainer of the car-package, who probably could be responsible for not breaking code when overwriting methods

I have talked to maintainers of both `lme4` and `car` about this before and John (Fox) has indeed decided to remove these methods from `car` once `lme4` with the needed fix (https://github.com/lme4/lme4/issues/607) is on CRAN. Then this issue would disappear on its own.

**Comment by mjrolland** [comment]
@IndrajeetPatil ok thanks, do you know when this will take effect?

**Comment by IndrajeetPatil** [comment]
Not sure. But hopefully soon since the last release of `lme4` was in December 2020.

**Comment by mjrolland** [comment]
OK thank you very much.  So I'll just be patient then if there is no other solution :)

**Comment by mjrolland** [comment]
To conclude this and until the issue is properly fixed in `car` (which seems that it will be the case at some point) to do what I want I just needed to load `car` **before** `lme4`... This works fine:

```r
library(car)
library(lme4)
library(performance)
m <- lmer(Reaction ~ Days + (Days | Subject), sleepstudy)
check_model(m)
```

`lme4` overwrites `car` instead of the other way...

**Comment by IndrajeetPatil** [comment]
New version of `lme4` is on CRAN now, and John said he would be submitting the new version of `car` to CRAN in the next few days.

So you want have to rely on this workaround for too long. :)
