### ISSUE TITLE
Add Cox regression as new supported model?

### ISSUE THREAD

**Issue by fedenichetti** [easystats/performance#302]
Hi there, amazing package, thank you! 

I am a medical oncologist always dealing with survival data, so I wondered if there is any chance to add coxph() and/or cph() as supported models for performance.

Thanks!
FN

**Comment by IndrajeetPatil** [comment]
Thanks for filing a feature request. There is already an issue where we are discussing adding this support.

Duplicate of https://github.com/easystats/performance/issues/267
