### ISSUE TITLE
adding data frame methods for `r2_bayes`

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/performance#303]
Not sure if this will cause any problems somewhere downstream, but can we add  a data frame method for these objects?

``` r
library(performance)
library(rstanarm)

model <- stan_glm(mpg ~ wt + cyl, data = mtcars, chains = 1, iter = 500, refresh = 0)

class(r2_bayes(model))
#> [1] "r2_bayes"
```

For example, often I want to use `standardize_names` to change names, but it doesn't work because `standardize_names` doesn't have any method for `r2_bayes` objects.

**Comment by bwiernik** [comment]
I think this should be okay?

**Comment by IndrajeetPatil** [comment]
This is already implemented 🤦 
Sorry

https://github.com/easystats/performance/blob/683614589fbde4565e3fbeba2d41919e3022d32c/R/r2_bayes.R#L334-L361
