### ISSUE TITLE
cloglog link function

### ISSUE THREAD

**Issue by jebyrnes** [easystats/performance#305]
Love this package. I was working with a beta regression with a cloglog link recently, but cannot get an R2. Here is a reproducible example. Thoughts?

```
library(performance)
library(betareg)
library(glmmTMB)

data("GasolineYield", package = "betareg")

## Table 1
gy <- glmmTMB(yield ~ batch + temp, 
              data = GasolineYield,
              family = beta_family(link = "cloglog"))

r2_nakagawa(gy)
```

This yields

```
[1] NA
Warning message:
Model link 'cloglog' is not yet supported for the beta distribution. 
```

It looks like, though, Nakagawa et al. have worked this out - see https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5636267/pdf/rsif20170213.pdf 

The distribution specific-variance is (pi^2)/6 and the observation level variance is defined in a table in the paper.

Any chance this will make it into a new version anytime soon?

**Comment by jebyrnes** [comment]
Ach - I see the issue is with insight. I've posted an issue at https://github.com/easystats/insight/issues/381 - feel free to close this if you want. (And note, while the above is reproducible, I see it's not a glmm - the real example I'm working on is, but, still have the cloglog problem)

**Comment by IndrajeetPatil** [comment]
Thanks for reporting!

Closing in favor of asystats/insight#381. The discussion can continue there.
