### ISSUE TITLE
incorrect "The models don't have the same response variable" error

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/performance#308]
The `test_performance` function [docs](https://easystats.github.io/performance/reference/test_performance.html) feature the following example:

```r
m1 <- lm(Sepal.Length ~ Petal.Width, data = iris)
m2 <- lm(Sepal.Length ~ Petal.Width + Species, data = iris)
m3 <- lm(Sepal.Length ~ Petal.Width * Species, data = iris)

test_performance(m1, m2, m3)
```

If I just change the dataset to `penguins` and use DVs and IVs from that dataset, the function fails:

``` r
library(performance)
library(palmerpenguins) 

m1 <- lm(flipper_length_mm ~ body_mass_g, data = penguins)
m2 <- lm(flipper_length_mm ~ body_mass_g + sex, data = penguins)
m3 <- lm(flipper_length_mm ~ body_mass_g * sex, data = penguins)

test_performance(m1, m2, m3)
#> Error in .test_performance_checks(objects): The models don't have the same response variable, which is a prerequisite to compare them.
```

<sup>Created on 2021-06-11 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by IndrajeetPatil** [comment]
Weirdly, if I change the categorial predictor from `sex` to `species`, it works 🤔 

``` r
library(performance)
library(palmerpenguins) 

m1 <- lm(flipper_length_mm ~ body_mass_g, data = penguins)
m2 <- lm(flipper_length_mm ~ body_mass_g + species, data = penguins)
m3 <- lm(flipper_length_mm ~ body_mass_g * species, data = penguins)

test_performance(m1, m2, m3)
#> Name | Model |     BF | Omega2 | p (Omega2) |     LR | p (LR)
#> -------------------------------------------------------------
#> m1   |    lm |        |        |            |        |       
#> m2   |    lm | > 1000 |   0.42 |     0.213  | 171.60 | < .001
#> m3   |    lm |  0.161 |   0.02 |     > .999 |   8.02 | 0.973 
#> Models were detected as nested and are compared in sequential order.
```

<sup>Created on 2021-06-11 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by strengejacke** [comment]
Missing data?

**Comment by IndrajeetPatil** [comment]
Yepp, indeed. But maybe we should anticipate this and put in some safeguards?

``` r
library(performance)
library(palmerpenguins) 

df <- tidyr::drop_na(penguins)

m1 <- lm(flipper_length_mm ~ body_mass_g, data = df)
m2 <- lm(flipper_length_mm ~ body_mass_g + sex, data = df)
m3 <- lm(flipper_length_mm ~ body_mass_g * sex, data = df)

test_performance(m1, m2, m3)
#> Name | Model |     BF |   Omega2 | p (Omega2) |    LR | p (LR)
#> --------------------------------------------------------------
#> m1   |    lm |        |          |            |       |       
#> m2   |    lm | > 1000 |     0.06 |     0.014  | 23.75 | < .001
#> m3   |    lm |  0.066 | 9.02e-04 |     > .999 |  0.38 | 0.993 
#> Models were detected as nested and are compared in sequential order.
```

<sup>Created on 2021-06-12 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by strengejacke** [comment]
> df <- tidyr::drop_na(penguins)

I wouldn't do such thing to remove NA from a dataset for regression modelling, because it often removes more cases than necessary :-)

In which way would you anticipate this situation?

**Comment by bwiernik** [comment]
If the predictors in a model have differential missing data (eg, like the penguins example).  Since we just are reporting individual model results and not tests of differences or anything, why don't we just ensure the same variable name without worrying about same vector, and also report the N in the table

**Comment by strengejacke** [comment]
Is the LRT still valid then?

**Comment by bwiernik** [comment]
No.

I guess I'm not exactly sure the aim of this function. Right now it seems to mostly be tabling coefficients, but not applying any tests that I can see

**Comment by strengejacke** [comment]
No, test_performance() performs a LRT-test, or a wald-test. See description of tests here:
https://easystats.github.io/performance/reference/test_performance.html

**Comment by bwiernik** [comment]
Oh, sorry, I was thinking we were talking about compare_parameters()

Yeah, none of the LRT or information criteria are comparable if the response vectors differ.

**Comment by IndrajeetPatil** [comment]
> The models don't have the same response variable, which is a prerequisite to compare them.

So maybe the function should fail here, but fail with a different error message?

**Comment by bwiernik** [comment]
I think referring to the "same response data" rather than "same response variable" might be clearer?

**Comment by bwiernik** [comment]
In the case that the response is transformed, we should direct users to use glm() and a link function instead of lm()

**Comment by strengejacke** [comment]
> In the case that the response is transformed, we should direct users to use glm() and a link function instead of lm()

What do you exactly mean here?

**Comment by bwiernik** [comment]
These aren't comparable:
```r
lm(mpg ~ wt, data = mtcars)
lm(log(mpg) ~ wt, data = mtcars)
```

But these are:

```r
lm(mpg ~ wt, data = mtcars)
glm(mpg ~ wt, family = gaussian(link = "log"), data = mtcars)
```

**Comment by strengejacke** [comment]
> In the case that the response is transformed, we should direct users to use glm() and a link function instead of lm()

I have changed `test_performance()` so it checks for log-transformed responses, and uses the corrected ll then.
