### ISSUE TITLE
check_assumptions()

### ISSUE THREAD

**Issue by strengejacke** [easystats/performance#31]
Maybe we should think of a new "class" of functions, prefixed with `check_*`, made for... checking stuff for our models. This could be a way of regrouping them together and making them more discoverable. They would become `check_overdispersion()`, `check_zeroinflation()` etc.

Based on recent questions that I had from students, other possible functions (not necesserily implemented in `performance`) come to my mind, such as `check_normality` and `check_homogeneity` (of variances), and other functions that would facilitates the checks to see if it's suited for parametric analyses... which would be very useful for students.

_Originally posted by @DominiqueMakowski in https://github.com/easystats/performance/pull/24#issuecomment-473315082_

**Comment by strengejacke** [comment]
http://www.cookbook-r.com/Statistical_analysis/Homogeneity_of_variance/

**Comment by strengejacke** [comment]
http://www.sthda.com/english/articles/39-regression-model-diagnostics/161-linear-regression-assumptions-and-diagnostics-in-r-essentials/#linearity-of-the-data

Might be something we can add to see as well.

**Comment by strengejacke** [comment]
I think we should have a `check_assumptions()` method in particular for models, that does some visual assumptions checking (diagnostic plots), where the plotting code can go into _see_. Things like `check_homogeneity()` don't make sense using a test like Levene, since you can just compare "groups", i.e. it only applies to (limited) factorial designs, not to models in general.

**Comment by strengejacke** [comment]
all other important check-functions have been added now, any comments on the style of implementation?

https://easystats.github.io/performance/reference/check_heteroscedasticity.html
https://easystats.github.io/performance/reference/check_autocorrelation.html
https://easystats.github.io/performance/reference/check_normality.html

**Comment by DominiqueMakowski** [comment]
That's awesome. I would maybe emphasise the "bad" results, either by colour or by something like "warning: ...".

For instance:

- `Residuals are normally distributed (p = %.3f).` -> `OK: The residuals appear as normally distributed (p = %.3f).` 
- `Non-normality of residuals detected (p = %.3f).` -> `Warning: Non-normality of residuals detected (p = %.3f).`

**Comment by DominiqueMakowski** [comment]
Just to make the good/bad results more salient

**Comment by mattansb** [comment]
How would these work for nested models (such as `lmer`) where there are many "residuals"? (the variance of random effects for example also needs to be constant, and the random effects need to be normal, etc).

For plotting, have you seen [`ggResidpanel`](https://cran.r-project.org/package=ggResidpanel)?

**Comment by strengejacke** [comment]
Yes, I have seen the announcement of ggResidpanel, however, it seems less sophisticated than what `sjPlot::plot_model(type = "diag")` does. The latter is something that could go into _performance_.

**Comment by strengejacke** [comment]
@mattansb I think we can address more complex models in a future update.

**Comment by mattansb** [comment]
Fair enough 😎
(I will just add that all diagnostics on residuals I've ever seen seem to focus on model residuals only, and completely overlook the assumption regarding "nested" / "projected" residuals. 🤦‍♂️🤷‍♂️)

**Comment by strengejacke** [comment]
For the furst step, I think this implementation is sufficient. Diagnostics for Stan-models currently only focus on the comparison of prior and posterior samples, maybe we can add something more here in the future.

**Comment by pdwaggoner** [comment]
This is some great stuff - I really like the new `check_*` family. In this vein, I wrote a function to check for influential observations via cook's distance. Its in a similar flavor as your measures @strengejacke , and also includes options to print names of outliers, drop outliers (and write a new df), and plot cook's distance.

I would welcome any thoughts here or whether this is even a desired "check". Thanks all!


``` r
check_outliers <- function(model, print_outliers = TRUE, drop_outliers = FALSE, plot = TRUE) {
  data <- insight::get_data(model)
  n <- nrow(data)
  
  #calculate cook's distance
  cook <- stats::cooks.distance(model)
  o <- length(as.numeric(names(cook)[(cook > (4/n))]))
  outliers <- ifelse(o >= 1, 1, 0)
  
  # check for outliers via cook's distance
  if (outliers >= 1) {
    insight::print_color(sprintf("Warning: Outliers detected.\n"), 'red')
  } else insight::print_color(sprintf("OK: No outliers detected.\n"), 'green')
  
  #option to print names of outliers
  if (print_outliers == TRUE) {
    print((names(cook)[(cook > (4 / n))]))
  }
  
  # option to drop outliers and write a new data frame (- outliers)
  if (drop_outliers == TRUE) {
    data_dropped <- data[!(cook > (4 / n)), ]
    return(data_dropped)
  }
  
  # option to plot cook's distance values, with line denoting likely outliers
  if (plot == TRUE){
    plot(cook, pch = 19, 
         main = "Check for Influential Observations\n(Cook's Distance)",
         ylab = "Cook's Distance Value")
    abline(h = (4 / n), 
           col = "red",
           cex = 4)
    text(x = 1:length(cook) + 1, 
         y = cook, 
         labels = ifelse(cook > (4 / n), 
                         names(cook), ""), 
         col = "red")
  }
}

# example
mt1 <- mtcars[, c(1,3)]  # select only mpg and disp (continuous)
oo <- data.frame(mpg = c(37, 40), # create some fake outliers
                 disp = c(300, 400))
mt2 <- rbind(mt1, oo)  # attach outliers to main df
model <- lm(disp ~ mpg, data = mt2) # fit model with outliers

# call the function
check_outliers(model, print_outliers = TRUE, drop_outliers = FALSE, plot = TRUE)
#> Warning: Outliers detected.
#> [1] "1" "2"
```

![](https://i.imgur.com/Dafuo2Q.png)

<sup>Created on 2019-06-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by pdwaggoner** [comment]
@strengejacke et al., sorry to be just a couple minutes later here!
