### ISSUE TITLE
fixing `check_homogeneity` example

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/performance#311]
I am guessing the example here errors because we need to use `<<-` instead of `<-`?
https://easystats.github.io/performance/reference/check_homogeneity.html

<img width="889" alt="Screenshot 2021-06-17 at 14 04 23" src="https://user-images.githubusercontent.com/11330453/122393269-fcd67080-cf74-11eb-92a2-e8c0b21b6b4d.png">

**Comment by bwiernik** [comment]
I'm not getting that error. I don't see why scope would be an issue here to necessitate <<-

**Comment by IndrajeetPatil** [comment]
You don't get this error when you run the example interactively, but do when `pkgdown` build the website, as can be seen on the webpage.

**Comment by bwiernik** [comment]
interactively

**Comment by IndrajeetPatil** [comment]
closed in https://github.com/easystats/performance/commit/8d1f41d96a7865e17fa0d143f1e4488da83eebee

**Comment by IndrajeetPatil** [comment]
The same fixes a bunch of other examples as well

<img width="884" alt="Screenshot 2021-06-19 at 10 09 33" src="https://user-images.githubusercontent.com/11330453/122637090-1d293b00-d0ed-11eb-9f05-3917fb0c3715.png">
<img width="902" alt="Screenshot 2021-06-19 at 10 10 19" src="https://user-images.githubusercontent.com/11330453/122637091-1dc1d180-d0ed-11eb-84a9-b1f7dcc6eea8.png">
