### ISSUE TITLE
Support for glmerMod objects, and not only glm

### ISSUE THREAD

**Issue by nadavrap** [easystats/performance#315]
The function `performance_roc` works for a single `glmerMod` object with returns from a GLMM regression performed by `lme4::glmer`. However, the function `performance_roc` failed when the input includes multiple `glmerMod` objects with the next error message:

`performance::performance_roc(m1, m2)`
> Warning messages:
> 1: Object 'm1' is not valid. 
> 2: Object 'm2' is not valid. 

I found it's due to the next piece of code in `performance_roc.R`
    `if (inherits(x[[i]], "glm"))`
As `glmerMod` does not inherit from `glm`. 

Is it possible to add this type of object as well, or is it going to break somewhere else?

**Comment by IndrajeetPatil** [comment]
Reprex:

 ``` r
library(performance)
library(lme4)
#> Loading required package: Matrix

m1 <- glmer(cbind(incidence, size - incidence) ~ period + (1 | herd),
              data = cbpp, family = binomial)

cbpp$obs <- 1:nrow(cbpp)
m2 <- glmer(cbind(incidence, size - incidence) ~ period + (1 | herd) + (1|obs),
               cbpp, binomial)

performance_roc(m1, m2)
#> Warning: Object 'm1' is not valid.
#> Warning: Object 'm2' is not valid.
#>      [,1]                       
#> [1,] "Object 'm1' is not valid."
#> [2,] "Object 'm2' is not valid."
```

<sup>Created on 2021-07-02 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by strengejacke** [comment]
``` r
library(performance)
library(lme4)
#> Loading required package: Matrix

m1 <- glmer(cbind(incidence, size - incidence) ~ period + (1 | herd),
            data = cbpp, family = binomial)

cbpp$obs <- 1:nrow(cbpp)
m2 <- glmer(cbind(incidence, size - incidence) ~ period + (1 | herd) + (1|obs),
            cbpp, binomial)

performance_roc(m1, m2)
#> Error: 'x' and ' predictions' must be of same length.


mtcars$obs <- 1:nrow(mtcars)
m1 <- glmer(vs ~ wt + mpg + (1 | cyl), data = mtcars, family = "binomial")
m2 <- glmer(vs ~ wt + mpg + (1 | cyl) + (1 | obs), data = mtcars, family = "binomial")
#> boundary (singular) fit: see ?isSingular

performance_roc(m1, m2)
#> # Area under Curve
#> 
#>   m1: 96.43%
#>   m2: 96.43%
```

<sup>Created on 2021-07-14 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>
