### ISSUE TITLE
Bayes factors per contrast from emmeans for categorical brms model error

### ISSUE THREAD

**Issue by mz555** [easystats/performance#316]
I am attempting to use the describe_posterior to obtain BF for all emmeans contrasts I specify. However, I have tried doing so with a categorical model computed in brms, and it does not seem to take the dpar argument when trying to run the sampling.

This is part of my code which may illustrate my point:

```r
#model (with a categorical -1, 0, 1 response); Condition has two levels, and Original has 3.
m1.bias <- brm(Bias ~ Condition*Original + (1| Participant),
data = SEacc,
family = categorical(),
warmup = 2000,
iter = 40000,
save_pars = save_pars(all = TRUE),
prior = my_bias_priors,
control = list(adapt_delta = 0.9))

#the contrasts I care about - works for getting what i want w/o BFs
pw.bias.profile <- emmeans(m1.bias, specs = pairwise ~Original, point.est = median, level = .89, dpar = "mu0")

#the code I am failing to run for the BFs
describe_posterior(pw.bias.profile,
estimate = "median", dispersion = TRUE,
ci = .89, ci_method = "hdi",
test = c("bayesfactor"),
bf_prior = m1.bias,
dpar= "mu0")

#the error
Sampling priors, please wait...
Error : The select parameter is not predicted by a linear formula. Use the 'dpar' and 'nlpar' arguments to select the parameter for which marginal means should be computed.
Predicted distributional parameters are: 'mu0', 'mu1'
Predicted non-linear parameters are: ''
Error in emmeans::ref_grid(prior) :
Perhaps a 'data' or 'params' argument is needed
```

I would greatly appreciate the help with figuring out how to write the correct code to get the needed BFs. Or if it is not possible, to know this so I can at least justify it in my paper.

Thank you in advance.

**Comment by bwiernik** [comment]
Personally, it doesn't really make sense to me to speak about Bayes Factor comparisons for a specific parameter/contrast rather than for comparing full _models_.

If your aim is to discuss whether your data support a null value for each contrast, I suggest you do that by interpreting the posterior distribution with reference to a region of practical equivalence (ROPE)--that is, a range of values you deem negligible or effectively null. For example, in the below distribution, the model suggests that most of the posterior is in the ROPE, so a negligible parameter value is more supported than a non-negligible one.

``` r
x <- rnorm(1000, mean = .05, sd = .1)
bayestestR::describe_posterior(x, rope_range = c(-.10, .10))
#> Summary of Posterior Distribution
#> 
#> Parameter | Median |        95% CI |     pd |          ROPE | % in ROPE
#> -----------------------------------------------------------------------
#> Posterior |   0.05 | [-0.15, 0.24] | 70.00% | [-0.10, 0.10] |    63.93%
```

<sup>Created on 2021-06-23 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by mz555** [comment]
Hi @bwiernik , thank you for the reply. I tend to agree about ROPE over BF, even though I remember reading https://doi.org/10.3758/s13423-017-1420-7 where they suggest BFs are more interpretable to a larger audience (in my field, psychology, I would agree that people are now picking up on BFs - due to JASP - but less so for ROPE). 
However, at present, I am just curious why getting BFs seems to work with the code above for every model I run (including ordinal, gaussian, bernoulli), but I get this error from categorical models. Is there a way to get BFs for contrasts using describe_posterior in this case? Thank you again in advance.

**Comment by bwiernik** [comment]
My point is that Bayes Factor is a statistic for comparing models. It doesn't make much sense to talk about a Bayes Factor for a specific part of a model. That's like asking "What's the likelihood for the first coefficient in the model?" or "What's the AIC for the first coefficient of the model?"

(Personally, I am not enthusiastic about the uptick in reporting of Bayes Factors in psychology, as they are very commonly misinterpreted (eg, http://datacolada.org/78c). I would argue that common interpretations of BF are worse than common misinterpretations of p values.)

**Comment by mz555** [comment]
@bwiernik but in this case it would be for pairwise contrasts, which would be akin to a t-test between two conditions. And again, my question here simply pertains to why the code works for other models types but not categorical. I see this more as a coding issue (or maybe limitation of the function). If you could let me know what the correct code would be I would appreciate it.

**Comment by DominiqueMakowski** [comment]
Aside from the rationale for/against OP's goal, the fact that it errors is strange. @mz555 could you provide some reproducible example so we can track & smash the bug?

**Comment by mz555** [comment]
Hi @DominiqueMakowski not sure what you would need so I am just attaching the data (i am not that proficient in R)

This is my setup:
### Libraries:
#model fit
library(brms)
library(bayestestR)
library(emmeans)

#set appropriate contrasts for factors with more than 2 levels.
options(contrasts = c('contr.orthonorm', 'contr.poly'))

#Make sure model understands which are factors
SEacc$Participant <-factor(SEacc$Participant)
SEacc$Original = factor(SEacc$Original)
SEacc$Bias = factor(SEacc$Bias)
SEacc$Condition = factor(SEacc$Condition)
SEacc$Trial = factor(SEacc$Trial)
[SEacc.xlsx](https://github.com/easystats/performance/files/6702544/SEacc.xlsx)

The model I ran is in my first post. Essentially, users are first split into two condition (Reveal or Visible), then they see three types of profiles (Bad, Mixed, Good). The bias response variable is coded as -1, 0, +1.

**Comment by mz555** [comment]
The solution was provided to me on the Stan forum by @mattansb 

Using the below code outputted the BFs for the model; 
```m1.bias_prior <- bayestestR::unupdate(m1.bias)
pw.bias.profile_prior <- emmeans(m1.bias_prior, specs = pairwise ~Original, point.est = median, level = .89, dpar = "mu0")
pw.bias.profile2_prior  <- emmeans(m1.bias_prior, specs = pairwise ~Original, point.est = median, level = .89, dpar = "mu1")

bayestestR::bayesfactor_parameters(pw.bias.profile, pw.bias.profile_prior)
bayestestR::bayesfactor_parameters(pw.bias.profile2, pw.bias.profile2_prior)
```

I also see a consensus with the point (made both here and on the Stan forum) than BFs with weakly (non) informative priors are not very meaningful, and I would like to learn more on this issue, especially as at present in programs like JASP or packages like ```ggstatsplot``` all seem to me to be using such priors to produce BFs in favour or against the null.

Thank you all for the assistance

**Comment by mattansb** [comment]
> I also see a consensus with the point (made both here and on the Stan forum) than BFs with weakly (non) informative priors are not very meaningful, and I would like to learn more on this issue, especially as at present in programs like JASP or packages like ggstatsplot all seem to me to be using such priors to produce BFs in favour or against the null.

the `BayesFactor` package is used both by JASP and `ggstatsplot` (@IndrajeetPatil, right?) for Bayes factors. This package uses "default" priors, which one might call "informative" (vs non- or weakly-informative). However even the package developers warn against these "defaults" (which is why JASP provides some robustness checks) and it is generally recommended to use subjective and informed priors based on domain knowledge whenever possible (and where not possible, not to use BFs).

**Comment by bwiernik** [comment]
This series of posts is a good discussion of the problems with using BF with diffuse priors to infer support for a null value: http://datacolada.org/78c

**Comment by mattansb** [comment]
For completness, here are some things I've added in my private correspondence with @mz555:

> Rouder and Morey define these "defaults" as suitable for experimental cognitive psych, where effect sizes tend to be larger than, say, in social psych. Elsewhere they explicitly say that the width of the "defaults" should be calibrated for each field according to domain knowledge (which makes the defaults... not so default?).
>
> Note that in `BayesFactor` there is some none standard parameterization going on, so the priors are on Cohen's d-like units, where as in `rstanarm` they are on standardized slope units, and in `brms` they are on the raw scale units. So *~N(0, 1)* or *~Cauchy(0, 0.71)* mean very different thing depending of the parameterization each package is using.

**Comment by mattansb** [comment]
> @bwiernik: My point is that Bayes Factor is a statistic for comparing models. It doesn't make much sense to talk about a Bayes Factor for a specific part of a model. That's like asking "What's the likelihood for the first coefficient in the model?" or "What's the AIC for the first coefficient of the model?"

This is not entirely accurate. A BF is an updating factor representing the change from prior to posterior in relative support between two sets of parameter(s) values (or spaces) [1]. Usually, this is quantified by comparing the marginal likelihoods of two models. But the Savage-Dickey density ratio can be used to examine this change in a single parameter / estimate (conditional on the model it is part of; in simple models this is an approximation to the comparison of marginal likelihoods) [2]. This is commonly done for point null hypotheses, but can also be expanded to compare ranges of parameter values [3,4].

### Refs:
- [1] https://www.bayesianspectacles.org/bayes-factors-for-those-who-hate-bayes-factors/
- [2] Wagenmakers, E. J., Lodewyckx, T., Kuriyal, H., and Grasman, R. (2010). Bayesian hypothesis testing for psychologists: A tutorial on the Savage-Dickey method. Cognitive psychology, 60(3), 158-189.
- [3] Morey, R. D., & Rouder, J. N. (2011). Bayes factor approaches for testing interval null hypotheses. Psychological methods, 16(4), 406.
- [4] Liao, J. G., Midya, V., & Berg, A. (2020). Connecting and contrasting the Bayes factor and a modified ROPE procedure for testing interval null hypotheses. The American Statistician, 1-19.

---

But to summaries this whole thread - pd + ROPE are the best way to go when you don't have specific informed priors.
