### ISSUE TITLE
Feature request: R2 values for Poisson models

### ISSUE THREAD

**Issue by anekb** [easystats/performance#324]
When running the function r2_bayes on poisson models the return is "bayes_R2 is only available for Gaussian and binomial models".
Is it possible to implement R2 calculations on poisson models as well?

**Comment by bwiernik** [comment]
Per http://www.stat.columbia.edu/~gelman/research/published/bayes_R2_v3.pdf

> Expanding the code to work for other generalized linear models requires some additional steps,
including setting transform=TRUE in the call to posterior_linpred (to apply the inverse-link
function to the linear predictor), the specification of the formula for varres for each distribution
class, and code to accomodate multilevel models fit using stan_glmer.

**Comment by bwiernik** [comment]
Actually, now that I check, we just rely on `rstantools::bayes_R2()` for this function. It now supports poisson models

``` r
m <- brms::brm(breaks ~ wool + tension, data = warpbreaks, family = "poisson")
performance::r2_bayes(m)
#> # Bayesian R2 with Standard Error
#> 
#>   Conditional R2: 0.278 (89% CI [0.203, 0.347])
rstantools::bayes_R2(m)
#>     Estimate  Est.Error      Q2.5     Q97.5
#> R2 0.2771867 0.04513538 0.1887002 0.3635722
```

<sup>Created on 2021-07-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by anekb** [comment]
Dear Brenton Wiernik,

Thank you very much for your reply to my issue.
I have just tried to run the code again on a poisson model. However, I get an error message (see below) – and I have no idea what it means. Any chance you can help?

Best wishes,
Ane


> m2 <- brms::brm(NMS3_pa_full_end ~  moisture_avg_start.c*treatment+npratio_start.c*treatment+ (1|site_nr),  data = env, family = "gaussian")
Compiling Stan program...
make cmd is
  make -f "C:/PROGRA~1/R/R-40~1.3/etc/x64/Makeconf" -f "C:/PROGRA~1/R/R-40~1.3/share/make/winshlib.mk" CXX='$(CXX14) $(CXX14STD)' CXXFLAGS='$(CXX14FLAGS)' CXXPICFLAGS='$(CXX14PICFLAGS)' SHLIB_LDFLAGS='$(SHLIB_CXX14LDFLAGS)' SHLIB_LD='$(SHLIB_CXX14LD)' SHLIB="file106475c1252d.dll" WIN=64 TCLBIN=64 OBJECTS="file106475c1252d.o"

make would use
if test "zfile106475c1252d.o" != "z"; then \
  if test -e "file106475c1252d-win.def"; then \
    echo /mingw64/bin/g++  -shared -s -static-libgcc -o file106475c1252d.dll file106475c1252d-win.def file106475c1252d.o   "C:/Users/au194814/Documents/R/win-library/4.0/rstan/lib/x64/libStanServices.a" -L"C:/Users/au194814/Documents/R/win-library/4.0/StanHeaders/libs/x64" -lStanHeaders -L"C:/Users/au194814/Documents/R/win-library/4.0/RcppParallel/lib/x64" -ltbb  -L"C:/PROGRA~1/R/R-40~1.3/bin/x64" -lR ; \
    /mingw64/bin/g++  -shared -s -static-libgcc -o file106475c1252d.dll file106475c1252d-win.def file106475c1252d.o   "C:/Users/au194814/Documents/R/win-library/4.0/rstan/lib/x64/libStanServices.a" -L"C:/Users/au194814/Documents/R/win-library/4.0/StanHeaders/libs/x64" -lStanHeaders -L"C:/Users/au194814/Documents/R/win-library/4.0/RcppParallel/lib/x64" -ltbb  -L"C:/PROGRA~1/R/R-40~1.3/bin/x64" -lR ; \
  else \
    echo EXPORTS > tmp.def; \
    /mingw64/bin/nm file106475c1252d.o | sed -n 's/^.* [BCDRT] / /p' | sed -e '/[.]refptr[.]/d' -e '/[.]weak[.]/d' | sed 's/[^ ][^ ]*/"&"/g'  >> tmp.def; \
    echo /mingw64/bin/g++  -shared -s -static-libgcc -o file106475c1252d.dll tmp.def file106475c1252d.o   "C:/Users/au194814/Documents/R/win-library/4.0/rstan/lib/x64/libStanServices.a" -L"C:/Users/au194814/Documents/R/win-library/4.0/StanHeaders/libs/x64" -lStanHeaders -L"C:/Users/au194814/Documents/R/win-library/4.0/RcppParallel/lib/x64" -ltbb  -L"C:/PROGRA~1/R/R-40~1.3/bin/x64" -lR ; \
    /mingw64/bin/g++  -shared -s -static-libgcc -o file106475c1252d.dll tmp.def file106475c1252d.o   "C:/Users/au194814/Documents/R/win-library/4.0/rstan/lib/x64/libStanServices.a" -L"C:/Users/au194814/Documents/R/win-library/4.0/StanHeaders/libs/x64" -lStanHeaders -L"C:/Users/au194814/Documents/R/win-library/4.0/RcppParallel/lib/x64" -ltbb  -L"C:/PROGRA~1/R/R-40~1.3/bin/x64" -lR ; \
    rm -f tmp.def; \
  fi \
fi
Error in compileCode(f, code, language = language, verbose = verbose) :
  C:/rtools40/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Users/au194814/Documents/R/win-library/4.0/rstan/lib/x64/libStanServices.a(stan_fit.o):stan_fit.cpp:(.rdata$_ZZN5boost4math6detail9bessel_j0IeEET_S3_E2P1[_ZZN5boost4math6detail9bessel_j0IeEET_S3_E2P1]+0x0): multiple definition of `boost::math::detail::bessel_j0<long double>(long double)::P1'; file106475c1252d.o:file106475c1252d.cpp:(.data$_ZZN5boost4math6detail9bessel_j0IeEET_S3_E2P1[_ZZN5boost4math6detail9bessel_j0IeEET_S3_E2P1]+0x0): first defined hereC:/rtools40/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Users/au194814/Documents/R/win-library/4.0/rstan/lib/x64/libStanServices.a(stan_fit.o):stan_fit.cpp:(.rdata$_ZZN5boost4math6detail9bessel_j0IeEET_S3_E2QC[_ZZN5boost4math6detail9bessel_j0IeEET_S3_E2QC]+0x0): multiple definition of `boost::math::detail::bessel_j0<long double>(long double)::QC'; file106475c1252d.o:file10647
In addition: Warning message:
I system(paste(CXX, ARGS), ignore.stdout = TRUE, ignore.stderr = TRUE) :
  '-E' not found
Error in sink(type = "output")

**Comment by strengejacke** [comment]
That looks rather like an Stan/rstan/brms related issue. I suggest asking [in the Stan-forums](https://discourse.mc-stan.org/) for help. For me, it worked switching from _rstan_ to [_cmdstanr_](https://mc-stan.org/cmdstanr/), which resolved complicated errors like yours.

After installing cmdstanr, you can add to your `.RProfile` file following line:

```
options(brms.backend = "cmdstanr", mc.cores = 4)
```

This makes _brms_ use cmdstanr by default.
