### ISSUE TITLE
Check's output consistency

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/performance#325]
Currently, the output of the checks is fairly inconsistent and somewhat unexpected (also #266). 

``` r
performance::check_heteroskedasticity(lm(mpg ~ wt, data = mtcars))
#> OK: Error variance appears to be homoscedastic (p = 0.846).
```

<sup>Created on 2021-07-09 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

Here, you would actually expect the output of the function to be actually the text displayed, rather than merely the p-value. 
That said, we could create a consistent and tidy output for checks made of a dataframe with the first column being the text (and/or the test name) that is printed, and additional columns being the values. It could be nicely rendered as text or as a table. 

In the example below, note that the plot is not working, because the plot tries to retrieve the model from the environment. We could store the model in the check output's attributes to avoid this kind of scope issue.

``` r
plot(performance::check_heteroskedasticity(lm(mpg ~ wt, data = mtcars)))
#> OK: Error variance appears to be homoscedastic (p = 0.846).
#> Error: Failed at retrieving data :( Please provide original model or data through the `data` argument
```

<sup>Created on 2021-07-09 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

The main problem is the text being still printed every time the function is run, which should not be the case... having a bespoke general `performance_check` class would allow printing nicely only when actually `print`ed. 

Recently there was a discussion about whether plots should be automated outputs, and while it's true that text, values and p-values have their limits and plots are preferable, I still think plots should be displayed only when `plot()` is called. Explicit behaviour is 👍

**Comment by bwiernik** [comment]
A more verbose textual description would be good. I like the idea of a table; that would make a print method straightforward.

> Recently there was a discussion about whether plots should be automated outputs, and while it's true that text, values and p-values have their limits and plots are preferable, I still think plots should be displayed only when plot() is called. Explicit behaviour is 👍

But `check_model()` is probably the most widely-used function in the easystats-verse. It plots by default (and no text at all). So, there is some inconsistency. Given that most folks probably just use `check_model()` rather than individual checks, I don't have much of a problem with the narrower functions not plotting by default
