### ISSUE TITLE
`check_consistency()` fails on `afex_aov` objects with `include_aov = FALSE`

### ISSUE THREAD

**Issue by singmann** [easystats/performance#326]
Hi all,

I am currently working on [version `1.0` of `afex`](https://github.com/singmann/afex/tree/v1) and discovered a bug in performance along the way. `check_consistency()` fails if the `aov` slot is not part of the `afex_aov` object:

 ``` r
library("performance")
suppressPackageStartupMessages(library("afex"))
data(obk.long, package = "afex")

obk.long$treatment <- as.character(obk.long$treatment)
aM <- afex::aov_car(value ~ treatment * gender + Error(id / (phase * hour)),
                      data = obk.long)
#> Converting to factor: treatment
#> Contrasts set to contr.sum for the following variables: treatment, gender
check_collinearity(aM)  
#> All predictors have been centered (factors with 'contr.sum()', numerics with
#>   'scale()').
#> # Check for Multicollinearity
#> 
#> Low Correlation
#> 
#>                         Term  VIF Increased SE Tolerance
#>                    treatment 1.04         1.02      0.96
#>                       gender 1.07         1.04      0.93
#>                        phase 1.15         1.07      0.87
#>                         hour 1.33         1.15      0.75
#>             treatment:gender 1.07         1.04      0.93
#>              treatment:phase 1.20         1.10      0.83
#>                 gender:phase 1.15         1.07      0.87
#>               treatment:hour 1.45         1.20      0.69
#>                  gender:hour 1.33         1.15      0.75
#>                   phase:hour 1.77         1.33      0.56
#>       treatment:gender:phase 1.20         1.10      0.83
#>        treatment:gender:hour 1.45         1.20      0.69
#>         treatment:phase:hour 2.09         1.45      0.48
#>            gender:phase:hour 1.77         1.33      0.56
#>  treatment:gender:phase:hour 2.09         1.45      0.48
  
aM2 <- afex::aov_car(value ~ treatment * gender + Error(id / (phase * hour)),
                      data = obk.long, include_aov = FALSE)
#> Converting to factor: treatment
#> Contrasts set to contr.sum for the following variables: treatment, gender
check_collinearity(aM2)  
#> All predictors have been centered (factors with 'contr.sum()', numerics with
#>   'scale()').
#> Error in cbind(fup_X1, fup_X2, fup_X3, fup_X4, fup_X5, post_X1, post_X2, : object 'fup_X1' not found
```

<sup>Created on 2021-07-09 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

The problem with this is that I will remove the `aov` slot per default in `afex` v1 (i.e., the new default will be `include_aov = FALSE`). The consequence of this is that the reverse dependency checks for `performance` fail with the new version as three of your tests involve `check_collinearity()` with `afex_aov()` objects. 

I was hoping to submit v1 to CRAN asap (actually yesterday) as `afex` will be archived on CRAN on 2021-07-22 if I do not resubmit a new version. However, with failing reverse dependency checks this is difficult. Could you let me know when you would be able to fix this on your end and could resubmit to CRAN? I hope that if you can tell me this will happen very soon, I can just resubmit to CRAN and assure them that you will resubmit a fixed version in a few days as well.

Sorry if this comes at a stressful time.

Cheers,
Henrik

**Comment by strengejacke** [comment]
Hi Henrik
I was on vacation, but returned today and will fix this issue within the next days. I guess I can submit by Thursday if nothing unexpected happens.

**Comment by strengejacke** [comment]
Could you give some advice how to handle this?
We have already revised some packages, so it can deal with the forthcoming afex v1.0. `check_collinearity()` is calling `insight::find_formula()`, which code is:

```r
function (x, verbose = TRUE, ...) 
{
  if (!is.null(x$aov)) {
    find_formula(x$aov, verbose = verbose, ...)
  }
  else {
    find_formula(x$lm, verbose = verbose, ...)
  }
}
```

which returns:

``` r
suppressPackageStartupMessages(library("afex"))
data(obk.long, package = "afex")

obk.long$treatment <- as.character(obk.long$treatment)
aM2 <- afex::aov_car(value ~ treatment * gender + Error(id / (phase * hour)),
                     data = obk.long, include_aov = FALSE)
#> Converting to factor: treatment
#> Contrasts set to contr.sum for the following variables: treatment, gender

insight::find_formula(aM2)
#> $conditional
#> cbind(fup_X1, fup_X2, fup_X3, fup_X4, fup_X5, post_X1, post_X2, 
#>     post_X3, post_X4, post_X5, pre_X1, pre_X2, pre_X3, pre_X4, 
#>     pre_X5) ~ treatment + gender + treatment:gender
#> <environment: 0x000000001f991420>
#> 
#> attr(,"class")
#> [1] "insight_formula" "list"
```

<sup>Created on 2021-07-13 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

`check_collinearity.afex_aov()` calls

```r
  check_collinearity(suppressWarnings(stats::lm(
    formula = f,
    data = d,
    contrasts = contrs
  )))
```

which results in the above mentioned error:

```r
#> Error in cbind(fup_X1, fup_X2, fup_X3, fup_X4, fup_X5, post_X1, post_X2, : object 'fup_X1' not found
```

So, what would be the best way to retrieve the proper formula from an `.afex_aov` object?

**Comment by singmann** [comment]
Thanks for looking at that. The problem does not appear to be with not with the formula. This formula obtained from `insight::find_formula` is correct. `afex_aov` per default now only contains the the `lm` slot which, in the case of repeated measures data, holds the multivariate object (of class `"mlm" "lm"`) for which the left hand side of the formula is a matrix created with `cbind()`. The corresponding data is contained in the `object$data$wide` slot. So in this case the problem seems to be the `d` in your call. 

However, as the `lm` slot already holds a multivariate `lm` object, this seems to fail as well, even with correct data:
``` r
library("performance")
suppressPackageStartupMessages(library("afex"))
data(obk.long, package = "afex")

obk.long$treatment <- as.character(obk.long$treatment)
aM2 <- afex::aov_car(value ~ treatment * gender + Error(id / (phase * hour)),
                      data = obk.long, include_aov = FALSE)
#> Converting to factor: treatment
#> Contrasts set to contr.sum for the following variables: treatment, gender

formula(aM2$lm)
#> cbind(fup_X1, fup_X2, fup_X3, fup_X4, fup_X5, post_X1, post_X2, 
#>     post_X3, post_X4, post_X5, pre_X1, pre_X2, pre_X3, pre_X4, 
#>     pre_X5) ~ treatment + gender + treatment:gender
#> <environment: 0x0000000029b0b518>

check_collinearity(aM2$lm)
#> Error in vars[["conditional"]]: subscript out of bounds

newf <- formula(aM2$lm)
newd <- aM2$data$wide

newm <- lm(formula = newf, data = newd)
check_collinearity(newm)
#> Error in vars[["conditional"]]: subscript out of bounds
```

<sup>Created on 2021-07-13 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

Not sure what would be the desired output here to be honest.

**Comment by singmann** [comment]
It is maybe of interest that `car::vif()` also fails with multivariate models as `car` otherwise handles them well (i.e., `afex` use `car::Anova()` to turn multivariate models into repeated measures ANOVAs):

``` r
suppressPackageStartupMessages(library("afex"))
data(obk.long, package = "afex")

obk.long$treatment <- as.character(obk.long$treatment)
aM2 <- afex::aov_car(value ~ treatment * gender + Error(id / (phase * hour)),
                      data = obk.long, include_aov = FALSE)
#> Converting to factor: treatment
#> Contrasts set to contr.sum for the following variables: treatment, gender
car::vif(aM2$lm)
#> Error in if (names(coefficients(mod)[1]) == "(Intercept)") {: argument is of length zero
```

<sup>Created on 2021-07-13 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

So maybe the best solution is to give an error if no `aov` slot is present in `afex_aov` objects and ask to refit the model with `include_aov = TRUE` or use a mixed model instead.

**Comment by strengejacke** [comment]
Just curious, why does `include_aov` now default to `FALSE`?

**Comment by singmann** [comment]
The `aov` object was only used for follow-up tests using `emmeans` as the ANOVA table is based on the `lm` object and `car::Anova()`. However, since for some time now `emmeans` also supports follow-up tests using the multivariate `lm` model. The benefit of the `lm` model for this is that it handles imbalance better. For example, `?aov` says: 
> aov is designed for balanced designs, and the results can be hard to interpret without balance: beware that missing values in the response(s) will likely lose the balance.

The same benefit of `lm` over `aov` models holds for follow-up tests and imbalance can happen easily with between-subject factors. Likewise, sphericity violations seem to more strongly affect follow-up tests for `aov` objects compared to `lm` objects. Finally, calculating the `aov` object can be really expensive in case of a complex design (i.e., it can take several seconds up to minutes). In sum, it is time to retire the `aov` slot.

**Comment by singmann** [comment]
Looking at your changes in b576400c5c2945adcc5e2ef2d9f1a1a047bc66fa, these tests will fail with current `afex` (as `include_aov = TRUE` is the current default so the first tests will not result in an error) and only pass with `afex` v1. You could also write the tests such that they work with each version (i.e., put `include_aov = FALSE` to those models that should result in an error).

In any case, are you ready for me to submit to CRAN and tell them you will submit a version that does not fail as soon as mine is accepted?

**Comment by strengejacke** [comment]
> Looking at your changes in [b576400](https://github.com/easystats/performance/commit/b576400c5c2945adcc5e2ef2d9f1a1a047bc66fa), these tests will fail with current `afex` (as `include_aov = TRUE` is the current default so the first tests will not result in an error) and only pass with `afex` v1. You could also write the tests such that they work with each version (i.e., put `include_aov = FALSE` to those models that should result in an error).
> 
> In any case, are you ready for me to submit to CRAN and tell them you will submit a version that does not fail as soon as mine is accepted?

If I understand right, the next version will be 1.0.0, so tests should only be executed for the forthcoming afex package:

```r
if (require("afex") && utils::packageVersion("afex") >= package_version("1.0.0")) {
```

**Comment by mattansb** [comment]
This is very weird... I thought I had all of these fixed.

Will make a PR.

**Comment by strengejacke** [comment]
Yeah, might be that most/all are fixed, but I think we currently still handle the aov-slot, and we should check if methods for class `.afex_aov` work as intended if this slot is no longer present in future afex-updates.

**Comment by mattansb** [comment]
After fixing `insight`, the old code now works:

``` r
data(obk.long, package = "afex")

obk.long$treatment <- as.character(obk.long$treatment)
obk.long$phase <- as.character(obk.long$phase)

M <- afex::aov_car(value ~ treatment * gender + age + Error(id / (phase * hour)),
                   factorize = FALSE,
                   data = obk.long, include_aov = FALSE)
#> Registered S3 methods overwritten by 'lme4':
#>   method                          from
#>   cooks.distance.influence.merMod car 
#>   influence.merMod                car 
#>   dfbeta.influence.merMod         car 
#>   dfbetas.influence.merMod        car
#> Contrasts set to contr.sum for the following variables: treatment, gender

performance::check_collinearity(M)
#> All predictors have been centered (factors with 'contr.sum()', numerics with
#>   'scale()').
#> Warning: Model has interaction terms. VIFs might be inflated. You may check
#>   multicollinearity among predictors of a model without interaction terms.
#> # Check for Multicollinearity
#> 
#> Low Correlation
#> 
#>                    Term  VIF Increased SE Tolerance
#>                   phase 1.23         1.11      0.81
#>                    hour 1.51         1.23      0.66
#>               treatment 2.18         1.48      0.46
#>                  gender 1.15         1.07      0.87
#>                     age 2.96         1.72      0.34
#>              phase:hour 2.27         1.51      0.44
#>        treatment:gender 1.89         1.37      0.53
#>            phase:gender 1.31         1.15      0.76
#>             hour:gender 1.73         1.31      0.58
#>  phase:treatment:gender 3.72         1.93      0.27
#>       phase:hour:gender 2.98         1.73      0.34
#> 
#> Moderate Correlation
#> 
#>             Term  VIF Increased SE Tolerance
#>  phase:treatment 5.28         2.30      0.19
#>        phase:age 8.73         2.96      0.11
#> 
#> High Correlation
#> 
#>                         Term     VIF Increased SE Tolerance
#>               hour:treatment   27.85         5.28      0.04
#>                     hour:age   76.25         8.73      0.01
#>        hour:treatment:gender   13.81         3.72      0.07
#>         phase:hour:treatment  775.39        27.85      0.00
#>               phase:hour:age 5814.79        76.25      0.00
#>  phase:hour:treatment:gender  190.81        13.81      0.01
```

<sup>Created on 2021-07-14 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by strengejacke** [comment]
Submission was rejected / on hold, reason:

> Thanks, we see:
>
>    Suggests or Enhances not in mainstream repositories:
>      glmmTMB
> 
> Or wait if the maintainer ever gets this fixed and resubmit.

**Comment by strengejacke** [comment]
afaik, glmmTMB is already resubmitted.

**Comment by singmann** [comment]
That is good to know, `glmmTMB` is also a Suggests of `afex`. So I will run into the same issue. 

But as you say, the [CRAN incoming dashboard](https://lockedata.github.io/cransays/articles/dashboard.html) does show a new `glmmTMB` version submitted as of 2 days ago. Status "pending"

**Comment by singmann** [comment]
I have just got the mail from `CRAN` that `glmmTMB` is back up: https://cran.r-project.org/package=glmmTMB
So if you can resubmit `performance` today I can resubmit `afex` before its removal deadline (which is in two days, so I need to submit latest tomorrow).

**Comment by IndrajeetPatil** [comment]
A new version of `performance` is now on CRAN!

**Comment by singmann** [comment]
Great, thanks. `afex` is also resubmitted now.

**Comment by mattansb** [comment]
Thanks you @singmann !
