### ISSUE TITLE
r2 lmer error for singular fit

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/performance#33]
it seems that r2_nakagawa fails when singular fit. Better would be to warn and return NA? Unfortunately, don't have any reproducible example at the moment.

**Comment by strengejacke** [comment]
Yes, R2 can't be calculated for models with singular fits. insight already gives a warning and returns NA for the related variance component, which makes r2_nakagawa fail. We should use tryCatch to capture all exceptions?

**Comment by DominiqueMakowski** [comment]
is there a way of detecting singular fits? I remember seeing an `is_singular` function (in sjstats?), maybe we could add something like this to insight to detect and run it as part of the sanity checks before computing indices of perf.

**Comment by strengejacke** [comment]
https://github.com/easystats/performance/blob/master/R/check_singularity.R

But we should still use tryCatch because there are many different exceptions that are already caught in get_variance(). So we just pass on the warning/error message.

**Comment by DominiqueMakowski** [comment]
oops missed that :)

you're right!
