### ISSUE TITLE
ICC for single random effects

### ISSUE THREAD

**Issue by bri2020** [easystats/performance#338]
Dear all, 

I am sorry, but I think this is not really an issue - more a question. 
In terms of the stats, I have a suggestion. Can I get the ICC for single random effects? I think I always get the ICC value for the complete set of random effects. In that way we could say how much of the total variance is explained by one random effect or the other.

```
m <- glmmTMB::glmmTMB(cbind(C,T) ~sex*age +(1|randomeffect1)+(1|obs_effect)+(1| randomeffect2),
                                           family=binomial,
                                           data=data,
                                           control=glmmTMBControl(optimizer=optim,
                                                     optArgs=list(method="BFGS")))
icc= icc(m)
> icc
# Intraclass Correlation Coefficient

     Adjusted ICC: 0.074
  Conditional ICC: 0.074
```

What can I do? Is this general possible?

Best wishes,
Britta

**Comment by strengejacke** [comment]
You could try the `by_group` argument.

**Comment by bri2020** [comment]
Dear Daniel, 
Thank you, for the simple solution, and I'm sorry I didn't see that in the documentation itself, but somehow it was overlooked. Now that I know... somehow I had landed on the documentation of sjstats without having noticed it. Greetings from Hamburg to Hamburg ;D
