### ISSUE TITLE
Does the performance package allow for testing machine learning regression models?

### ISSUE THREAD

**Issue by kamaulindhardt** [easystats/performance#339]
**Dear authors and enthusiastic community,**

Recently I discovered this package and it seems to greatly improve the visualisation, communication and interpretation of model outputs. I am using the TidyModels framework for solving several regression problems and I have just finished my ensemble stacked model. However, I am very interested in knowing whether, and if so, how the performance package can be used to compare the models. 

Any useful examples or guidance on how how to use the performance package for comparing several machine learning regression models?

Thank you!

**Comment by bwiernik** [comment]
You can see a list of the supported model classes with `insight:: supported_models()`. You can see if a specific model you've fit is supported with `insight::is_supported_model()`

We currently have limited support for tidymodels classes.

**Comment by kamaulindhardt** [comment]
Thank you! That's great. 

I see that machine learning model performances are not really supported? Neither random forest, svm nor xgboost models supported? Is that correct?

Will there be an update with TidyModels supported?

**Comment by DominiqueMakowski** [comment]
It has been a long term goal since the early days of eaystats, but the main blocker is that none of the core contributors have experience with these models... So we're essentially waiting for a willing future someone that would contribute is expertise by kick-starting the support for more ml models :)

**Comment by IndrajeetPatil** [comment]
Closing in favor of https://github.com/easystats/easystats/issues/165
