### ISSUE TITLE
test_performance when Suggested package missing

### ISSUE THREAD

**Issue by bwiernik** [easystats/performance#344]
User reported a bug where `test_performance.ListNestedRegressions()` was only returning Bayes Factors, not anything else.

Turns out that's because other tests are silently omitted when the 'CompQuadForm' package is missing. 

```r
tryCatch({
        rez <- test_bf(objects, reference = "sequential")
        if (!is.null(rez)) {
            rez$Model <- NULL
            out <- cbind(out, rez)
        }
    }, error = function(e) {
    })
```

We should probably add a message here:

```r
    tryCatch({
        rez <- test_vuong(objects)
        rez$Model <- NULL
        out <- merge(out, rez, sort = FALSE)
    }, error = function(e) {
  if (grepl("Package 'CompQuadForm' is required", msg)) message("For additional tests, install the 'CompQuadForm' package by running: install.packages('CompQuadForm')") 
    })
```

Would we perhaps want to substitute a different test here, such as `test_lrt()` or `test_anova()` (or write and add `test_R2()`)?

**Comment by DominiqueMakowski** [comment]
> or write and add test_R2()

We should definitely write and add `test_r2()` in any case


I thought for nested models test_lrt was also called by default 🤔 ?

**Comment by bwiernik** [comment]
It uses test_vuong() which depends on the package. We should make what it calls dependent on the availability of the package.
