### ISSUE TITLE
[suggestion]: include xgboost, ranger, glmnet models 

### ISSUE THREAD

**Issue by verajosemanuel** [easystats/performance#346]
I assume the error I get is because that kind of models are not included in {performance}

Anytime I try to make it work with: glmnet, xgboost, ranger....

`Error in if (minfo$is_bayesian) { : argument is of length zero`

worked with any lm model, so I assume this could not be my fault.

Thanks a lot

**Comment by IndrajeetPatil** [comment]
The `easystats` ecosystem currently provides only limited support for ML methods, and we are discussing providing such support in new packages, although there is no guarantee that we will ultimately do so.

Closing in favor of https://github.com/easystats/easystats/issues/110, https://github.com/easystats/easystats/issues/165

**Comment by sidthakur08** [comment]
Wanted to check really quick if this feature was ever worked on?
