### ISSUE TITLE
compare_performance: Error in cat(insight::format_table(x))...

### ISSUE THREAD

**Issue by dpmoriarity** [easystats/performance#351]
Hello,

I really enjoy working with this package! Thank you for your work on it.

I just came back to a project I've been working on for ~ a year to extend some analyses and when I used "compare_performance" I get an error that I didn't 6 months ago. See below. For context the models are lmer with random slopes. Please let me know if it would be helpful if I emailed someone my code+data. Thank you!

Error in cat(insight::format_table(x)) : 
  argument 1 (type 'list') cannot be handled by 'cat'

**Comment by strengejacke** [comment]
> 6 months ago

That's several generations in easystats-development-time ;-)
I think you can resolve this by replacing `format_table()` with `export_table()`.

**Comment by dpmoriarity** [comment]
Thank you for your response! It's been fun keeping up with all the updates on Twitter.

I never included format_table in the original code, so I'm unsure how to implement this solution. My code using this package was limited to. Also, I'm new at using GitHub so please let me know if there is a better way for me to be providing this information. Cheers!

compare_performance(model1, model 2, rank = TRUE)

From: Daniel ***@***.***>
Sent: Monday, August 16, 2021 6:29 AM
To: easystats/performance ***@***.***>
Cc: Daniel P Moriarity ***@***.***>; Author ***@***.***>
Subject: [External] Re: [easystats/performance] compare_performance: Error in cat(insight::format_table(x))... (#351)


6 months ago

That's several generations in easystats-development-time ;-)
I think you can resolve this by replacing format_table() with export_table().

-
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Feasystats%2Fperformance%2Fissues%2F351%23issuecomment-899401791&data=04%7C01%7Cmort963%40temple.edu%7C88a375181b11496ab98408d960a09ce7%7C716e81efb52244738e3110bd02ccf6e5%7C0%7C0%7C637647065214949349%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=M6sNkqLhFIC0kpTkQyoyMl7qmbKOOicNVq45VFN7DUQ%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAJ5272ZKQDRZNYS3OLS5XNDT5DR5NANCNFSM5CGICVAQ&data=04%7C01%7Cmort963%40temple.edu%7C88a375181b11496ab98408d960a09ce7%7C716e81efb52244738e3110bd02ccf6e5%7C0%7C0%7C637647065214959343%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=yFCpvrKruaf4N45k6Gex0LIiOYDOHfqNm0yx%2BB%2BtMHw%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cmort963%40temple.edu%7C88a375181b11496ab98408d960a09ce7%7C716e81efb52244738e3110bd02ccf6e5%7C0%7C0%7C637647065214959343%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=EIcVBZ2ctSFyKEBvZKyspa%2F4yAi3s58vubYBOEkphao%3D&reserved=0> or Android<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7Cmort963%40temple.edu%7C88a375181b11496ab98408d960a09ce7%7C716e81efb52244738e3110bd02ccf6e5%7C0%7C0%7C637647065214969339%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=76Ov5SrPUwYmvgJq7VOcscdxUEgtzN2hZ%2BgQOZT6RWA%3D&reserved=0>.

**Comment by bwiernik** [comment]
Can you please update your packages in the current versions and be sure you still get the error. The easiest way to do that is to run:

`easystats::easystats_update()`

If you still get the error, please update to the development versions from GitHub and try again:

`easystats::install_latest()`

If the error is still around, can you give us a reproducible example that we can run so we can see the error? One way to do that is use a built in dataset in R and show us the code. The `reprex::reprex()` function can be helpful here.

**Comment by dpmoriarity** [comment]
I also had to update my actual version of R as well, but this worked! Appreciate both your help.

From: Brenton M. Wiernik ***@***.***>
Sent: Monday, August 16, 2021 10:11 AM
To: easystats/performance ***@***.***>
Cc: Daniel P Moriarity ***@***.***>; Author ***@***.***>
Subject: [External] Re: [easystats/performance] compare_performance: Error in cat(insight::format_table(x))... (#351)


Can you please update your packages in the current versions and be sure you still get the error. The easiest way to do that is to run:

easystats::easystats_update()

If you still get the error, please update to the development versions from GitHub and try again:

easystats::install_latest()

If the error is still around, can you give us a reproducible example that we can run so we can see the error? One way to do that is use a built in dataset in R and show us the code. The reprex::reprex() function can be helpful here.

-
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Feasystats%2Fperformance%2Fissues%2F351%23issuecomment-899542802&data=04%7C01%7Cmort963%40temple.edu%7Ccbfa14aef7fc412a27c408d960bf9c15%7C716e81efb52244738e3110bd02ccf6e5%7C0%7C0%7C637647198381010839%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=hzxHXaFvsIJ%2BWweVW7fwHAkBpqXwIHnbKYakL%2F0GEL0%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAJ52726XGVTE2EBCZVIP6SDT5EL5PANCNFSM5CGICVAQ&data=04%7C01%7Cmort963%40temple.edu%7Ccbfa14aef7fc412a27c408d960bf9c15%7C716e81efb52244738e3110bd02ccf6e5%7C0%7C0%7C637647198381020833%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ug6Kfqyunwikxx9avKT0CsRe70m3EiJHXZ%2F3muR7oyg%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cmort963%40temple.edu%7Ccbfa14aef7fc412a27c408d960bf9c15%7C716e81efb52244738e3110bd02ccf6e5%7C0%7C0%7C637647198381020833%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=78yKzGBHmiZc8k7nYBgwCGafYbEWd51A6W9xCeENwJ4%3D&reserved=0> or Android<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7Cmort963%40temple.edu%7Ccbfa14aef7fc412a27c408d960bf9c15%7C716e81efb52244738e3110bd02ccf6e5%7C0%7C0%7C637647198381030827%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=XF5l1qiGW8qrDn%2FfKwMJOfl1vyUyFaliuUscruuhATk%3D&reserved=0>.
