### ISSUE TITLE
Error related to Cooks Distance

### ISSUE THREAD

**Issue by gille597** [easystats/performance#352]
Error in order(plot_data$Cooks_Distance, decreasing = TRUE) : 
  argument 1 is not a vector

Hello, 

I am running an lm with three predictors and no missing data. I get the error above when I run check_model (my.model).

Do you think this might be an issue on my end? Or a bug?

Thank you!
Sarah

**Comment by bwiernik** [comment]
Could you give a full reproducible example that produces the bug?

**Comment by strengejacke** [comment]
_bump_

**Comment by IndrajeetPatil** [comment]
Closing this for now. Please reopen if the issue persists.

**Comment by jmbarbone** [comment]
I may have ran into the same issue.  It could be an issue with using `subset` inside `lm`.   Subsetting and saving to a different object seems to do the trick.

``` r
library(performance)
x <- data.frame(a = 1:10, b  = 1:10, z = 1:10)

mod <- lm(a ~ poly(b, 2), data = x)
try(check_model(mod))
#> Registered S3 method overwritten by 'see':
#>   method                    from      
#>   plot.visualisation_recipe datawizard

mod <- glm(a ~ poly(b, 2, raw = TRUE), data = x, subset = z > 1)
# this fails -- because of subset?
try(check_model(mod))
#> Error in order(plot_data$Cooks_Distance, decreasing = TRUE): argument 1 is not a vector

x2 <- subset(x, z > 1)
mod <- glm(a ~ poly(b, 2), data = x2)
try(check_model(mod))
```

<sup>Created on 2021-10-04 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
