### ISSUE TITLE
Issue with performance package loading

### ISSUE THREAD

**Issue by jwylie21** [easystats/performance#358]
Hello again!

I recently installed the effectsize package and ran into issues with insight (that have been fixed). However, now another issue is popping up with the performance package—so I'm unable to run anything with ggstatsplot or sjPlot. 

```
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  namespace ‘performance’ 0.7.3 is already loaded, but >= 0.7.3.1 is required
```

It seems that the performance package is currently at version 0.7.3, so I'm not sure what to do here. Any suggestions?

**Comment by strengejacke** [comment]
_bump_

**Comment by IndrajeetPatil** [comment]
Closing this for now. Please reopen if the issue persists.
