### ISSUE TITLE
`pp_check` with transformed responses

### ISSUE THREAD

**Issue by mattansb** [easystats/performance#359]
Transforming *in formula* like this is common in reaction-time analysis.

``` r
data(stroop, package = "afex")

head(stroop)
#>    pno condition study trialnum  congruency acc    rt
#> 1 s1_1   deplete     1        1   congruent   1 0.626
#> 2 s1_1   deplete     1        2   congruent   1 0.550
#> 3 s1_1   deplete     1        3 incongruent   1 0.872
#> 4 s1_1   deplete     1        4   congruent   1 0.635
#> 5 s1_1   deplete     1        5   congruent   1 0.660
#> 6 s1_1   deplete     1        6 incongruent   1 0.667

stroop <- stroop |>
  subset(study == 1) |>
  subset(acc == 1) |>
  subset(pno %in% levels(pno)[1:10])

m <- lme4::lmer(log(rt) ~ congruency * condition + 
                   (congruency * condition | pno),
                 data = stroop,
                 control = lme4::lmerControl("bobyqa"))
#> boundary (singular) fit: see ?isSingular

(ppc <- performance::pp_check(m))
#> Warning: Maximum value of original data is not included in the replicated data. Model may
#>   not capture the variation of the data.
```

![](https://i.imgur.com/kwbkElV.png)

``` r
ppc[1:50] <- lapply(ppc[1:50], exp)
ppc
```

![](https://i.imgur.com/i2CRFfj.png)

<sup>Created on 2021-08-31 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by bwiernik** [comment]
For the response variable, we should give a warning and encourage users to use a link function instead:

glmer(RT ~ ., family = gaussian(link = "log"))

**Comment by mattansb** [comment]
[`log(y) ~ .` + `family = gaussian()` is not that same as `y ~ .` + `family = gaussian(link = "log")`](https://stats.stackexchange.com/questions/21447/how-to-specify-a-lognormal-distribution-in-the-glm-family-argument-in-r#comment308726_63761) :/

**Comment by bwiernik** [comment]
I'm not following. They are the same, other than which metric is regressed as the "native" metric for scaling the likelihood, which can lead to minor optimization differences. No?

The link function parameterization has the advantage that it can be compared to say, a linear model.

**Comment by mattansb** [comment]
- `log(y) ~ . + family = gaussian()` = log-normal likelihood + a log link function (y is conditionally log-normally distributed).
- `y ~ . + family = gaussian(link = "log")` = normal likelihood + a log link function (y is conditionally normally distributed).

See https://stat.ethz.ch/pipermail/r-help/2004-December/062683.html

**Comment by DominiqueMakowski** [comment]
![image](https://user-images.githubusercontent.com/8875533/131633364-f7365927-f55d-4dcb-8c38-778be82951d5.png)

**Comment by bwiernik** [comment]
Ah, the constant variance vs CV point makes sense. Thanks!

**Comment by mattansb** [comment]
😎

**Comment by strengejacke** [comment]
The easiest thing is to check on the transformed scale:

``` r
data(stroop, package = "afex")

head(stroop)
#>    pno condition study trialnum  congruency acc    rt
#> 1 s1_1   deplete     1        1   congruent   1 0.626
#> 2 s1_1   deplete     1        2   congruent   1 0.550
#> 3 s1_1   deplete     1        3 incongruent   1 0.872
#> 4 s1_1   deplete     1        4   congruent   1 0.635
#> 5 s1_1   deplete     1        5   congruent   1 0.660
#> 6 s1_1   deplete     1        6 incongruent   1 0.667

stroop <- stroop |>
  subset(study == 1) |>
  subset(acc == 1) |>
  subset(pno %in% levels(pno)[1:10])

m <- lme4::lmer(log(rt) ~ congruency * condition + 
                  (congruency * condition | pno),
                data = stroop,
                control = lme4::lmerControl("bobyqa"))
#> boundary (singular) fit: see ?isSingular

performance::check_predictions(m)
```

![](https://i.imgur.com/5OoVW1i.png)

<sup>Created on 2021-09-12 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>


But I could also find which kind of transformation was done, and then back-transform all predictions.

**Comment by mattansb** [comment]
I think back-transforming all the reps would be better, but not critical.

**Comment by strengejacke** [comment]
``` r
data(stroop, package = "afex")

stroop <- stroop |>
  subset(study == 1) |>
  subset(acc == 1) |>
  subset(pno %in% levels(pno)[1:10])

m <- lme4::lmer(log(rt) ~ congruency * condition + 
                  (congruency * condition | pno),
                data = stroop,
                control = lme4::lmerControl("bobyqa"))
#> boundary (singular) fit: see ?isSingular

performance::check_predictions(m)
```

![](https://i.imgur.com/5X1SQ1x.png)

<sup>Created on 2021-09-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
