### ISSUE TITLE
attaching performance after rstanarm breaks pp_check S3 dispatch

### ISSUE THREAD

**Issue by bwiernik** [easystats/performance#360]
If I `library(easystats)` after `library(rstanarm)`, it breaks S3 dispatch on the `pp_check()` function, sending the `stanreg` model to performance's `glm` method, rather than the `stanreg` method. We should see if we can fix that or otherwise check if a model is `stanreg` and then send to the `bayesplot()` method manually.

``` r
library(rstanarm)
#> Loading required package: Rcpp
#> This is rstanarm version 2.21.1
#> - See https://mc-stan.org/rstanarm/articles/priors for changes to default priors!
#> - Default priors may change, so it's safest to specify priors, even if equivalent to the defaults.
#> - For execution on a local, multicore CPU with excess RAM we recommend calling
#>   options(mc.cores = parallel::detectCores())
library(performance)
#> 
#> Attaching package: 'performance'
#> The following object is masked from 'package:rstanarm':
#> 
#>     pp_check
m <- stan_glm(mpg ~ disp, data = mtcars)
#> 
#> SAMPLING FOR MODEL 'continuous' NOW (CHAIN 1).
#> Chain 1: 
#> Chain 1: Gradient evaluation took 0 seconds
#> Chain 1: 1000 transitions using 10 leapfrog steps per transition would take 0 seconds.
#> Chain 1: Adjust your expectations accordingly!
#> Chain 1: 
#> Chain 1: 
#> Chain 1: Iteration:    1 / 2000 [  0%]  (Warmup)
#> Chain 1: Iteration:  200 / 2000 [ 10%]  (Warmup)
#> Chain 1: Iteration:  400 / 2000 [ 20%]  (Warmup)
#> Chain 1: Iteration:  600 / 2000 [ 30%]  (Warmup)
#> Chain 1: Iteration:  800 / 2000 [ 40%]  (Warmup)
#> Chain 1: Iteration: 1000 / 2000 [ 50%]  (Warmup)
#> Chain 1: Iteration: 1001 / 2000 [ 50%]  (Sampling)
#> Chain 1: Iteration: 1200 / 2000 [ 60%]  (Sampling)
#> Chain 1: Iteration: 1400 / 2000 [ 70%]  (Sampling)
#> Chain 1: Iteration: 1600 / 2000 [ 80%]  (Sampling)
#> Chain 1: Iteration: 1800 / 2000 [ 90%]  (Sampling)
#> Chain 1: Iteration: 2000 / 2000 [100%]  (Sampling)
#> Chain 1: 
#> Chain 1:  Elapsed Time: 0.155 seconds (Warm-up)
#> Chain 1:                0.126 seconds (Sampling)
#> Chain 1:                0.281 seconds (Total)
#> Chain 1: 
#> 
#> SAMPLING FOR MODEL 'continuous' NOW (CHAIN 2).
#> Chain 2: 
#> Chain 2: Gradient evaluation took 0 seconds
#> Chain 2: 1000 transitions using 10 leapfrog steps per transition would take 0 seconds.
#> Chain 2: Adjust your expectations accordingly!
#> Chain 2: 
#> Chain 2: 
#> Chain 2: Iteration:    1 / 2000 [  0%]  (Warmup)
#> Chain 2: Iteration:  200 / 2000 [ 10%]  (Warmup)
#> Chain 2: Iteration:  400 / 2000 [ 20%]  (Warmup)
#> Chain 2: Iteration:  600 / 2000 [ 30%]  (Warmup)
#> Chain 2: Iteration:  800 / 2000 [ 40%]  (Warmup)
#> Chain 2: Iteration: 1000 / 2000 [ 50%]  (Warmup)
#> Chain 2: Iteration: 1001 / 2000 [ 50%]  (Sampling)
#> Chain 2: Iteration: 1200 / 2000 [ 60%]  (Sampling)
#> Chain 2: Iteration: 1400 / 2000 [ 70%]  (Sampling)
#> Chain 2: Iteration: 1600 / 2000 [ 80%]  (Sampling)
#> Chain 2: Iteration: 1800 / 2000 [ 90%]  (Sampling)
#> Chain 2: Iteration: 2000 / 2000 [100%]  (Sampling)
#> Chain 2: 
#> Chain 2:  Elapsed Time: 0.139 seconds (Warm-up)
#> Chain 2:                0.117 seconds (Sampling)
#> Chain 2:                0.256 seconds (Total)
#> Chain 2: 
#> 
#> SAMPLING FOR MODEL 'continuous' NOW (CHAIN 3).
#> Chain 3: 
#> Chain 3: Gradient evaluation took 0 seconds
#> Chain 3: 1000 transitions using 10 leapfrog steps per transition would take 0 seconds.
#> Chain 3: Adjust your expectations accordingly!
#> Chain 3: 
#> Chain 3: 
#> Chain 3: Iteration:    1 / 2000 [  0%]  (Warmup)
#> Chain 3: Iteration:  200 / 2000 [ 10%]  (Warmup)
#> Chain 3: Iteration:  400 / 2000 [ 20%]  (Warmup)
#> Chain 3: Iteration:  600 / 2000 [ 30%]  (Warmup)
#> Chain 3: Iteration:  800 / 2000 [ 40%]  (Warmup)
#> Chain 3: Iteration: 1000 / 2000 [ 50%]  (Warmup)
#> Chain 3: Iteration: 1001 / 2000 [ 50%]  (Sampling)
#> Chain 3: Iteration: 1200 / 2000 [ 60%]  (Sampling)
#> Chain 3: Iteration: 1400 / 2000 [ 70%]  (Sampling)
#> Chain 3: Iteration: 1600 / 2000 [ 80%]  (Sampling)
#> Chain 3: Iteration: 1800 / 2000 [ 90%]  (Sampling)
#> Chain 3: Iteration: 2000 / 2000 [100%]  (Sampling)
#> Chain 3: 
#> Chain 3:  Elapsed Time: 0.147 seconds (Warm-up)
#> Chain 3:                0.14 seconds (Sampling)
#> Chain 3:                0.287 seconds (Total)
#> Chain 3: 
#> 
#> SAMPLING FOR MODEL 'continuous' NOW (CHAIN 4).
#> Chain 4: 
#> Chain 4: Gradient evaluation took 0 seconds
#> Chain 4: 1000 transitions using 10 leapfrog steps per transition would take 0 seconds.
#> Chain 4: Adjust your expectations accordingly!
#> Chain 4: 
#> Chain 4: 
#> Chain 4: Iteration:    1 / 2000 [  0%]  (Warmup)
#> Chain 4: Iteration:  200 / 2000 [ 10%]  (Warmup)
#> Chain 4: Iteration:  400 / 2000 [ 20%]  (Warmup)
#> Chain 4: Iteration:  600 / 2000 [ 30%]  (Warmup)
#> Chain 4: Iteration:  800 / 2000 [ 40%]  (Warmup)
#> Chain 4: Iteration: 1000 / 2000 [ 50%]  (Warmup)
#> Chain 4: Iteration: 1001 / 2000 [ 50%]  (Sampling)
#> Chain 4: Iteration: 1200 / 2000 [ 60%]  (Sampling)
#> Chain 4: Iteration: 1400 / 2000 [ 70%]  (Sampling)
#> Chain 4: Iteration: 1600 / 2000 [ 80%]  (Sampling)
#> Chain 4: Iteration: 1800 / 2000 [ 90%]  (Sampling)
#> Chain 4: Iteration: 2000 / 2000 [100%]  (Sampling)
#> Chain 4: 
#> Chain 4:  Elapsed Time: 0.191 seconds (Warm-up)
#> Chain 4:                0.149 seconds (Sampling)
#> Chain 4:                0.34 seconds (Total)
#> Chain 4:
pp_check(m)
#> Warning in rnorm(ntot, sd = sqrt(vars)): NAs produced
#> Error in if (min(replicated) > min(original)) {: missing value where TRUE/FALSE needed
```

<sup>Created on 2021-09-01 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by strengejacke** [comment]
strange, since the method in _rstanarm_ is `pp_check.stanreg()`, and we don't overwrite the method for this class.

**Comment by bwiernik** [comment]
Speculating and not sure here. Is the issue that we export the pp_check() *function* and not just the S3 method? That is what positions out version of pp_check, and the methods in our namespace, ahead of the other methods? 

I'm not sure if the issue is solvable without importing pp_check from bayesplot. I think an acceptable solution would be to only export the S3 method and then to use check_posterior_prediction() as our exported user-facing function.

**Comment by bwiernik** [comment]
I messed around with a bunch of possible ways to co-exist with the pp_check() function in other packages.  There just isn't a way to export `pp_check()` without importing *bayesplot* and have satisfactory cooperation between packages.

When we export the `pp_check()` function without importing *bayesplot*, inevitably attaching the namespace of both *performance* and one of the Bayesian modeling packages inevitably obscures the namespace of one of the two packages, whichever was loaded first. Eg, if performance, then rstanarm, then `pp_check.lm()` breaks. If rstanarm then performance, `pp_check.stanreg()` breaks.

As a result, this is the best I can come up with:

1. We export the `pp_check.lm()` and other methods like this: `S3method(bayesplot::pp_check,MixMod)`. That will register S3 methods for these models, which will be dispatched if a package that exports `pp_check()` is attached.

For example:
```r
library(bayesplot)
devtools::load_all()
mf <- lm(mpg ~ disp, data = mtcars)
pp_check(mf)
```

This will work regardless of the order packages are attached. If no package exporting `pp_check()` is attached, then an error is returned: `Error in pp_check(mf) : could not find function "pp_check"`

2. We use `check_posterior_predictions()` as our exported function for these checks.

**Comment by DominiqueMakowski** [comment]
Regarding `pp_check`, tbh I'm a bit worried about expanding and re-using rstan's functions. What if they decide someday to cover some methods that we do, then some conflicts will appear and lead to some tough decisions to make.

For me the most straightforward solution would be to just go with our alias `posterior_predictive_check` (maybe we could rename it `check_predictive` to make it more general).

**Comment by strengejacke** [comment]
Maybe we should go for `check_posterior_predictions()`.

**Comment by DominiqueMakowski** [comment]
Yeah but if we support models that don't have a "posterior" per se it's a bit strange... maybe `check_predictions` is more general? or `check_predictive_distribution`

**Comment by bwiernik** [comment]
Frequentist models have a posterior 😜

**Comment by bwiernik** [comment]
Opened a PR to fix this. It does 3 things:

1. Makes the basic function `check_predictions()` with aliases `posterior_predictive_check()` and `check_posterior_predictions()`. 
2. In `check_predictions()`, it checks if the model is Bayesian and dispatches to `bayesplot::pp_check()`. This doesn't currently work with BayesFactor models.t
3. Delayed exports `pp_check()` methods for frequentist models so that `pp_check(lm_mod)` will work if *bayesplot* is attached.

**Comment by bwiernik** [comment]
Okay, small wrinkle: The `S3method(bayesplot::pp_check, lm)` syntax requires R 3.6.0+. There is a [way](https://vctrs.r-lib.org/reference/s3_register.html) to manually do delayed S3 registration on R 3.4 and 3.5 (implemented that in my latest commit), but that only works if bayesplot/etc. is loaded before performance. The R 3.6.0+ method works with packages loaded in either order.

Options:
1. Switch our dependency to R 3.6+ and keep using `S3method(bayesplot::pp_check, lm)`
2. Use the `s3_register()` approach linked above to register the methods `.onLoad()`, requiring bayesplot/etc to be loaded first.
3. Use the `S3method(bayesplot::pp_check, lm)` approach, but post-edit the NAMESPACE file after running `document()` to put R version checks around these.

Thoughts?

**Comment by strengejacke** [comment]
Looking at the hassle we have when trying to have a `pp_check()`, I suggest just using our own name for that function (mainly, point 1 from [here](https://github.com/easystats/performance/issues/360#issuecomment-913003043)).
