### ISSUE TITLE
glmmTMB beta_family r2()

### ISSUE THREAD

**Issue by mgree013** [easystats/performance#366]
I'm attempting to extract r2() conditional and marginal effects for a beta_family model using glmmTMB. Im getting warning message: mu of (blank) is too close to zero, estimate of random effect variances may be unreliable. Either the random variances are NA or quite large and leads me to believe they are being incorrectly estimated. Models and r2() work fine for my other response variable using Gaussian distributions, but the beta_family models seem to give people issues and after googling for hours on end, I cant seem to find anyone who has come up with a solution. 

Here is link to my data set (https://github.com/mgree013/Rethinking_Biodiversity_Streams/blob/main/data.csv) and the code I'm running (https://github.com/mgree013/Rethinking_Biodiversity_Streams/blob/main/glmmTMB.R) also pasted below:

mod1<-glmmTMB(betas.LCBD~ River.dist.lake+ (1|O.NET),family=beta_family(), data=data)
mod2<-glmmTMB(betas.LCBD~ Head.river.dist+ (1|O.NET),family=beta_family(),data=data)
mod3<-glmmTMB(betas.LCBD~ Head.river.dist*River.dist.lake+ (1|O.NET),family=beta_family(),data=data)
null<-glmmTMB(betas.LCBD~1+ (1|O.NET),family=beta_family(),data=data)
reported.table2 <- bbmle::AICtab(mod1,mod2,mod3,null,weights = TRUE, sort = FALSE)

performance::r2(mod1)
performance::r2(mod2)
performance::r2(mod3)
performance::r2(null)

And heres the gaussian response that works well and provides reasonable estimates for r2:

mod1<-glmmTMB(N1~ River.dist.lake+ (1|O.NET),family=gaussian(), data=data)
mod2<-glmmTMB(N1~ Head.river.dist+ (1|O.NET),family=gaussian(),data=data)
mod3<-glmmTMB(N1~ River.dist.lake*Head.river.dist+ (1|O.NET),family=gaussian(),data=data)
null<-glmmTMB(N1~1+ (1|O.NET),family=gaussian(),data=data)
reported.table2 <- bbmle::AICtab(mod1,mod2,mod3, null,weights = TRUE, sort = F)

performance::r2(mod1)
performance::r2(mod2)
performance::r2(mod3)
performance::r2(null)

See this rpubs for similar issue I'm facing: https://rpubs.com/elprogramadordeldiablo/r2

**Comment by bbolker** [comment]
I guess we'll try to find time to dig in. There's a very long thread [here](https://github.com/glmmTMB/glmmTMB/issues/169), where people refer to beta family at the bottom ... it will be good to have a reproducible example, because it's really hard to distinguish when people are overfitting/fitting unstable or nearly singular models and when there's actually a bug ...

**Comment by mgree013** [comment]
Greta just added a reproducible example with a link to the data set on github and the code pasted below.

**Comment by bbolker** [comment]
I worked on this a bit. Honestly, I don't see anything wrong (i.e., no evidence that the Beta models are actually doing anything weird) except for the "mu of 0.1 is too close to zero, estimate of **** may be unreliable" warnings, which emanate from `insight::.compute_variances()`. I think you'd have to go all the way back to Nakagawa/Schielzeth/Johnson to understand why a low predicted value at the intercept would give an unreliable estimate of the RE variances ... ??  

I made a gist, which doesn't do much but streamline your example a bit/examine the coefficients to make sure they're reasonable: https://gist.github.com/bbolker/d2f1754ce7ce41736de120d09f075288

I don't see any evidence at all for

>  Either the random variances are NA or quite large and leads me to believe they are being incorrectly estimated. 

... where are you seeing that?

**Comment by mgree013** [comment]
Thanks for the Ben, I really appreciate it. I guess my confusion is how to interpret these conditional R2 values when I'm getting the warning "mu of 0.1 is too close to zero..." Should these values not be trusted? I don't think so given the warning and they explain so much variation, where my other example with the gaussian models don't show much evidence for really high explanatory power of random effects. I have not been able to find any code or papers out there that use glmmtmb models with beta family distributions and report R2, which makes this tricky. Im thinking of just reporting AIC values and ditching R2 (or at least ditching conditional R2).


The warning message where I get NA's for conditional R2 are from another set of models. 

I pasted the warning below:

Warning messages:
1: Can't compute random effect variances. Some variance components equal zero. Your model may suffer
  from singulariy.
  Solution: Respecify random structure! You may also decrease the 'tolerance' level to enforce the
  calculation of random effect variances. 
2: mu of 0.0 is too close to zero, estimate of random effect variances may be unreliable.

**Comment by mgree013** [comment]
Okay this make sense Ben. It sounds like mixed models may not be necessary then to account for variation among our groups, since the among group variances are estimated as zero (or really close to zero 1e-10). Thanks for all the help!

**Comment by strengejacke** [comment]
> I think you'd have to go all the way back to Nakagawa/Schielzeth/Johnson to understand why a low predicted value at the intercept would give an unreliable estimate of the RE variances ... ??

If I remember right, this warning was taken from your code, @bbolker. Quite some time ago, you posted a quick draft in the glmmTMB repo that implemented the log(normal)-approximated R2 values for mixed models based on Nakagawa (based on a cleaned-up/adapted version of Jon Lefcheck's code from SEMfit?), and this draft included this warning.

I asked you if I could use part of this code to implement a function that calculates variance components and R2, and I copied that warning - that's how it came into this function :-) 

`mu` refers to the exponentiated coefficient (intercept) of the null-model, which is required to compute `log(1+var(x)/mu^2)` as lognormal-approximation of the distributional variance.
