### ISSUE TITLE
check_zeroinflation() wrong results with glmmTMB Ngative Binomial

### ISSUE THREAD

**Issue by ClaudioZandonella** [easystats/performance#367]
Thanks for this amazing package!

I found a small issue concerning `performance::check_zeroinflation()` with models obtained from `glmmTMB::glmmTMB()` using Negative Binomial distributions.

Minimal Working Example
```r
data(Salamanders, package = "glmmTMB")

fit_mass <- MASS::glm.nb(count ~ spp + mined, data = Salamanders)
fit_tmb <- glmmTMB::glmmTMB(count ~ spp + mined, data = Salamanders, family=glmmTMB::nbinom2())
```

I fitted two models on the same data specifying a negative binomial distribution using respectively`MASS::glm.nb()` and `glmmTMB::glmmTMB()`. As you can see estimated parameters are identical.
```r
coefficients(fit_mass)
(Intercept)       sppPR       sppDM     sppEC-A     sppEC-L    sppDES-L       sppDF     minedno 
 -1.4605320  -1.2277880   0.4043891  -0.6707205   0.6387474   0.8215330   0.3600422   2.0380754 

glmmTMB::fixef(fit_tmb)
Conditional model:
(Intercept)        sppPR        sppDM      sppEC-A      sppEC-L     sppDES-L        sppDF      minedno  
    -1.4605      -1.2278       0.4044      -0.6707       0.6387       0.8215       0.3600       2.0381 
```

Results from `performance::check_zeroinflation()` , however, are very different:
```r
performance::check_zeroinflation(fit_mass)
# Check for zero-inflation

   Observed zeros: 387
  Predicted zeros: 374
            Ratio: 0.97

Model seems ok, ratio of observed and predicted zeros is within the tolerance range.

performance::check_zeroinflation(fit_tmb)
# Check for zero-inflation

   Observed zeros: 387
  Predicted zeros: 297
            Ratio: 0.77

Model is underfitting zeros (probable zero-inflation).
```

This is a problem as the model are identical (almost). Digging into the code, I found that the problem in this part of the code

https://github.com/easystats/performance/blob/371f1bbbbeff399af1356eacb690a3b7e34f2cdf/R/check_zeroinflation.R#L47-L52

where `x` is the model fit. Note that `x$theta` works fine for `glm.nb` objects but not `glmmTMB` objects
```r
fit_mass$theta
[1] 0.8052867

fit_tmb$theta
NULL
```

To properly get the dispersion parameter from `glmmTMB` objects, the function `stats::sigma()` can be used:
```r
stats::sigma(fit_tmb)
[1] 0.8052869
```

Failing to get `x$theta`, the function actually ends up evaluating density from a Poisson distribution, rather than negative binomial (see code linked).

Note that this issue may affect other functions as well where the dispersion parameter is involved

**Comment by ClaudioZandonella** [comment]
An easy solution could be

```r
# get theta
  if(is(x, "glmmTMB")){
    theta <- stats::sigma(x)
  } else {
    theta <- x$theta
  }
  mu <- stats::fitted(x)
  if (model_info$is_negbin && !is.null(theta)) {
    pred.zero <- round(sum(stats::dnbinom(x = 0, size = theta,
                                          mu = mu)))
  }
```

Note that in the case of `glm.nb` objects `x$theta` and `stats::sigma(x)` give different results.

From previous example
```
fit_mass$theta
[1] 0.8052867

stats::sigma(fit_mass)
[1] 0.9253467
```

**Comment by strengejacke** [comment]
Thanks, your suggestion looks good!

**Comment by florianhartig** [comment]
Hi, 

I'm not sure if this was really fixed, see https://github.com/florianhartig/DHARMa/issues/392

**Comment by strengejacke** [comment]
I'm not sure if this is a "bug" or an inaccuracy due to the chosen approach. We will look into this.

We wanted to rely on DHARMa to improve the methods in the long run...
See #376 and #595.
