### ISSUE TITLE
Revise readme for release

### ISSUE THREAD

**Issue by strengejacke** [easystats/performance#37]
Since we have no vignettes yet, I would like to revise the readme a bit, starting with a short "about" paragraph, then maybe sections on

- [x] r2 / icc
- [x] check-functions
- [ ] item-functions
- [x] model_performance()

**Comment by strengejacke** [comment]
@DominiqueMakowski 
CRAN release and package building for bayestestR went very fast... I guess we can publish the blog-post next week, and maybe also submit performance to CRAN before easter...

**Comment by DominiqueMakowski** [comment]
Yep (it's my turn to be a bit swamped at work, but yes I will try to write up a small draft for bayestestR). And yes, for performance, would be great

**Comment by DominiqueMakowski** [comment]
(I like where the README is going :)

**Comment by strengejacke** [comment]
Yeah, it's becoming more a vignette than a short readme ;-)
But we still can extract parts and put them into vignettes later, if we like. For now, I think it's good to have examples that show a bit the scope of the package.
