### ISSUE TITLE
compare_performance() with transformed response variables

### ISSUE THREAD

**Issue by bwiernik** [easystats/performance#372]
For many transformations, we can compute a Jacobian to transform the log-likelihood/IC values, as well as R^2, sigma, etc.

e.g., for log(y): https://stats.stackexchange.com/q/343176

@strengejacke Could you figure out how we can detect if the responses for models with differing responses have the same base variable (e.g., `y` and `log(y)` or `sqrt(y)` or `(1 / y)`)? At least `log(y)` would be great.

**Comment by strengejacke** [comment]
`insight::find_response()` will return `y` for all of such models - do you mean that? or, beside the name of the response variable, if the data is also the same?

**Comment by bwiernik** [comment]
Got it. Okay that works. 

The other thing we would need would be to identify the transformation function applied. Have an idea how to do that effectively?

**Comment by strengejacke** [comment]
What needs to be changed here in wich way?

**Comment by mattansb** [comment]
Hey, I've implemented something similar in my [`MSBMisc` package](https://mattansb.github.io/MSBMisc/reference/logLik_lnorm.html):

``` r
data("mtcars")
mtcars$mpg <- floor(mtcars$mpg)

model_lnorm <- lm(log(mpg) ~ factor(cyl), mtcars)
model_norm <- lm(mpg ~ factor(cyl), mtcars)
model_pois <- glm(mpg ~ factor(cyl), mtcars, family = poisson())

# No, that first one is wrong...
(aics <- AIC(model_lnorm, model_norm, model_pois))
#>             df       AIC
#> model_lnorm  4 -19.67061
#> model_norm   4 170.87527
#> model_pois   3 173.59104

aics[1, "AIC"] <- MSBMisc::AIC_lnorm(model_lnorm)
aics # better!
#>             df      AIC
#> model_lnorm  4 168.3652
#> model_norm   4 170.8753
#> model_pois   3 173.5910
```

However it doesn’t give the exact same results - I use `dlnorm()` directly:

``` r
AIC(model_lnorm) + 2 * sum(log(insight::get_response(model_lnorm)))
#> [1] 168.2152
MSBMisc::AIC_lnorm(model_lnorm)
#> [1] 168.3652
```

<sup>Created on 2021-12-26 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by bwiernik** [comment]
At first glance I would assume the dlnorm is more correct. The alternative is a Taylor series approximation.

**Comment by strengejacke** [comment]
> What needs to be changed here in wich way?

**Comment by mattansb** [comment]
We need to 
1. Detect a transformed outcome
2. Compute the relevant Jacobian
3. Multiply the AIC by the Jacobian to get the adjusted AIC.

**Comment by bwiernik** [comment]
For log() transforms specifically, let's use Mattan's fucntion he linked to. For other trabsforms, we would use numericDeriv() to compute the Jacobian

https://stat.ethz.ch/R-manual/R-devel/library/stats/html/numericDeriv.html

numDeriv::numDeriv() is easier to use if we can accept the soft dependency

**Comment by strengejacke** [comment]
I'm not sure what Jacobian means here, I always thought it's a kind of matrix used for marginal effects.

**Comment by strengejacke** [comment]
``` r
library(performance)
data("mtcars")
mtcars$mpg <- floor(mtcars$mpg)

model_lnorm <- lm(log(mpg) ~ factor(cyl), mtcars)
model_norm <- lm(mpg ~ factor(cyl), mtcars)
model_pois <- glm(mpg ~ factor(cyl), mtcars, family = poisson())

performance_aic(model_lnorm)
#> [1] 168.3652
performance_aic(model_norm)
#> [1] 170.8753
performance_aic(model_pois)
#> [1] 173.591
```

<sup>Created on 2022-02-26 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by strengejacke** [comment]
I think all we need is to add the computation for other response-transformations than log here:

https://github.com/easystats/performance/blob/022d7498eef5f1f8896151bb743a89092dfaf50b/R/performance_aicc.R#L207

`.aic_transformed_response()` should return the final AIC value. If this function fails, this is taken care of in `performance_aic.default()`, which yields a warning and tries to compute the normal AIC instead.

**Comment by mattansb** [comment]
Note that my function doesn't support weights or REML, so (unless someone can generalize it) I suggest we use the Jacobian approximation in those cases?

(I also have no idea what a Jacobian is here... 🤷‍♂️🤓)

**Comment by bwiernik** [comment]
The Jacobian is just derivative of the function. That what we get from numericDeriv()

**Comment by strengejacke** [comment]
> Note that my function doesn't support weights or REML, so (unless someone can generalize it) I suggest we use the Jacobian approximation in those cases?

I'm not sure what the correct way would be... I'll pass this over to you to add/modify the code I startet working on :-)

**Comment by strengejacke** [comment]
I don't know how to use `numericDeriv()` on a transformed response (like `sqrt(y)`). And I'm not sure what to do with that numeric derivation? How does this translate into a logLik?

**Comment by strengejacke** [comment]
``` r
data("mtcars")
mtcars$mpg <- floor(mtcars$mpg)

m1 <- lm(sqrt(mpg) ~ factor(cyl), mtcars)
m2 <- lm(mpg ~ factor(cyl), mtcars)

logLik(m1)
#> 'log Lik.' -10.74082 (df=4)
logLik(m2)
#> 'log Lik.' -81.43763 (df=4)

AIC(m1, m2)
#>    df       AIC
#> m1  4  29.48165
#> m2  4 170.87527
```

<sup>Created on 2022-02-28 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by bwiernik** [comment]
``` r
m1 <- lm(disp ~ hp, data = mtcars)
m2 <- lm(log(disp) ~ hp, data = mtcars)
m3 <- lm(log(disp) ~ log(hp), data = mtcars)

ic_jacobian_adjustment <- function(model) {
  trans <- insight::get_transformation(model)$transformation
  adjust <- sum(log(
      diag(attr(with(
        insight::get_data(model),
        numericDeriv(
          expr = quote(trans(
            get(insight::find_response(model))
          )),
          theta = insight::find_response(model)
        )
      ), "gradient"))
  ))
  - 2 * adjust
}

AIC(m1, m2, m3) |> 
  dplyr::mutate(
    AICadj = AIC + sapply(list(m1, m2, m3), ic_jacobian_adjustment)
  )
#>    df       AIC   AICadj
#> m1  3 372.82473 372.8247
#> m2  3  28.84773 367.0772
#> m3  3  18.40596 356.6354
```

<sup>Created on 2022-02-28 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by strengejacke** [comment]
Is this adjustment only valid for AIC, or also for loglikelihood in general? If the latter, we could add that feature to `test_likelihoodratio()` as well.

**Comment by strengejacke** [comment]
So I could do `LL+ sapply(list(m1, m2, m3), ic_jacobian_adjustment)` to get corrected loglikelihood?

**Comment by bwiernik** [comment]
Delete the -2 from the function of applying directly to the LL

**Comment by bwiernik** [comment]
@strengejacke You can get rid of the special treatment of log() -- this function can apply to anything (including no transformation). 

For simplicity, let's make the internal function `.loglik_adjust_jacobian()`

One argument (the model). Just return the adjustment (no aic or -2). Then that function can be used to adjust logLik, LRT, or elpd performance directly, or any IC (LOOIC, BIC, AIC, WAIC, AICc) by multiplying by -2

**Comment by strengejacke** [comment]
> You can get rid of the special treatment of log() 

I thought we wanted to use `dlnorm()` specifically for log, and the derivative for the others?

**Comment by bwiernik** [comment]
I was thinking per Mattan:

> Note that my function doesn't support weights or REML, so (unless someone can generalize it) I suggest we use the Jacobian approximation in those cases?

But thinking about it, need to check those for the Jacobian case anyway. So let's leave as is for log() for now. 

Note that my comment about making the fucntion .loglik_adjust_jacobian() above still applies

**Comment by strengejacke** [comment]
Yeah, I have changed the functions. However, I'm not sure in which places we could use these functions. Note that for `test_lrt()`, I use the new `check_response` argument in `insight::get_loglikelihood()`, which applies the Jacobian adjustment if needed, so we don't need to revise `test_lrt()` here.

**Comment by bwiernik** [comment]
Great!

In `insight::get_loglikelihood()`, it's adding `.loglik_adjust_jacobian(mod)`, right?

Then in IC functions where we call `insight::get_loglikelihood()`, we are good. 

In other IC functions, we need to add `-2 * .loglik_adjust_jacobian(mod)` like being done with AIC already. I don't think we report `elpd` anywhere (just LOOIC), but in that case we would need to add just `.loglik_adjust_jacobian(mod)`

**Comment by strengejacke** [comment]
Let me summarize the latest changes.

## insight

In _insight_, we either call the dlnorm-transformation for log-response, and Jacobian for others:

```r
.ll_log_adjustment <- function(x) {
  tryCatch(
    {
      sum(stats::dlnorm(
        x = get_response(x),
        meanlog = stats::fitted(x),
        sdlog = get_sigma(x, ci = NULL, verbose = FALSE),
        log = TRUE
      ))
    },
    error = function(e) {
      NULL
    }
  )
}

.ll_jacobian_adjustment <- function(model) {
  tryCatch(
    {
      trans <- get_transformation(model)$transformation
      sum(log(
        diag(attr(with(
          get_data(model),
          stats::numericDeriv(
            expr = quote(trans(
              get(find_response(model))
            )),
            theta = find_response(model)
          )
        ), "gradient"))
      ))
    },
    error = function(e) {
      NULL
    }
  )
}
```

(https://github.com/easystats/insight/blob/c2e9c4a2c9754f9fe59c9d3e9cdaa8376723b915/R/get_loglikelihood.R#L347-L384)

Every `get_loglikelihood()` method calls `.loglikelihood_prep_output()`, where we have following code:

```r
  if (isTRUE(check_response)) {
    # check if we have transformed response, and if so, adjust LogLik
    response_transform <- find_transformation(x)
    if (!is.null(response_transform) && !identical(response_transform, "identity")) {
      ll_transform <- switch(
        response_transform,
        "log" = .ll_log_adjustment(x),
        .ll_jacobian_adjustment(x)
      )

      if (is.null(ll_transform) && isTRUE(verbose)) {
        warning(insight::format_message("Could not compute corrected log-likelihood for models with transformed response. Log-likelihood value is probably inaccurate."), call. = FALSE)
      } else {
        out[1] <- ll_transform
      }
    }
  }
```


## performance

In _performance_, we have 4 helper-functions:

- `adjust_aic()`, which only applies to AIC and either uses the dlnorm- or Jacobian approach
- `adjust_aic_dlnorm()`, only used in `adjust_aic()`
- `adjust_loglik_jacobian()`, which only adjusts the loglikelihood
- `adjust_ic_jacobian()`, which is used in most AIC(c) and BIC functions, which requires the model object and IC value, internally calls `adjust_loglik_jacobian()` on the model and then adjusts the IC (`ic <- ic - 2 * adjustment`).

```r
# jacobian / derivate for log models and other transformations ----------------

# this function adjusts any IC for models with transformed response variables
.adjust_ic_jacobian <- function(model, ic) {
  response_transform <- insight::find_transformation(model)
  if (!is.null(ic) && !is.null(response_transform) && !identical(response_transform, "identity")) {
    adjustment <- tryCatch(.adjust_loglik_jacobian(model), error = function(e) NULL)
    if (!is.null(adjustment)) {
      ic <- ic - 2 * adjustment
    }
  }
  ic
}

# this function adjusts the AIC, either dlnorm for log, or Jacobian for other transformations
.adjust_aic <- function(x, response_transform, aic = NULL, ...) {
  if (response_transform == "log") {
    aic <- .adjust_aic_dlnorm(x)
  } else {
    aic <- aic - 2 * .adjust_loglik_jacobian(x)
  }
  aic
}

# this function adjusts the AIC, based on dlnorm() log-likelihood adjustment
.adjust_aic_dlnorm <- function(model) {
  # loglik-transformation. first try, we use dlnorm()
  aic <- tryCatch(
    {
      ll <- insight::get_loglikelihood(model)
      ll[1] <- sum(stats::dlnorm(
        x = insight::get_response(model),
        meanlog = stats::fitted(model),
        sdlog = insight::get_sigma(model, ci = NULL, verbose = FALSE),
        log = TRUE
      ))
      stats::AIC(ll)
    },
    error = function(e) {
      NULL
    }
  )

  # if this does not work for some reason, use slightly less accurate approach
  if (is.null(aic)) {
    aic <- stats::AIC(model) + 2 * sum(log(insight::get_response(model)))
  }

  aic
}

# this function just adjusts the log-likelihood of a model
.adjust_loglik_jacobian <- function(model) {
  trans <- insight::get_transformation(model)$transformation
  sum(log(
    diag(attr(with(
      insight::get_data(model),
      stats::numericDeriv(
        expr = quote(trans(
          get(insight::find_response(model))
        )),
        theta = insight::find_response(model)
      )
    ), "gradient"))
  ))
}
```

(https://github.com/easystats/performance/blob/f841500b88e7e0a1470755f951b5dc1d74c3fb77/R/performance_aicc.R#L225-L294)

(Most) functions that compute the AIC, BIC or AICc just have a call to `adjust_ic_jacobian(model, ic)` at the end, to adjust the related IC value. This follows your suggestion above.

## performance - tests

Currently, `test_likelihoodratio()` is the only test that used adjusted loglikelihoods, by calling `insight::get_loglikelihood(check_response = TRUE)`:

```r
    lls <- sapply(objects, insight::get_loglikelihood, check_response = TRUE)
```

https://github.com/easystats/performance/blob/f841500b88e7e0a1470755f951b5dc1d74c3fb77/R/test_likelihoodratio.R#L71

## summary

- AIC, AICc and BIC are covered - with some exception, where I was not yet sure what kind of AIC the function returns (see `performance_aic.vgam()`).
- `test_lrt()` is covered

We still need to decide whether we _only_ want to rely on the Jacobian transformation, or also keep the dlnorm-approach.

**Comment by mattansb** [comment]
If `insight::get_loglikelihood()` returns an object of class `logLik`, AIC and BIC can be computed simply as:

- `AIC(insight::get_loglikelihood(model))`
- `BIC(insight::get_loglikelihood(model))`

---

@bwiernik How does your Jacobian function deal with weighting? If it can deal with it, I suggest dropping the direct `dlnorm` method - generalizability is exchange for precision.

**Comment by bwiernik** [comment]
It does not currently handle weights or REML.

**Comment by strengejacke** [comment]
> If insight::get_loglikelihood() returns an object of class logLik, AIC and BIC can be computed simply as

So, we could simplify it to just having one `performance_aic()` method:

```r
performance_aic <- function(x, ...) {
  stats::AIC(insight::get_loglikelihood(x, check_response = TRUE))
}
```

?

**Comment by bwiernik** [comment]
It does not currently. 

@strengejacke It can handle weights if we replace `sum()` with a weighted sum. 

```r
.weighted_sum <- function(x, w, ...) {
  if (missing(w) || is.null(w)) {
    stats::weighted.mean(x, ...) * length(x)
  } else {
    stats::weighted.mean(x, w, ...) * length(x)
  }
}
```

It doesn't currently handle REML either, but you shouldn't do model comparison for REML models anyway (do we refit mixed models in compare_performance() like lme4 and glmmTMB do in anova()?). 

The same dlnorm logic could also apply to BIC and to AICc (assuming that the transformed data follow a normal likelihood). This isn't specific to AIC (either dlnorm or jacobian are drop-in replacements for the LL). 

It would similarly apply to WAIC. LOOIC would need some more handling of the PSIS weights. We can probably defer adjusting those in performance() / compare_performance() for now. 

We could also add weights to the dlnorm function (multiplying each dlnorm() result by the normalized model weights), but might be easier at that point to just use the jacobian.

**Comment by strengejacke** [comment]
weights refer to model weights in this case, right?

**Comment by bwiernik** [comment]
Yep, get_weights(). The weighted sum function there is designed to accept a NULL result from get_weights()

**Comment by strengejacke** [comment]
If we always use the Jacobian function, we have following differences between the two approaches (dlnorm vs. Jacobian)

```r
# loglik = -80
lm(mpg ~ wt, data = mtcars) 

# loglik = -75 for dlnorm
lm(log(mpg) ~ wt, data = mtcars) 

# loglik = -90 for jacobian
lm(log(mpg) ~ wt, data = mtcars) 
```

We still might rely on the dlnorm function, unless we have weights. Or should we completely rely on the Jacobian method and drop the dlnorm-method?

**Comment by strengejacke** [comment]
> If `insight::get_loglikelihood()` returns an object of class `logLik`, AIC and BIC can be computed simply as:
> 
> * `AIC(insight::get_loglikelihood(model))`
> * `BIC(insight::get_loglikelihood(model))`

That doesn't seem to return the same results:

``` r
m2 <- lm(sqrt(disp) ~ hp, data = mtcars)
performance:::.adjust_ic_jacobian(m2, AIC(m2))
#> [1] 367.1239
AIC(insight::get_loglikelihood(m2, check_response = TRUE))
#> [1] 219.4762
```

<sup>Created on 2022-03-01 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by strengejacke** [comment]
Yeah, but those functions do the same thing (AIC from adjusted LL). Before, we had the approach suggested by @bwiernik where we had the "raw" (unadjusted) AIC - 2 * adjusted LL.

``` r
m2 <- lm(sqrt(disp) ~ hp, data = mtcars)

ll <- logLik(m2)
ll[1] <- performance:::.adjust_loglik_jacobian(m2) # adjust
AIC(ll)
#> [1] 219.4762

AIC(insight::get_loglikelihood(m2, check_response = TRUE))
#> [1] 219.4762


AIC(m2) - 2 * performance:::.adjust_loglik_jacobian(m2)
#> [1] 367.1239

# which is close to 
m1 <- lm(disp ~ hp, data = mtcars)
AIC(m1)
#> [1] 372.8247
```

<sup>Created on 2022-03-01 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by strengejacke** [comment]
(see https://github.com/easystats/performance/issues/372#issuecomment-1054227487)

**Comment by strengejacke** [comment]
So the question is whether we use `AIC(adjusted-logLik)` or `AIC(model) - 2 * adjusted_logLik`.

**Comment by bwiernik** [comment]
I'll take a look. Are these on the master branch now?

**Comment by strengejacke** [comment]
Yes. But it's mainly the question posed here: https://github.com/easystats/performance/issues/372#issuecomment-1055517906

Should we use AIC(adjusted_logLik(mpodel)) or AIC(model) - 2 * adjusted_logLik(model)?

**Comment by bwiernik** [comment]
The issue is that you need to add the results of `.adjust_loglik_jacobian(m2)` to the existing logLik value. `.adjust_loglik_jacobian()` just returns the adjustment itself.

```r
ll <- logLik(m2)
ll[1] <- ll[1] + .adjust_loglik_jacobian(m2) # adjust
AIC(ll)
#> [1] 367.1239
```

`insight::get_loglikelihood()` needs to be updated accordingly

**Comment by bwiernik** [comment]
Sorry the function name wasn't the clearest

**Comment by strengejacke** [comment]
Ah, got it! I think part of my confusion was that for @mattansb approach, the ll was indeed _replaced_, while for the Jacobian, we need to _add_ to the ll.

**Comment by strengejacke** [comment]
ok, _should_ work now.
