### ISSUE TITLE
`check_zeroinflation()` for `lme4::glmer.nb()`model

### ISSUE THREAD

**Issue by maxsitt** [easystats/performance#381]
Currently the function `check_zeroinflation()` is not working for a mixed model with negative binomial distribution, fitted with `lme4::glmer.nb()`.
Error message: `Error: $ operator not defined for this S4 class`

`glmer.nb()` is not mentioned as supported model class in the function reference, so this might be a already known problem.
I would be interested in the reason why it is not possible to include `glmer.nb()` as model class for `check_zeroinflation()`.
Is there maybe a simple workaround to still check for zero-inflation in `glmer.nb()` models with one of the easystats tools?

Thank you for your answer!

**Comment by strengejacke** [comment]
Thanks, fixed in the GitHub version of _performance_.
