### ISSUE TITLE
REML vs ML

### ISSUE THREAD

**Issue by strengejacke** [easystats/performance#393]
Origin is the discussion here: https://github.com/easystats/performance/issues/372#issuecomment-1055245788

In `insight::get_loglikelihood()`, we can either return the LL based on REML or ML fit. For comparison, usually the ML fit makes more sense (see `anova.merMod()`, where input is re-fitted when comparing multiple models).

In _performance_, `performance_aic()`, `model_performance()` or `compare_performance()` set `estimator = "ML"` by default, thus, all AIC(c) values are based on ML fits by default (unlike `AIC.merMod()`, which returns the REML AIC by default). And `test_lrt()` always uses `estimator = "ML"`, so it returns the "correct" LRT test results.

My question is, should we preserve the same defaults in  `performance_aic()`, `model_performance()` or `compare_performance()` as _lme4_, i.e. return `AIC(REML = TRUE)` by default (instead of current behaviour, `AIC(REML = FALSE)`)?

Note this only applies to linear models (lmer), not glmer.

@bwiernik @mattansb @DominiqueMakowski

**Comment by mattansb** [comment]
Odd that `anova` refits to ML, but AIC does not.

What I was taught was that model comparisons where there are only differences in random effects should be done with REML, all other cases with ML (which makes the `anova` behavior quite annoying...).... So not sure what a good default is here...

**Comment by strengejacke** [comment]
Or we stick with the "usual" defaults for `performance_aic()` and `get_loglikelihood()`, and only for `test_lrt()` and `compare_performance()` we use ML AIC (instead of REML).

**Comment by strengejacke** [comment]
This discussion might be of interest, too: https://github.com/glmmTMB/glmmTMB/issues/686

Maybe, if @bbolker finds some time, he could has a suggestion?

The main issue is: should functions like `get_loglikelihood()` (returns logLik) or `performance_aic()` (returns AIC) by default 
1. set `REML` to FALSE
2. or stick to the defaults as in the "original packages" (e.g. REML=TRUE for input models from lme4), so `get_loglikelihood()` equals `logLik()` and `performance_aic()` equals `AIC()`

For `test_likelihoodratio()`, we already check if models are nested, and _always_ default REML to FALSE when doing a LRTR - however, for models that only differ in their random effects, we could set REML to TRUE.

**Comment by bwiernik** [comment]
The major consideration of REML vs ML for model comparison is whether the models have the same fixed effects or not. Can you add that info as well?

**Comment by DominiqueMakowski** [comment]
I don't understand that well enough to have a relevant opinion here 😕

**Comment by strengejacke** [comment]
> The major consideration of REML vs ML for model comparison is whether the models have the same fixed effects or not. Can you add that info as well?

I think for `test_*()` and `compare_performance()`, we're set. But what about the defaults when not comparing models? See https://github.com/easystats/performance/issues/393#issuecomment-1057784133

**Comment by mattansb** [comment]
When not comparing, we should default to the fitted model (if it was fitted with REML, give REML...)

**Comment by mattansb** [comment]
I hate `lme4`'s `Refitting model.....` message..........

**Comment by bbolker** [comment]
@mattansb you could post an issue for `lme4` (explain what you hate about the message/why we should change it) ...

**Comment by strengejacke** [comment]
> explain what you hate about the message

Don't worry, this is just the uncontrolled anger of a young man. ;-)

**Comment by mattansb** [comment]
@bbolker I just dislike that if I fit two models with REML, the default is to overwrite my choice when comparing them 🤷‍♂️
But as Daniel said - I'm just an [angry young man](https://www.youtube.com/watch?v=M2iNLt_hUZg) :P

**Comment by strengejacke** [comment]
> @mattansb you could post an issue for `lme4` (explain what you hate about the message/why we should change it) ...

I think in general it's a good message/action, because from my experience, there are quite some users that know that comparison with `anova()` is useful, but they don't know that a comparison is not valid when `REML = TRUE`. However, `anova.merMod()` also yields this warning for models with same fixed effects, so maybe the message/action could be modified? Automatic refitting with ML when fixed effects are different, else - when all input models share the same fixed effects - yield a warning that model comparison with REML fit might return inaccurate results?

**Comment by bbolker** [comment]
Let's continue the discussion [here](https://github.com/lme4/lme4/issues/141).

**Comment by strengejacke** [comment]
I think we can close this. `compare_performance()` defaults `estimator` to `"ML"`, and gives a warning for `estimator = "REML"` when models don't have the same fixed effects. `test_likelihoodratio()` chooses the default estimator based on the model characteristics, i.e. defaults to ML, or to REML _if_ all models are linear mixed effects model with same fixed effects. `performance_aic()` mimics the default behaviour of `AIC()`.

**Comment by strengejacke** [comment]
You can set `verbose = FALSE` in the call to `ellipses_info()` if you want to get rid of the warning "Some of the nested models seem to be identical".

**Comment by DominiqueMakowski** [comment]
> Some of the nested models seem to be identical and probably only vary in their random effects.

Could we add a few words about what it means for the user; is the comparison likely to be meaningless? invalid? Should they take any actions?

**Comment by strengejacke** [comment]
I think this is already done in `compare_performance()` and the `test_*()` functions, i.e. additional warnings/messages appear *if* the user could do something unintended / stupid. Furthermore, I added more background to the docs about when comparing is appropriate and where not.
