### ISSUE TITLE
Documentation for `check_model()`

### ISSUE THREAD

**Issue by strengejacke** [easystats/performance#395]
@bwiernik @IndrajeetPatil @DominiqueMakowski @mattansb I think a very common question is how to interprete these plots. We already have some more details in the docs, but probably we should provide some guidelines about the meaning of these plots in the docs:

https://easystats.github.io/performance/reference/check_model.html

_Originally posted by @strengejacke in https://github.com/easystats/see/issues/211#issuecomment-1056397023_

**Comment by bwiernik** [comment]
We should split the docs up by model type like with parameters

**Comment by strengejacke** [comment]
Maybe:

1. Generic plots (seen for all model types)
2. specific plots linear/...
3. specific plots glm/...
4. specific plots mixed models/...

?

There is some overlap between those types.

**Comment by mattansb** [comment]
I think perhaps a vignette would be better than r-docs, what do you think? With a section for linear, count, binomial, mixed, etc...

**Comment by bwiernik** [comment]
I would prefer them to be organized around model type, rather than type of plot, because the same plot might be used for different things for different models (eg, a scale-location plot is used to check homogeneity in a linear model, but overdispersion in a count model)

**Comment by strengejacke** [comment]
ok, makes sense.

**Comment by strengejacke** [comment]
Anyone who is willing to make a first draft?

**Comment by strengejacke** [comment]
(bump)

**Comment by bwiernik** [comment]
Will start on it this weekend

**Comment by strengejacke** [comment]
I'd like to submit _performance_ soon, do you think we can add some stuff to the docs?

**Comment by bwiernik** [comment]
I'm writing a draft of this vignette on my flight today.

**Comment by IndrajeetPatil** [comment]
*bump*

**Comment by IndrajeetPatil** [comment]
*bump*

**Comment by strengejacke** [comment]
I hope you landed safely, Brenton. :-D
Can you look at https://easystats.github.io/performance/reference/check_model.html and maybe add/revise there? It's probably faster for now than writing a whole vignette.
