### ISSUE TITLE
Remove internal `.factor_to_numeric()` helper?

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/performance#397]
We have `factor` method for `data_to_numeric` generic in datawizard:
https://easystats.github.io/datawizard/reference/convert_data_to_numeric.html

Can it be used instead of this internal helper? Or this helper has a different logic to it?

https://github.com/easystats/performance/blob/ed1a3984fb0823680956cdb5258cb95e6df06a47/R/helpers.R#L74-L108

**Comment by strengejacke** [comment]
No, they behave differently. `data_to_numeric()` does not preserve numeric factor levels:

``` r
datawizard::convert_data_to_numeric(as.factor(mtcars$gear), dummy_factors = FALSE)
#>  [1] 2 2 2 1 1 1 1 2 2 2 2 1 1 1 1 1 1 2 2 2 1 1 1 1 1 2 3 3 3 3 3 2
performance:::.factor_to_numeric(as.factor(mtcars$gear))
#>  [1] 4 4 4 3 3 3 3 4 4 4 4 3 3 3 3 3 3 4 4 4 3 3 3 3 3 4 5 5 5 5 5 4
```

<sup>Created on 2022-03-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by IndrajeetPatil** [comment]
So instead of having two copies, should we add a new argument `preserve_levels` to `data_to_numeric.factor()`, and use that function instead?

**Comment by strengejacke** [comment]
yes, sounds good!

**Comment by strengejacke** [comment]
And probably a `lowest_value` or `start_value` argument as well.

**Comment by strengejacke** [comment]
Some function require the response of logistic regression to be 0/1:

``` r
mtcars$vs <- as.factor(mtcars$vs)
model <- glm(vs ~ wt + mpg, data = mtcars, family = "binomial")

datawizard::convert_data_to_numeric(insight::get_response(model), dummy_factors = FALSE)
#>  [1] 1 1 2 2 1 2 1 2 2 2 2 1 1 1 1 1 1 2 2 2 2 1 1 1 1 2 1 2 1 1 1 2
performance:::.factor_to_numeric(insight::get_response(model), lowest = 0)
#>  [1] 0 0 1 1 0 1 0 1 1 1 1 0 0 0 0 0 0 1 1 1 1 0 0 0 0 1 0 1 0 0 0 1
```

<sup>Created on 2022-03-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by IndrajeetPatil** [comment]
Thanks! I have created an issue in `{datawizard}` to track this.

**Comment by strengejacke** [comment]
There's one more difference, though I'm not sure if the default behaviour of `data_to_numeric()` is better here. Be we could have an argument for this, too:

``` r
x <- factor(c("a", "b", "d"), levels = letters[1:4])
x
#> [1] a b d
#> Levels: a b c d

datawizard::convert_data_to_numeric(x, dummy_factors = FALSE)
#> [1] 1 2 4
performance:::.factor_to_numeric(x)
#> [1] 1 2 3
```

<sup>Created on 2022-03-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by strengejacke** [comment]
ok, so you now have the edge cases for testing ;-)

**Comment by strengejacke** [comment]
putting this on-hold until it's finished in _datawizard_ (and on CRAN)

**Comment by IndrajeetPatil** [comment]
Note to self: Also remove the copy in _performance_

https://github.com/easystats/performance/blob/beafaa04c5735199ddbce0a3da36c8f85580e268/R/helpers.R#L46-L98

**Comment by IndrajeetPatil** [comment]
Note to self: Do the same for _parameters_

https://github.com/easystats/parameters/blob/186473140805c8dc2804f508698a7897e246beb9/R/utils.R#L10-L80
