### ISSUE TITLE
More informative error for Bernoulli models in `check_overdispersion`

### ISSUE THREAD

**Issue by mattansb** [easystats/performance#398]
``` r
library(performance)

m <- glm(am ~ hp, mtcars, family = binomial())

check_overdispersion(m)
#> Error: Model is not allowed to be a Bernoulli model.
```

<sup>Created on 2022-03-06 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

A novice user might interpreted this error as a violation of the assumption.

**Comment by bwiernik** [comment]
@strengejacke For clarity can we say "Poisson families or binomial families with trials > 1" ?
