### ISSUE TITLE
ranking of models and indices differences

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/performance#40]
This is an extension of #28

 It would indeed be interesting to either have a separate function (e.g., `rank_models`), or an argument in `compare_models` (e.g., `show_ranks`), to "rank" the models, i.e., displaying "the best" at the top, and then the following, which indices could be displayed in terms of difference with the best model. 

This presents several challenges:

- encoding somewhere the directionality of each index (for instance, for R2 the bigger the better, whereas for AIC the smaller the better). 
- finding some sort of unique index of "best" model, for instance, the ratio of higher indices (as these are not always congruent). For instance, model 2 can have 4 out of 6 indices placing it as the best.
- dealing with edge cases: what to do in the case of equality, etc.
- some indices can be compared through NH testing, resulting in a p-value. What to do in these cases?

**Comment by strengejacke** [comment]
Isn't this what probably could also be done with LRT, like in `anova()`? Or do you have something else in mind? Or maybe something that goes a bit beyong `anova()`-LRT?

**Comment by DominiqueMakowski** [comment]
What do you mean by LRT? Well `anova()` can eventually compare certain types of models, but it's very narrow. I was thinking more of an "agnostic" method (i.e., that doesn't compute any specific index or tests) that would just take all the indices, order them so that we can later arrange the models based on one or multiple indices. 

To put it differently, we could currently add an argument to `compare_models` that would run under the hood something similar to `arrange(AIC, BIC, desc(R2))` etc. for all indices.

However, for this we have to prioritize the indices (in the previous example, AIC is the main index used for ranking the models). I was thinking about adding a composite meta-index, that could be for instance the mean of individual ranks of indices, and then arrange the models by this value. For example, Model1 is ranked `1` (i.e., the best) for AIC, BIC, but `2` for R2 (i.e., has the second best R2). Thus, his "meta" index of performance would be `1+1+2/3=1.33`.

**Comment by strengejacke** [comment]
LRT is a likelihood-ratio-test, to check if a model A is significantly better compared to a model B. But yes, the approach desribed by you would be different from  `anova()`, and maybe a good extension.

**Comment by strengejacke** [comment]
We can probably add a plot-method for `compare_models()`, based on the radarplot shown in this PDF:
https://journal.r-project.org/archive/2019/RJ-2019-036/RJ-2019-036.pdf (page 7)

We have the radarplot-function already in the see-package.

**Comment by DominiqueMakowski** [comment]
Very good idea!

**Comment by strengejacke** [comment]
``` r
library(easystats)
#> # Attaching packages
#> <U+2714> insight     0.7.0.1   <U+2714> bayestestR  0.4.0.1
#> <U+2714> performance 0.4.0.1   <U+2714> parameters  0.3.0  
#> <U+2714> see         0.3.0.1   <U+2714> effectsize  0.0.1  
#> <U+2714> correlation 0.1.0     <U+2714> estimate    0.1.0  
#> <U+2714> report      0.1.0
data(iris)
lm1 <- lm(Sepal.Length ~ Species, data = iris)
lm2 <- lm(Sepal.Length ~ Species + Petal.Length, data = iris)
lm3 <- lm(Sepal.Length ~ Species * Petal.Length, data = iris)
x <- compare_performance(lm1, lm2, lm3)

plot(x)
```

![](https://i.imgur.com/JOZ1jbq.png)

<sup>Created on 2019-11-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by strengejacke** [comment]
``` r
library(easystats)
#> # Attaching packages
#> <U+2714> insight     0.7.0.1   <U+2714> bayestestR  0.4.0.1
#> <U+2714> performance 0.4.0.1   <U+2714> parameters  0.3.0  
#> <U+2714> see         0.3.0.1   <U+2714> effectsize  0.0.1  
#> <U+2714> correlation 0.1.0     <U+2714> estimate    0.1.0  
#> <U+2714> report      0.1.0
data(iris)
lm1 <- lm(Sepal.Length ~ Species, data = iris)
lm2 <- lm(Sepal.Length ~ Species + Petal.Length, data = iris)
lm3 <- lm(Sepal.Length ~ Species * Petal.Length, data = iris)
x <- compare_performance(lm1, lm2, lm3)

plot(x)
```

![](https://i.imgur.com/DsZSfwQ.png)

<sup>Created on 2019-11-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by strengejacke** [comment]
Maybe not the best solution, but the only downside I currently see is that all indices are equally "weighted". I think for the beginning this is quite OK.

``` r
library(easystats)
data(iris)
lm1 <- lm(Sepal.Length ~ Species, data = iris)
lm2 <- lm(Sepal.Length ~ Species + Petal.Length, data = iris)
lm3 <- lm(Sepal.Length ~ Species * Petal.Length, data = iris)
compare_performance(lm1, lm2, lm3, rank = TRUE)
#> # Comparison of Model Performance Indices
#> 
#>  Model Type     AIC     BIC    R2 R2_adjusted  RMSE           BF
#>    lm2   lm 106.233 121.286 0.837       0.833 0.333 3.445528e+26
#>    lm3   lm 106.767 127.842 0.840       0.835 0.330 1.299196e+25
#>    lm1   lm 231.452 243.494 0.619       0.614 0.510           NA
#>  Performance_Score
#>             99.25%
#>             83.00%
#>              0.00%
#> 
#> Model lm2 (of class lm) performed best with an overall performance score of 99.25%.
```

<sup>Created on 2019-11-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by strengejacke** [comment]
@DominiqueMakowski @mattansb Do you think this "ranking" index makes sense? Approach similar to what has been suggested here: https://github.com/easystats/performance/issues/40#issuecomment-486588618

I normalize all indices, so they all (includig AIC, BIC of BF) range between 0 to 1. Then I calculate the mean of all indices per model (which again is between 0 to 1) and that's the "rank-index". A value of "1" means that the model has a "100% performance score", which means that this model performed best in all indices.

Dominique suggested using the mean by order of models, i.e. for each indice, a model gets a value from 1 to number of compared models, based on the models ranking for this index. Example R2: m1 has r2 of .8, m2 has r2 of .6 and m3 has r2 of .1. Then, according to the ranking, following points are given: m1 = 1, m2 = 2 and m3 = 3. As you can see, the models are equally "weighted". Using normalize, the models would get following points in my approach: m1 = 1, m2 = 0.7143 and m3 = 0. The _order_ is the same, but m1 and m2 are closer to each other, because there r2 are more similar. The same is done for all indices, some are corrected in directions (AIC, BIC and RMSE -> lower = better, so after normalization they are reversed).

**Comment by strengejacke** [comment]
See also [here](https://easystats.github.io/performance/reference/model_performance.html), docs for `rank` and section _Details_.

**Comment by DominiqueMakowski** [comment]
I think this is can be a very useful simplification! 

I'm just wondering if it's better to return, as you say, the ratio of the mean rank (or "normalized" index, between 0 and 1) or directly the mean rank. It seems that the interpretation of the latter (in which a score of let's say **2** could be interpreted as "on average, this model is the second best") is more intuitive, but on the other hand, as it is an unbounded index (depending on the number of trials), I agree that a normalized index is statistically more stable (always between 0 and 1).

**Comment by strengejacke** [comment]
I think the main difference between a "score" (proportion) and a "rank" (mean of ranks) is the different "weighting". Let's take the following example:

Looking at the raw rankings, m1 is 1st for r2 and 2nd for r2_adj, while m2 is 2nd for r2_adj and 1st for r2. On average, they both perform equally well. However, m1 is "more" better in r2 than m2 is "more" better in r2_adj. So I personally would say that m1 is a bit better than m2. And this is reflected by the score.

``` r
library(easystats)
d <- data.frame(
  r2 = c(m1 = .8, m2 = .6, m3 = .1),
  r2_adj = c(m1 = .5, m2 = .55, m3 = .05)
)
d
#>     r2 r2_adj
#> m1 0.8   0.50
#> m2 0.6   0.55
#> m3 0.1   0.05

ranks <- sapply(d, order, decreasing = TRUE)
ranks
#>      r2 r2_adj
#> [1,]  1      2
#> [2,]  2      1
#> [3,]  3      3

setNames(rowMeans(ranks), c("m1", "m2", "m3"))
#>  m1  m2  m3 
#> 1.5 1.5 3.0


score <- round(normalize(d), 3)
score
#>       r2 r2_adj
#> m1 1.000    0.9
#> m2 0.714    1.0
#> m3 0.000    0.0

rowMeans(score)
#>    m1    m2    m3 
#> 0.950 0.857 0.000
```

<sup>Created on 2019-11-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

However, both approaches do _not_ give different importance to the indices, e.g. is R2 more important than AIC? We could think about a `weight`-argument, so the user can weight the indices according to their own judged relevance.

**Comment by DominiqueMakowski** [comment]
Mmh I see, and thus I agree with the score! Will be easy to plot too!

And yes, a 'weight' argument could be easily implementable, although I doubt it'll be often used by people (I mean, you have to have quite a bold opinion to say "okay R2 is 0.8 but BIC only 0.5" 😁)

**Comment by strengejacke** [comment]
> Will be easy to plot too!

The plot is here: https://github.com/easystats/performance/issues/40#issuecomment-557188328
Already implemented in performance and see.

**Comment by strengejacke** [comment]
Ok, function is now also quite verbose in case comparison of ranks is not approprioate.

``` r
library(lme4)
#> Loading required package: Matrix
library(performance)

data(iris)

m2 <- glm(vs ~ wt + mpg, data = mtcars, family = "binomial")
m3 <- lmer(Petal.Length ~ Sepal.Length + (1 | Species), data = iris)
lm1 <- lm(Sepal.Length ~ Species, data = iris)
lm2 <- lm(Sepal.Length ~ Species + Petal.Length, data = iris)
lm3 <- lm(Sepal.Length ~ Species * Petal.Length, data = iris)

compare_performance(lm1, lm2, lm3, m2, m3, rank = TRUE)
#> Warning: When comparing models, please note that probably not all models were
#> fit from same data.
#> Warning: Models are not of same type. Comparison of indices might be not
#> meaningful.
#> Warning: Following indices with missing values are not used for ranking: R2,
#> R2_adjusted, R2_Tjur, LOGLOSS, SCORE_LOG, SCORE_SPHERICAL, PCP, R2_conditional,
#> R2_marginal, ICC
#> # Comparison of Model Performance Indices
#> 
#>  Model    Type     AIC     BIC  RMSE    R2 R2_adjusted R2_Tjur LOGLOSS
#>     m3 lmerMod  77.320  89.362 0.279    NA          NA      NA      NA
#>    lm2      lm 106.233 121.286 0.333 0.837       0.833      NA      NA
#>    lm3      lm 106.767 127.842 0.330 0.840       0.835      NA      NA
#>     m2     glm  31.298  35.695 0.889    NA          NA   0.478   0.395
#>    lm1      lm 231.452 243.494 0.510 0.619       0.614      NA      NA
#>  SCORE_LOG SCORE_SPHERICAL   PCP R2_conditional R2_marginal   ICC
#>         NA              NA    NA          0.972       0.096 0.969
#>         NA              NA    NA             NA          NA    NA
#>         NA              NA    NA             NA          NA    NA
#>    -14.903           0.095 0.743             NA          NA    NA
#>         NA              NA    NA             NA          NA    NA
#>  Performance_Score
#>             83.73%
#>             70.80%
#>             69.87%
#>             66.67%
#>             20.73%
#> 
#> Model m3 (of class lmerMod) performed best with an overall performance score of 83.73%.
```

<sup>Created on 2019-11-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by DominiqueMakowski** [comment]
I know (my team has actually been using it today to prepare a presentation :), but having a unique "composite" index will also allow for more simple visualisations (e.g. bar charts)

**Comment by DominiqueMakowski** [comment]
Awesome! timing is perfect, I'll be using it very soon ☺️

**Comment by strengejacke** [comment]
> I know (my team has actually been using it today to prepare a presentation :), but having a unique "composite" index will also allow for more simple visualisations (e.g. bar charts)

What do you have in mind? A simple bar chart from 0 to 1, for each model, that represents the score?

**Comment by DominiqueMakowski** [comment]
Yes, but this is for people to do if they need it, I don't think it requires a plot method in see (best to do more complicated stuff there such as radar charts)

**Comment by strengejacke** [comment]
We could make a "context sensitive" plot, that differs depending on the `rank` argument. Problem is only that the "worst" model always has zero percent, and nothing is shown:

``` r
library(easystats)
#> # Attaching packages
#> <U+2714> insight     0.7.0.1   <U+2714> bayestestR  0.4.0.1
#> <U+2714> performance 0.4.0.1   <U+2714> parameters  0.3.0  
#> <U+2714> see         0.3.0.1   <U+2714> effectsize  0.0.1  
#> <U+2714> correlation 0.1.0     <U+2714> estimate    0.1.0  
#> <U+2714> report      0.1.0
data(iris)
lm1 <- lm(Sepal.Length ~ Species, data = iris)
lm2 <- lm(Sepal.Length ~ Species + Petal.Length, data = iris)
lm3 <- lm(Sepal.Length ~ Species * Petal.Length, data = iris)

x1 <- compare_performance(lm1, lm2, lm3)
x2 <- compare_performance(lm1, lm2, lm3, rank = TRUE)

plot(x1)
```

![](https://i.imgur.com/AekYiNs.png)

``` r
plot(x2)
```

![](https://i.imgur.com/67A6cvr.png)

<sup>Created on 2019-11-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by strengejacke** [comment]
We might think about not normalizing ranks that are between 0 and 1 anyway, like R2 or so. Than even the worst model gets some points.
