### ISSUE TITLE
Add option to add title to check_model() panel plot

### ISSUE THREAD

**Issue by rempsyc** [easystats/performance#414]
If one wants to check several models at once with e.g. `lapply`, it would be useful to have an optional argument allowing to specify the name of the current variable. Else skimming through the various figures it can be hard to remember the order of the variables in relation to the plot, which might require to go look back at the order of variables specified earlier.

The plot looks like a `ggplot2` object so I have tried adding `ylab` directly but alas it is not actually a `ggplot2` object so it doesn't work. Example:
```r
library(performance)
library(see)
library(ggplot2)

m <- lm(mpg ~ wt + cyl + gear + disp, data = mtcars)
plot.m <- check_model(m)
plot.m + ylab("test")
```
Also tried:
```r
test <- last_plot()
test + ylab("test")
```
And:
```r
plots(test, title = "test")
```
But I am not able to add a title to the plot. Perhaps there is an easy way that I have missed? Is there currently an argument for this?

**Comment by strengejacke** [comment]
Is this sufficient?

**Comment by rempsyc** [comment]
Yes, excellent, thank you.

**Comment by rempsyc** [comment]
Yes, excellent, thank you.
