### ISSUE TITLE
Incorrect plot title with `check_predictions()`

### ISSUE THREAD

**Issue by fweber144** [easystats/performance#416]
It seems like the title in a frequentist predictive check plot needs to be adjusted:
```r
fit <- lm(mpg ~ disp, data = mtcars)
library(performance)
set.seed(439839)
check_predictions(fit, iterations = 5)
```
gives

![freq_pc](https://user-images.githubusercontent.com/55132727/162155992-9a91056d-f135-4a3f-abf4-ef7602ba3a11.png)

where the title reads "Posterior Predictive Check". I'm not sure how you want to label the frequentist equivalent to the Bayesian PPC, but I guess "Posterior Predictive Check" is incorrect in this case.

**Comment by bwiernik** [comment]
It's an appropriate name even in a frequentist model.

**Comment by fweber144** [comment]
Of course, strictly speaking yes (if you understand "posterior" just as "after seeing the data"). But I still find it misleading because in my experience, the term "posterior predictive check" is associated with a Bayesian analysis. But I might just not have worked enough with these kinds of checks in a frequentist framework. Anyway, this decision is up to you and you can close this issue if you like. I just thought this plot title was not intentioned.

**Comment by bwiernik** [comment]
Ah, yes, it's intentional. It's a frequentist posterior predictive distribution. Both frameworks can yield distributional inference. This is a great treatise on frequentist distributional inference https://www.uio.no/studier/emner/matnat/math/STK4180/v16/clp_oct2015_pages1to205.pdf

**Comment by fweber144** [comment]
Ah ok, I didn't know this was an established term in a frequentist setting. Thank you for the information. Closing now.
