### ISSUE TITLE
check_model() error

### ISSUE THREAD

**Issue by Dallak** [easystats/performance#419]
Hi,

I'm running into this issue when running `check_model(m1)`. It returns:

Error in data.frame(..., check.names = FALSE) : 
  arguments imply differing number of rows: 1772, 1777

Could you please provide some guidance?
Many thanks,

**Comment by DominiqueMakowski** [comment]
Hi, do you have a reproducible example for us to debug?

**Comment by strengejacke** [comment]
(closed wrong issue)

**Comment by strengejacke** [comment]
_bump_ - what kind of model did you use? Do you have a small reprex?

**Comment by Dallak** [comment]
Sorry not sure why I did not get a notification about your replies until now!
This was a while ago and I guess it was solved, but I'll keep an eye out for it and update you with a reprex if it occurs again.
Thank you for your concerns!
