### ISSUE TITLE
[Proposal] Do you plan to support the gls and lme models (nlme)?

### ISSUE THREAD

**Issue by hugesingleton** [easystats/performance#420]
As in the topic. General linear models fit via generalized least square play central role in the pharmaceutical industry - so called MMRM models. They are even more popular than the mixed models in this field. GLS accounts naturally for heteroscedasticity, but the residuals, multicollinearity, outliers, etc. are still important to investigate.

**Comment by strengejacke** [comment]
Should work with the latest commit, despite that not all plot types are included.

``` r
library(performance)
library(nlme)

data(Ovary)
m1 <- gls(follicles ~ sin(2 * pi * Time) + cos(2 * pi * Time),
          Ovary,
          correlation = corAR1(form = ~ 1 | Mare)
)

check_model(m1)
#> Homogeneity of variance could not be computed. Cannot extract residual variance from objects of class 'gls'.
```

![](https://i.imgur.com/4JP6SsO.png)

<sup>Created on 2022-04-20 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
