### ISSUE TITLE
glm matrix error in check_model

### ISSUE THREAD

**Issue by samhforbes** [easystats/performance#421]
Hi,
Since upgrading to 0.9.0 it throws an error with glm (and glmer etc) when using the cbind(successes, failures) notation:

Error in matrix(value, nrow = nr, dimnames = list(rn, cn)) : 
  length of 'dimnames' [2] not equal to array extent

Note the example below works in 0.8.0 but not in 0.9.0 where it throws the above error.

## reprex

```r
a <- rep(100, 100)
b <- rpois(100, 50)
c <- rnorm(100)
d <- rnorm(100, 50, 4)

df <- data.frame(a,b,c,d)

df$prop <- b/a

mod1 <- glm(cbind(b, a-b) ~ c *d ,
            family = binomial,
    data = df)

performance::check_model(mod1)
```

Note this is not due to something odd with the data. The below code works fine with both versions.

mod2 <- lm(prop ~ c *d ,
            data = df)

performance::check_model(mod2)

**Comment by strengejacke** [comment]
We changed the plots in `check_model()`. which now includes [posterior predictive checks](https://easystats.github.io/performance/reference/check_predictions.html). This, however, did not work for models with matrix response. Should work now.

``` r
a <- rep(100, 100)
b <- rpois(100, 50)
c <- rnorm(100)
d <- rnorm(100, 50, 4)

df <- data.frame(a,b,c,d)

df$prop <- b/a

mod1 <- glm(cbind(b, a-b) ~ c *d ,
            family = binomial,
            data = df)

performance::check_model(mod1)
```

![](https://i.imgur.com/0DzJz8D.png)

<sup>Created on 2022-04-20 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
