### ISSUE TITLE
PCA to parameters?

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/performance#43]
Looking at the functions, I wonder if pca should be moved to parameters. As it is not technically related to performance, but rather used eventually to decrease the number of parameters of the model. Maybe it would be more discoverable there. What do you think?

**Comment by strengejacke** [comment]
I think we had discussed this before, but yes, I always had the feeling that pca is not really a performance thing.

**Comment by strengejacke** [comment]
Close with https://github.com/easystats/parameters/commit/c6735f6877f32b25560f9489bc7d0a5bd601379f

We'll probably have some time with overlap, but I'd say once _parameters_ is on CRAN, we can safely remove `principal_components()` from this package.
