### ISSUE TITLE
May "conditional ICC" not being *conditional*?

### ISSUE THREAD

**Issue by iago-pssjd** [easystats/performance#434]
I wonder if calling conditional to the non-adjusted value reported by `icc` is suitable. It may produce some confussion as you may look at the example below.

Looking at *Nakagawa et al. 2017*, they do not mention anywhere "conditional ICC", but just an ICC adjusted and another ICC not including any subscript to the symbol, as they do for the adjusted or for the marginal and conditional R^2 (which I imagine is the reason you talk about conditional ICC).

Further, in the book *Rabe-Hesketh and Skrondal (2012)*, they talk about a conditional or residual intraclass correlation, but it agrees (!!!) with the "adjusted ICC". Indeed, looking at the examples in section 3.5, specifically at the last paragraph before section 3.6 (page 137), they say:

> For the intraclass correlation, we see that the unconditional intraclass correlation for the null model without covariates is estimated as 0.487. This reduces to a conditional or residual intraclass correlation of 0.459 when level-2 covariates are added and to 0.455 when all remaining covariates are added.

And if we download the data from http://www.stata-press.com/data/mlmus4.html and replicate the analysis (that agree with tables in pages 132 [or 134] and 137):
```r
library(haven)
smoking <- read_dta("mlmus4/smoking.dta")
library(lme4)
null <- lmer(birwt ~ (1|momid), data = smoking)
all <- lmer(birwt ~ (1|momid) + smoke + male + mage + hsgrad + somecoll + collgrad + married + black + kessner2 + kessner3 + novisit + pretri2 + pretri3, data = smoking)
fit <- lmer(birwt ~ (1|momid) + hsgrad + somecoll + collgrad + married + black, data = smoking)
library(parameters)
library(performance)
model_parameters(fit)
Package 'merDeriv' needs to be installed to compute confidence intervals for random effect parameters.
# Fixed Effects 

Parameter   | Coefficient |    SE |             95% CI | t(8596) |      p
-------------------------------------------------------------------------
(Intercept) |     3216.48 | 25.84 | [3165.82, 3267.14] |  124.45 | < .001
hsgrad      |      131.44 | 24.93 | [  82.57,  180.31] |    5.27 | < .001
somecoll    |      180.69 | 26.52 | [ 128.70,  232.68] |    6.81 | < .001
collgrad    |      232.90 | 25.61 | [ 182.70,  283.09] |    9.10 | < .001
married     |      114.76 | 25.48 | [  64.82,  164.71] |    4.50 | < .001
black       |     -201.48 | 28.82 | [-257.98, -144.97] |   -6.99 | < .001

# Random Effects 

Parameter             | Coefficient
-----------------------------------
SD (Intercept: momid) |      348.55
SD (Residual)         |      377.76

Uncertainty intervals (equal-tailed) and p-values (two-tailed) computed using a Wald t-distribution approximation.

print(icc(null), digits = 5)
# Intraclass Correlation Coefficient

     Adjusted ICC: 0.48753
  Conditional ICC: 0.48753

print(icc(fit), digits = 5)
# Intraclass Correlation Coefficient

     Adjusted ICC: 0.45985
  Conditional ICC: 0.43631

print(icc(all), digits = 5)
# Intraclass Correlation Coefficient

     Adjusted ICC: 0.45562
  Conditional ICC: 0.41461
```

Thanks!

**Comment by strengejacke** [comment]
I agree with your arguments, and the long-term goal should also be to rename the return values. @vincentarelbundock which icc's do you extract in your packages? only adjusted icc?

**Comment by strengejacke** [comment]
Ping @vincentarelbundock again 😬

**Comment by vincentarelbundock** [comment]
Sorry, missed that one. I use the columns called `aic` and `bic` after applying `insight::standardize_names(out, style = "broom")` to the output of `performance::model_performance`. I assume this means I do *not* use the "adjusted" versions.
