### ISSUE TITLE
`check_normality`: Compatibility with generalized linear mixed models (random effects)

### ISSUE THREAD

**Issue by mccarthy-m-g** [easystats/performance#436]
The `check_normality()` function currently isn't compatible with generalized linear mixed models when you want to check normality for the random effects. (Aside: there's a typo/grammar issue in the returned message).

``` r
library(glmmTMB)
library(performance)
data("Salamanders")
m <- glmmTMB(
  count ~ mined + spp + (1 | site),
  family = poisson,
  data = Salamanders
)
check_normality(m, effects = "random")
#> Checking normality of residuals is only useful an appropriate assumption for
#>   linear models.
#> NULL
```

<sup>Created on 2022-06-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

However, the [`glmmTMB` package](https://cran.r-project.org/web/packages/glmmTMB/index.html) does assume normality for the random effects [on central limit grounds and for analytical and computational convenience](https://stats.stackexchange.com/questions/366483/why-are-random-effects-assumed-to-follow-a-normal-distribution-in-glmms#comment688502_366483):

> Random effects are assumed to be Gaussian on the scale of the linear predictor and are integrated out using the Laplace approximation.

Given this, should it be possible to use the `check_normality()` function with generalized linear mixed models for the random effects? Or is the limitation still warranted given that "Theory and simulation studies indicate that most aspects of statistical inference are highly robust to this assumption" ([McCulloch & Neuhaus, 2012](https://arxiv.org/abs/1201.1980v1))?

If the limitation is warranted, it might be helpful to revise the message to drop the "appropriate assumption" part since the software is making this assumption (unless I'm misinterpreting what `glmmTMB` is assuming).

**Comment by bwiernik** [comment]
Does check_model() include the random effects QQ plot for such models?

**Comment by strengejacke** [comment]
Yes, should be.
