### ISSUE TITLE
Raise warnings or messages instead of `print_color`

### ISSUE THREAD

**Issue by vincentarelbundock** [easystats/performance#440]
I often need to catch `performance` errors or messages and either silence them or operate on them. This is often not possible because errors and warnings are raised as `insight::print_color` output, which just calls `cat()` and prints to console.

My view is that it would be much preferable to follow recommended and standardized practice and return formal errors or warnings or messages when appropriate, rather than print.

Example: https://github.com/easystats/performance/blob/master/R/r2_nakagawa.R#L118

**Comment by strengejacke** [comment]
yeah, we once switched to `print_color()`, but later back to `message()` and `warning()` again. Feel free to change any occurrences you find.

**Comment by bwiernik** [comment]
I strongly think that warning() should never be used. Only message or error

**Comment by vincentarelbundock** [comment]
That's interesting! I really don't have a strong view on this, so I'm quite curious to know why you think warnings are bad. 

The only thing I feel pretty strongly about is that we shouldn't `print()` or `cat()`, for [the same reasons Wickham gives here.](http://adv-r.had.co.nz/Exceptions-Debugging.html)

> Function authors can also communicate with their users with print() or cat(), but I think that’s a bad idea because it’s hard to capture and selectively ignore this sort of output. Printed output is not a condition, so you can’t use any of the useful condition handling tools you’ll learn about below.

This seems especially problematic for packages like `performance`, which other packages import and program against.

**Comment by vincentarelbundock** [comment]
One thing I've struggled with in my own packages is determine what should be a warning and what should be a message. Since the barrier is too fuzzy, I just defaulted to always raise a warning and never messages. Should I switch, or is the problem just that we have two not-so-distinct categories?

**Comment by bwiernik** [comment]
My perspective is, if it's a problem, it should be an error. If it's valid, but concerning, it should be a message. If it's merely informative, show as part of the print() method. warning() is too ambiguous about what it means

**Comment by strengejacke** [comment]
I disagree, and I actually consider `warning()` as useful, in comparison to `message()`.

- if something is not working, stop (error)
- if something works, but result is not 100% predictable or accurate, warn (like convergence issues for mixed models)
- to give some more information about the context, which is nothing that affects the accuracy or predictability of results, message (like we do by saying which method `model_parameters()` used to compute CIs).

In particular when running R-scripts in your analyses (like `source("file.R")`), R gives you a message like _there were x warnings_. This gets lost if you use `message()` or `cat()`, I think. But this might be informative to users. We _could_ use `print_color()` instead, saying "Warning: this is..." in red or similar (which we used to do in the past more often), but then you cannot suppress those messages/warnings in situations @vincentarelbundock described. Else, we have to be _very consistent_ and _consequent_ in passing `verbose` arguments to suppress printing of warnings.

**Comment by strengejacke** [comment]
I still like the idea of a "verbosity level" (see https://github.com/easystats/parameters/issues/627), but this could be difficult to realize.

**Comment by bwiernik** [comment]
I'd be okay with that, maybe "high", moderate, low, etc. instead of numbers? We can have an option() for verbosity. That can be realized with messages using switch() for messages instead of if () else

**Comment by vincentarelbundock** [comment]
As a first step, would you be OK with me replacing all `print_color()` calls by `message()`, except in print methods?

**Comment by bwiernik** [comment]
I would really rather avoid the exception system. They can only be the one scary color that is alarming to new users. Could we maybe talk about a specific example and we can find another path? In psychmeta, for example, we batch together warnings and then display them once. Maybe we could do something similar?

**Comment by vincentarelbundock** [comment]
Closing now since there is no agreement on a clean path forward, and I don't have the bandwidth to implement `verbose` argument everywhere. Will find a workaround in downstream packages to suppress printed text.
