### ISSUE TITLE
`check_outliers` and `method = “optics”`: find automatic way of setting 'xi'

### ISSUE THREAD

**Issue by rempsyc** [easystats/performance#468]
When working on PR #443 , I noticed the note below in `.check_outliers_optics`. I thought it would be better to make it a proper issue so we don't forget about it.
```r
 # TODO: find automatic way of setting 'xi'
```

To be honest, I'm not really sure how to tackle this issue or who took the note (and whether that person expects to come back to this issue later, or for someone else to take over eventually).

When working on the PR, I've attempted to test each method to make sure each one was still working correctly. During my testing, I _think_ I've seen why in some situations the `xi` parameter for `method = “optics”` can create problems. Let's take the `mtcars` dataset as example.

``` r
library(performance)
check_outliers(mtcars, method = "optics")
#> OK: No outliers detected.
# No outlier

# default threshold is:
2 * ncol(mtcars)
#> [1] 22
# That's 22. Let's change it to be more conservative so we can attempt to find outliers!

check_outliers(mtcars, method = "optics", threshold = 25)
#> Warning in dbscan::extractXi(rez, xi = 0.05): No clusters were found with
#> threshold: 0.05
#> OK: No outliers detected.
# Whoops, we're getting a warning. But still no outliers! Not conservative enough?

check_outliers(mtcars, method = "optics", threshold = 32)
#> Error in dbscan::kNN(x, k, sort = TRUE, ...): Not enough neighbors in data set!
# Whoops, we're getting an error now. What if we try just one value smaller so we don't get an error?
# Surely we will find an outlier then?

check_outliers(mtcars, method = "optics", threshold = 31)
#> Warning in dbscan::extractXi(rez, xi = 0.05): No clusters were found with
#> threshold: 0.05
#> OK: No outliers detected.
# Still a warning but still no outliers!!

# Conclusion: this method cannot find outliers on this dataset. Is that expected?
```

<sup>Created on 2022-08-16 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by strengejacke** [comment]
See https://github.com/easystats/performance/pull/443#issuecomment-1227579567
