### ISSUE TITLE
`check_outliers` and `method = “lof”`: use `tukey_mc` from `bigutilsr` package

### ISSUE THREAD

**Issue by rempsyc** [easystats/performance#469]
When working on PR #443, I noticed the note below in `.check_outliers_lof`. I thought it would be better to make it a proper issue so we don't forget about it.

```r
# TODO: use tukey_mc from bigutilsr package
```

It is not clear to me the reason this change is needed (as there is no explicit explanation), but it might be causing problems in certain edge cases or it might be that `bigutilsr::tukey_mc_up` is simply a better option.

The comment is appearing when defining the cutoff threshold. Reprex below.

``` r
library(performance)

x <- mtcars
threshold = 0.025
out <- data.frame(Row = 1:nrow(x))

# Compute
out$Distance_LOF <- log(dbscan::lof(x, minPts = ncol(x)))

# Threshold
# TODO: use tukey_mc from bigutilsr package
cutoff <- stats::qnorm(1 - threshold) * stats::sd(out$Distance_LOF)

cutoff
#> [1] 0.1789252
# So cutoff is now 0.18

# Let's see if we cannot find a similar threshold with bigutilsr::tukey_mc_up.
bigutilsr::tukey_mc_up(x)
#> The default of 'doScale' is FALSE now for stability;
#>   set options(mc_doScale_quiet=TRUE) to suppress this (once per session) message
#> [1] 523.2777
```

So 523. Hum. That doesn’t sound normal. We might have a problem here already since actually `bigutilsr::tukey_mc_up` is made for numeric vectors, not data frames. Therefore, it probably expects a single variable (like the examples in the docs `?bigutilsr::tukey_mc_up`). Problem is that `method = "lof"` expects a dataframe with at least two variables since it is for multivariate normality, so it would not work in this context, I believe.

I suggest that we abandon `bigutilsr::tukey_mc_up` and keep the current default. Unless of course, there is a specific reasoning that I have missed and that would still be implementable.

<sup>Created on 2022-08-16 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by strengejacke** [comment]
@DominiqueMakowski any ideas?

**Comment by DominiqueMakowski** [comment]
I think any suggestions by @rempsyc are worth implementing, as I don't have any strong opinion about - or didn't have any specific reason for coding anything in a particular way in - check_outliers. I'd say go ahead Rémi and start improving it as you see fit, we trust your judgment. And worst case scenario, if something is off, I'm sure @bwiernik's falcon eyes will notice and we'll correct it :)

**Comment by strengejacke** [comment]
![picard_make_it_so](https://user-images.githubusercontent.com/26301769/185050006-aac20b91-43a5-4b1f-b9fa-d3236ee98844.jpg)

**Comment by strengejacke** [comment]
_(three French have spoken, so let's do it!)_
