### ISSUE TITLE
Vignettes

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/performance#47]
I think we could start by adding two vignettes, one "Different R2s" discussing the differences and application of the R2 indices. We already have this information in the docs so it's mainly a reformatting. A second one could be "Comparing models" As I feel that this feature will need a bit of highlighting :)

I'll try making drafts

**Comment by strengejacke** [comment]
Maybe we can also take some content from https://strengejacke.github.io/sjstats/articles/mixedmodels-statistics.html and make a vignette out of it, since some functions from sjstats are now implemented here.

**Comment by DominiqueMakowski** [comment]
👍

**Comment by strengejacke** [comment]
Do we want this vignette to be ready for v0.2.0? Now that's bayestestR on CRAN, we could submit performance to CRAN in 1-2 weeks...

**Comment by DominiqueMakowski** [comment]
If we find time, sure. I am currently trying to focus on parameters, as it would be good to release it soon

**Comment by strengejacke** [comment]
Let's address the vignette in 0.3.0, I would also rather focus on parameters.

**Comment by strengejacke** [comment]
> If we find time

😒 

This is really a pity, but I don't have time to write a more comprehensive vignette... Maybe we can start with this using a separate branch? So it's at least progressing slowly?

**Comment by DominiqueMakowski** [comment]
What? Daniel using a separate branch 😮?

I don't think it's worth using a separate branch tho since even just a one sentence-vignette is better than what currently exists :) 

I tell you, we should start teaching classes "intro to R and collaborative projects" and suggest easystats documentation and testing as assignments so the students can improve their stats, R and githubing skills and become easystats contributors 😁

**Comment by DominiqueMakowski** [comment]
I think @mattansb is the only one currently teaching tho 👀 😁 and maybe @pdwaggoner ?

**Comment by mattansb** [comment]
That is an awesome idea - maybe for extra credit I can assign some vignette writing! 😆

**Comment by pdwaggoner** [comment]
Ha! I really like this idea both for easystats and for teaching... I may actually do this. I will let you know if anyone comes up with a brilliant output; otherwise, I'll keep it to myself ;)

**Comment by DominiqueMakowski** [comment]
> Maybe we can also take some content from https://strengejacke.github.io/sjstats/articles/mixedmodels-statistics.html and make a vignette out of it, since some functions from sjstats are now implemented here.

What about that idea @strengejacke 😏 ?

**Comment by strengejacke** [comment]
Those pages have been removed meanwhile ;-)
But here's a link: https://github.com/strengejacke/sjstats/blob/a5bd59a143b5d40e463ffade2f803f015029ff9b/vignettes/mixedmodels-statistics.Rmd

Since all the information is now in the docs, and even more up to date, maybe we should just re-assemble the docs to have a readable vignette?

**Comment by DominiqueMakowski** [comment]
Can we directly "copy" the vignette content from some roxygen sections? as we do within the docstrings?

**Comment by DominiqueMakowski** [comment]
Current pkgdown website building fails and the action says: 

  (converted from warning) installation of package ‘VGAM’ had non-zero exit status

🤔

**Comment by strengejacke** [comment]
yeah, I think this is a temporary issue. Seems to be related to the mac-platforms.

**Comment by IndrajeetPatil** [comment]
> I think we could start by adding two vignettes, one "Different R2s" discussing the differences and application of the R2 indices. We already have this information in the docs so it's mainly a reformatting. 

https://easystats.github.io/performance/articles/r2.html

> A second one could be "Comparing models" As I feel that this feature will need a bit of highlighting :)

https://easystats.github.io/performance/articles/compare.html

Should we be closing this?
