### ISSUE TITLE
`check_outliers`: add support for `method = “iforest”`

### ISSUE THREAD

**Issue by rempsyc** [easystats/performance#470]
I haven’t touched `method = “iforest”` in `check_outliers` when working on PR #443, because it was commented. Opening this issue to remember to add support for this method in the future.

I tried uncommenting it to see if I could figure out how to solve the issue but I wasn’t easily able to, so I commented it again, for now.

Essentially, the function runs different code depending on your version of `solitude`. I have version `1.1.3`, so it runs this version of the code for more recent versions:

``` r
x <- mtcars
out <- data.frame(Row = 1:nrow(x))

(iforest <- solitude::isolationForest$new(sample_size = nrow(x)))
#> <solitude>
#>   Public:
#>     clone: function (deep = FALSE) 
#>     fit: function (dataset) 
#>     forest: NULL
#>     initialize: function (sample_size = 256, num_trees = 100, replace = FALSE, 
#>     max_depth: 5
#>     nproc: NULL
#>     num_trees: 100
#>     predict: function (data) 
#>     replace: FALSE
#>     respect_unordered_factors: NULL
#>     sample_size: 32
#>     scores: NULL
#>     seed: 101
#>     status: not_trained
#>   Private:
#>     computeAnomaly: function (depth, data_size) 
#>     harmonic: function (n) 
#>     pathLengthNormalizer: function (phi) 
#>     phi: NULL
#>     sample_fraction: NULL
#>     terminal_nodes_depth: NULL
suppressMessages(iforest$fit(x))
#> INFO  [20:30:45.888] Building Isolation Forest ...  
#> INFO  [20:30:47.311] done 
#> INFO  [20:30:47.322] Computing depth of terminal nodes ...  
#> INFO  [20:30:47.993] done 
#> INFO  [20:30:48.004] Completed growing isolation forest
out$Distance_iforest <- iforest$scores$anomaly_score
out$Distance_iforest
#> NULL
```

Problem is, `out$Distance_iforest` is NULL… Not sure why. Same thing with other datasets (`iris`, `ToothGrowth`).

<sup>Created on 2022-08-16 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by strengejacke** [comment]
closing this for now (see https://github.com/easystats/performance/pull/443#issuecomment-1227579567). @DominiqueMakowski, if you would like to work on it, feel free to re-open.
