### ISSUE TITLE
Option to drop "weights" from compare_performance

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/performance#472]
In order to make publication-ready tables easily, it could be useful to be able to drop weights easily. Currently when doing e.g., `compare_performance(m1, m2, metrics=c("BIC")` it returns the BIC and the BIC_weights.  Either we make it so that weights have to be requested specifically (e.g., `compare_performance(m1, m2, metrics=c("BIC", "BIC_weights")`) or we add a `include_weights=TRUE` arg. What do you think?

**Comment by bwiernik** [comment]
A publication table should have the weights...

**Comment by bwiernik** [comment]
The weights are what makes IC criteria interpretable for most folks

**Comment by DominiqueMakowski** [comment]
Perhaps pretty printing them by adding the weights in parentheses in the same column as the BIC values would be better then

**Comment by bwiernik** [comment]
That's a good idea for the general printing method too. @strengejacke could you help with a pretty printer in *insight* like with CIs?

**Comment by strengejacke** [comment]
``` r
data(iris)
library(performance)
lm1 <- lm(Sepal.Length ~ Species, data = iris)
lm2 <- lm(Sepal.Length ~ Species + Petal.Length, data = iris)
lm3 <- lm(Sepal.Length ~ Species * Petal.Length, data = iris)
compare_performance(lm1, lm2, lm3)
#> # Comparison of Model Performance Indices
#> 
#> Name | Model |   AIC (weights) |   BIC (weights) |    R2 | R2 (adj.) |  RMSE | Sigma
#> ------------------------------------------------------------------------------------
#> lm1  |    lm | 231.452 (<.001) | 243.494 (<.001) | 0.619 |     0.614 | 0.510 | 0.515
#> lm2  |    lm | 106.233 (0.566) | 121.286 (0.964) | 0.837 |     0.833 | 0.333 | 0.338
#> lm3  |    lm | 106.767 (0.434) | 127.842 (0.036) | 0.840 |     0.835 | 0.330 | 0.336
```

<sup>Created on 2022-08-21 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by bwiernik** [comment]
Thanks! That's awesome!

**Comment by bwiernik** [comment]
@strengejacke digits for ICs, elpd, and loglikelihood can probably default to 1

**Comment by strengejacke** [comment]
``` r
data(iris)
library(performance)
lm1 <- lm(Sepal.Length ~ Species, data = iris)
lm2 <- lm(Sepal.Length ~ Species + Petal.Length, data = iris)
lm3 <- lm(Sepal.Length ~ Species * Petal.Length, data = iris)
compare_performance(lm1, lm2, lm3)
#> # Comparison of Model Performance Indices
#> 
#> Name | Model | AIC (weights) | BIC (weights) |    R2 | R2 (adj.) |  RMSE | Sigma
#> --------------------------------------------------------------------------------
#> lm1  |    lm | 231.5 (<.001) | 243.5 (<.001) | 0.619 |     0.614 | 0.510 | 0.515
#> lm2  |    lm | 106.2 (0.566) | 121.3 (0.964) | 0.837 |     0.833 | 0.333 | 0.338
#> lm3  |    lm | 106.8 (0.434) | 127.8 (0.036) | 0.840 |     0.835 | 0.330 | 0.336
```

<sup>Created on 2022-08-24 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

We now should look at the `print()` method to make sure it passed the relevant arguments to `insight::format_table()` to control the digits.

**Comment by strengejacke** [comment]
Should it be `AIC (weights)` or `AIC (weighted)`?

**Comment by bwiernik** [comment]
Weights

(we have this conversation every time you look at these labels 😜)
