### ISSUE TITLE
Remove `pp_check()` alias

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/performance#477]
We had kept this for backward compatibility, but given its collision with `{bayesplot}`, I don't think it's a good idea to continue to retain it.

`posterior_predictive_check()` is good enough.

**Comment by DominiqueMakowski** [comment]
I agree, as a matter of fact we should just move forward with `check_predictions()` as the main form

**Comment by strengejacke** [comment]
There's no collision, I think @bwiernik made this work so either `pp_check()` works with _performance_ even if _bayesplot_ is not installed, and if it is installed or loaded, [this code](https://github.com/easystats/performance/blob/cd0404b36cbd13e0164b2622d7af1d100aadab47/R/pp_check.R#L247) takes care to avoid collision.

The current implementation allows _bayesplot_ users to use `pp_check()` for other models (supported in _performance_), and allows "easystats" users to use `check_predictions()`. This is intentional and actually a good feature, to not have different method-names for different objects. The generic is in _bayesplot_ and we provide methods for new classes.

**Comment by IndrajeetPatil** [comment]
I don't see a single example or a test that uses `performance::pp_check()`, so I will just have to take it on faith that this works as expected.

**Comment by DominiqueMakowski** [comment]
yeah but that's the thing, we should increase the consistency between the plots and re-make our own plots instead of relying on bayesplot for bayesian models. 

I'd say deprecate `posterior_predictive_check()` alias (too long), eventually keep `pp_check()` for models non-compatible with bayesplot (i.e., we extend their function - even though I think that clutters the API for not much), and just use check_predictions which is consistent with our API

**Comment by bwiernik** [comment]
I agree I'd like to redraw Bayesian plots in `check_predictions()` and also keep around the `pp_check()` methods we export

**Comment by strengejacke** [comment]
If we have our own methods for Bayesian models, there's no need to keep `pp_check()`, I'd say.

**Comment by bwiernik** [comment]
There is no downside to exporting the `pp_check` S3 methods, so my preference is to keep them.

**Comment by bwiernik** [comment]
Just to clarify, the situation is like how `{broom}` exports the `tidy()` generic and various other packages like `{marginaleffects}` include methods for their classes. What the conditional logic @IndrajeetPatil just removed from the `{performance}` NAMESPACE was for was that before R 3.6, you couldn't export a method without importing its generic

i.e., before R 3.6, you had to:
```r
importFrom(bayesplot,pp_check)
S3method(pp_check,lm)
```

R 3.6 made it possible to specify the namespace of the generic, so we could export methods without importing the generic:
```r
S3method(bayesplot::pp_check,lm)
```

**Comment by strengejacke** [comment]
> I agree I'd like to redraw Bayesian plots in `check_predictions()` and also keep around the `pp_check()` methods we export

How do we get the simulated response for Bayesian models? What does `pp_check()` return here?

**Comment by bwiernik** [comment]
See eg, https://github.com/paul-buerkner/brms/blob/master/R/pp_check.R

The pp_check methods in various packages do the steps for wrangling the data and then pass them to bayesplot. Looking at it more, we can probably just take the bayesplot results and apply some more styling to them.

**Comment by DominiqueMakowski** [comment]
Can't we call get_prediction with a number of draws?

**Comment by DominiqueMakowski** [comment]
> I agree I'd like to redraw Bayesian plots in check_predictions()

It would be really nice to have our own plot when calling check_predictions.brm 😁

**Comment by DominiqueMakowski** [comment]
Circling back to this, but the current reliance on rstan's ppcheck is quite confusing. In our documentation the default is `iterations=50` but then when we run the function for brms models it prints only 10 by default. 

``` r
model <- brms::brm(qsec ~ mpg, data=mtcars, refresh=0)
#> Compiling Stan program...
#> Start sampling
performance::check_predictions(model)
#> Using 10 posterior draws for ppc type 'dens_overlay' by default.
```

![](https://i.imgur.com/2HIO4Wo.png)

<sup>Created on 2024-03-29 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by DominiqueMakowski** [comment]
Especially since we're already making our own plot in `check_model()` for these models, so why not just return these?

**Comment by strengejacke** [comment]
We could reconstruct the pp_check-plot:

``` r
library(see)
model <- brms::brm(qsec ~ mpg, data=mtcars, refresh=0)
#> Compiling Stan program...
#> Start sampling
pr <- bayesplot::pp_check(model)
#> Using 10 posterior draws for ppc type 'dens_overlay' by default.
d <- as.data.frame(pr$data)

d1 <- datawizard::data_filter(d, is_y == FALSE)
d2 <- datawizard::data_to_wide(d1, id_cols = "y_id", values_from = "value", names_from = "rep_id")
d2$y_id <- NULL
colnames(d2) <- paste0("sim_", colnames(d2))

d2$y <- d$value[d$is_y == TRUE]

class(d2) <- c("performance_pp_check", "see_performance_pp_check", "data.frame")
attr(d2, "model_info") <- insight::model_info(model)
attr(d2, "type") <- "density"
attr(d2, "response_name") <- "qsec"
attr(d2, "bandwidth") <- "nrd"

plot(d2)
```

![](https://i.imgur.com/PlNNXFk.png)

<sup>Created on 2024-03-29 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by strengejacke** [comment]
Anyone knows how to create dots plots with `pp_check()` for Bernoulli or count models? @mattansb ?

**Comment by strengejacke** [comment]
``` r
library(performance)
library(see)
library(brms)
#> Loading required package: Rcpp
#> Loading 'brms' package (version 2.21.0). Useful instructions
#> can be found by typing help('brms'). A more detailed introduction
#> to the package is available through vignette('brms_overview').
#> 
#> Attaching package: 'brms'
#> The following object is masked from 'package:stats':
#> 
#>     ar

load("c:/Users/DL/Desktop/workspace.RData")

# these are the models
# data(Salamanders, package = "glmmTMB")
# model1 <- brms::brm(qsec ~ mpg, data = mtcars, refresh = 0)
# model2 <- brms::brm(am ~  mpg, data = mtcars, refresh = 0, family = brms::bernoulli())
# model3 <- brms::brm(count ~ spp + mined, data = Salamanders, refresh = 0, family = poisson())

check_predictions(model1) |> plot()
```

![](https://i.imgur.com/eUC3Zvq.png)

``` r
bayesplot::pp_check(model1, ndraws = 250)
```

![](https://i.imgur.com/hf9FqVo.png)

``` r

check_predictions(model2) |> plot()
```

![](https://i.imgur.com/2YZfi9k.png)

``` r
bayesplot::pp_check(model2, type = "bars")
#> Using 10 posterior draws for ppc type 'bars' by default.
```

![](https://i.imgur.com/s9i98EQ.png)

``` r

check_predictions(model3) |> plot()
#> Warning: Removed 1 row containing missing values or values outside the scale range
#> (`geom_point()`).
```

![](https://i.imgur.com/Ub46odq.png)

``` r
bayesplot::pp_check(model3, type = "bars")
#> Using 10 posterior draws for ppc type 'bars' by default.
```

![](https://i.imgur.com/cQTnkcW.png)

<sup>Created on 2024-03-29 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by strengejacke** [comment]
We have also the aliases `posterior_predictive_check()` and `check_posterior_predictions()`. Do we want to keep them?
