### ISSUE TITLE
Improve docs for Unstandardized cook's D

### ISSUE THREAD

**Issue by jebyrnes** [easystats/performance#487]
Any chance we can have a `std = FALSE` argument in `check_outliers()` so that we can plot raw Cook's D values?

**Comment by jebyrnes** [comment]
Or `cooks_raw` as a `type`

**Comment by strengejacke** [comment]
@rempsyc I think you were most engaged in that function in the past :-)

**Comment by bwiernik** [comment]
What do you mean by raw Cook's D? Cook's D is by definition standardized by the mean square error of the model and the number of predictors https://en.wikipedia.org/wiki/Cook%27s_distance

**Comment by jebyrnes** [comment]
Right, but here it is standardized to the largest value, which is 1. This means one cannot look at the value to see which go beyond the 4/n threshold and by how much.

**Comment by jebyrnes** [comment]
For example, see the difference between `check_outliers()` and `plot()`

``` r
library(palmerpenguins)
library(performance)

mod <- lm(bill_length_mm ~ body_mass_g, data = penguins)

check_outliers(mod) |> plot(type = "bar")
```

![](https://i.imgur.com/vChAUAE.png)

``` r

plot(mod, which = 4)
```

![](https://i.imgur.com/qrOKjn2.png)

<sup>Created on 2022-10-13 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by jebyrnes** [comment]
Ah. I see you can add a `rescale = FALSE` to plot. 

`check_outliers(mod, rescale = FALSE) |> plot(type = "bar", rescale = FALSE)`

Sorry - that was hard to find in the documentation. Perhaps make that clearer? It's not really in the `see` documentation

**Comment by jebyrnes** [comment]
Sure - I meant not standardized by threshold (so the 0-1 scale) - see plots above. But, looks as if that is available via the rescale argument. That just wasn't entirely clear. Thanks! All about default behavior!
