### ISSUE TITLE
ICC docs

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/performance#49]
Minor point, currently in the ICC docs it says:

> can be interpreted as \dQuote{the proportion of the variance explained by the grouping structure in the population}  \cite{(Hox 2010: 15)}

[Here](https://singmann.github.io/mixed_model_workshop_2day/part2-mixed-models-in-r/mixed_models.html#63) the definition is:

> The intraclass correlation ρ can also be interpreted as the expected correlation between two randomly drawn units that are in the same group. (Hox, 2010, p. 15)

Should we also add this second definition (if correct) to the docs?

**Comment by mattansb** [comment]
TIL!

``` r
library(tidyverse)

n <- 100

means <- rnorm(n,sd = 2)

df <- data.frame(ID = seq_along(means),
                 means) %>% 
  mutate(means = map(means,~bayestestR::rnorm_perfect(100,.x,1))) %>% 
  unnest()

fit <- lme4::lmer(means ~ (1|ID), df)
performance::icc(fit)
#> # Intraclass Correlation Coefficient
#> 
#>      Adjusted ICC: 0.814
#>   Conditional ICC: 0.814

B <- 200
rr <- numeric(B)
for (b in seq_len(B)) {
  sample <- df %>% 
    group_by(ID) %>% 
    summarise(X1 = sample(means,1),
              X2 = sample(means,1))
  
  rr[b] <- cor(sample$X1,sample$X2)
}
mean(rr)
#> [1] 0.8157511
```

<sup>Created on 2019-05-04 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by DominiqueMakowski** [comment]
@mattansb nice demo!!

**Comment by strengejacke** [comment]
Does this also apply to more complex random effects structures?

**Comment by DominiqueMakowski** [comment]
I wonder. But to me this definition makes things a bit clearer (cf. our [loooong discussion](https://github.com/easystats/report/issues/14) related to my non-understanding of ICC 😅)

**Comment by mattansb** [comment]
> Does this also apply to more complex random effects structures?

This only applies to the random intercept case only. If there are for example random slopes `(x|Group)`, sampling 1 point from a group does not account for the variance due to the effect of `x` within that group.

``` r
library(tidyverse)
library(lme4)
#> Loading required package: Matrix
#> 
#> Attaching package: 'Matrix'
#> The following object is masked from 'package:tidyr':
#> 
#>     expand

n <- 100

intercepts <- rnorm(n,sd = 1)
slopes <- rnorm(n,sd = .5)

x_and_y <- function(a, b, k = 100){
  x <- rnorm(k)
  y <- a + x*b + rnorm(k,sd = .4)
  data.frame(x,y)
}

df <- data.frame(ID = seq_len(n),
                 intercepts,
                 slopes) %>% 
  mutate(y = map2(intercepts,slopes,x_and_y)) %>% 
  unnest()
head(df)
#>   ID intercepts    slopes           x            y
#> 1  1  -1.285697 -0.518077 -0.40864109 -1.313670647
#> 2  1  -1.285697 -0.518077  0.02258621 -0.873237393
#> 3  1  -1.285697 -0.518077 -1.61664141  0.002887271
#> 4  1  -1.285697 -0.518077  0.66250362 -0.859712421
#> 5  1  -1.285697 -0.518077 -0.86756175  0.151638608
#> 6  1  -1.285697 -0.518077  0.28500003 -1.526366063

fit <- lmer(y ~ x + (x|ID), df)
performance::icc(fit)
#> # Intraclass Correlation Coefficient
#> 
#>      Adjusted ICC: 0.900
#>   Conditional ICC: 0.898

B <- 200
rr <- numeric(B)
for (b in seq_len(B)) {
  sample <- df %>% 
    group_by(ID) %>% 
    summarise(X1 = sample(y,1),
              X2 = sample(y,1))
  
  rr[b] <- cor(sample$X1,sample$X2)
}
mean(rr)
#> [1] 0.7087208
```

<sup>Created on 2019-05-04 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
