### ISSUE TITLE
Performance fails on rstanarm non "sampling" models

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/performance#5]
To be fixed once [algorithm detection is implemented](https://github.com/easystats/insight/issues/38).

**Comment by strengejacke** [comment]
Do you have a reprex?

**Comment by strengejacke** [comment]
_bump_

I'm not sure what you mean by "non sampling" models.

**Comment by DominiqueMakowski** [comment]
sorry about that! I meant when algorithm is optimizing, meanfield or fullrank

**Comment by strengejacke** [comment]
Ok, and where does which function fail?

**Comment by DominiqueMakowski** [comment]
All I think :)

```r
performance::model_performance(insight::download_model("stanreg_meanfield_lm_1"))
performance::model_performance(insight::download_model("stanreg_fullrank_lm_1"))
performance::model_performance(rstanarm::stan_glm(Sepal.Length ~ Sepal.Width, data=iris, algorithm = "optimizing"))
```

Because of LOO

**Comment by strengejacke** [comment]
Ok, finally I got it what you meant... :-)
