### ISSUE TITLE
Install fails with Error "object ‘has_intercept’ is not exported by 'namespace:insight'"

### ISSUE THREAD

**Issue by sbibauw** [easystats/performance#50]
I tried to install `performance`, but the install is currently failing with the following error:

```
Downloading GitHub repo easystats/performance@master
✔  checking for file ‘/private/var/folders/[...]/easystats-performance-122d3d0/DESCRIPTION’ ...
─  preparing ‘performance’:
✔  checking DESCRIPTION meta-information ...
─  installing the package to process help pages
         -----------------------------------
─  installing *source* package ‘performance’ ...
   ** using staged installation
   ** R
   ** byte-compile and prepare package for lazy loading
   Error: object ‘has_intercept’ is not exported by 'namespace:insight'
   Execution halted
   ERROR: lazy loading failed for package ‘performance’
─  removing ‘/private/var/folders/[...]/performance’
```

Possible to some bug got into the process recently?
(FYI, I am on macOS 10.14.4, running R 3.6.0)

**Comment by DominiqueMakowski** [comment]
@sbibauw, this might be related to an update of `insight`. Could you please try installing insight from github:

```devtools::install_github("easystats/insight")```

**Comment by strengejacke** [comment]
An update of insight was just released on CRAN, so either install from GitHub or from CRAN, and everything should work. You need insight version 0.3.0.

**Comment by sbibauw** [comment]
Indeed, it works fine after an update to insight 0.3.0! Thank you very much!
