### ISSUE TITLE
CIs for R2?

### ISSUE THREAD

**Issue by strengejacke** [easystats/performance#504]
In the docs for `r2()`, I saw we mention the `ci` argument, where CIs can be based on bootstrap or we calculate analytical CIs for R2 (https://easystats.github.io/performance/reference/r2.html).

But do we actually support this anywhere?

@easystats/core-team

**Comment by IndrajeetPatil** [comment]
Yes, e.g. for `r2_bayes()`: https://easystats.github.io/performance/reference/r2_bayes.html

**Comment by strengejacke** [comment]
But it's also mentioned for the default method, and we mention analytical and bootstrap methods for `ci_method`, but that argument is not used in `r2_bayes()`.

**Comment by IndrajeetPatil** [comment]
Yeah, we had a discussion about this in the past (https://github.com/easystats/performance/issues/188) and decided against it. I guess, the argument mentions them because initially we were planning to support `ci_method`, but later decided against it.

So we either support the CI method argument nonetheless, or we remove its mention in the docs. Fine either way.

**Comment by strengejacke** [comment]
ok, I think for now we should remove it from the docs. We can implement later, if we want to, but the current situation is a bit confusing, I'd say.

**Comment by bwiernik** [comment]
I thought I implemented R2 CIs as like the first thing I did with easystsats?

**Comment by bwiernik** [comment]
https://github.com/easystats/performance/blob/main/R/r2_ci.R

**Comment by mattansb** [comment]
It this code valid for any R2? ICC, conditional, marginal....? Perhaps... semi partial R2?

**Comment by strengejacke** [comment]
> I thought I implemented R2 CIs as like the first thing I did with easystsats?

So we had the function, but never implemented it?

**Comment by strengejacke** [comment]
``` r
library(performance)

m <- lm(Sepal.Length ~ Species + Petal.Length, data = iris)
r2(m, ci = .9)
#>        R2: 0.837 [0.787, 0.870]
#>   adj. R2: 0.833 [0.783, 0.868]

m <- glm(am ~ mpg, data = mtcars)
r2(m, ci = .9)
#>   R2: 0.360 [0.133, 0.570]
```

<sup>Created on 2022-10-30 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by strengejacke** [comment]
@bwiernik Could you please add a sentence to the documentation about the method how CIs are computed for non-mixed models?
