### ISSUE TITLE
Avoid using `detectCores()` to get number of cores

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/performance#524]
See: https://www.jottr.org/2022/12/05/avoid-detectcores/

https://github.com/easystats/performance/blob/c3b12bcbd6af76fa09a28589d27f5cf83020344f/R/check_outliers.R#L1566-L1570

**Comment by bwiernik** [comment]
I'm not sure how that fixes the issue @strengejacke? The fix for automatic parallelization would be to switch to `parallely::availableCores()`

**Comment by vincentarelbundock** [comment]
> The fix for automatic parallelization would be to switch to `parallely::availableCores()`

Out of curiosity, are we parallelizing automatically without user input? (Sorry, too lazy to look at the code.) That would seem impolite in cases where users have some important task running outside of R.

**Comment by IndrajeetPatil** [comment]
I agree. We shouldn't be making this decision for the user.

So this issue is now about removing this parallelization code altogether.

**Comment by bbolker** [comment]
This topic has been chewed over a lot here and in other places. My own personal recommendation would be

```r
n_cores <- getOption("mc.cores", 1L)
 ```

The documentation can tell users how to use `options(mc.cores = parallel::detectCores()-1)` (or `parallely::availableCores()-1`, or whatever they want). If desired you could make the option name "performance.mc.cores" to allow flexibility/avoid collisions with other packages that are looking at options setting ...

The only downside is the reduced default performance (for users who have lots of cores and don't know they could be using them). You could implement a message that told them about this (or even use `proc.time()` to see how long a single outlier check took and pick a threshold for "slow enough to print a message"

**Comment by bwiernik** [comment]
Love that approach @bbolker
