### ISSUE TITLE
Should `model_performance()` produce warnings when some measures can't be computed?

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/performance#530]
It is tautological that not every performance metric will be available for every regression model, so I'd expect exceptions thrown to be messages, and not warnings. That is, instead of `insight::format_warning()`, we should be using `insight::format_alert()`.

WDYT?

``` r
library(BayesFactor)
library(performance)

mod <- ttestBF(mtcars$wt, mu = 3)

options(warn = 2L)
performance(mod, verbose = FALSE)
#> Error: (converted from warning) Can produce 
#>   R2 & SIGMA
#>    only for linear models.
```

<sup>Created on 2023-01-07 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

For a reference, this is how Hadley [describes](https://adv-r.hadley.nz/conditions.html) which exception should be used when:

<img width="724" alt="Screenshot 2023-01-07 at 10 58 51" src="https://user-images.githubusercontent.com/11330453/211144792-40b93517-1fa6-4321-9a42-0fe1296ada2d.png">

**Comment by DominiqueMakowski** [comment]
I agree. Too much warnings kill the warnings

**Comment by IndrajeetPatil** [comment]
WDYT, @strengejacke? 

This is a high-priority issue for my repos, so I'd be a happy customer if we decide either way and resolve this soon.

**Comment by vincentarelbundock** [comment]
Nobody asked for my opinion, but I strongly support the "too much warning kills warnings". 

As a downstream user/developer I would like to push forward warnings to end users when numerical results may be inaccurate or problematic, but I would have to silence all warnings if they are too frequent.

**Comment by IndrajeetPatil** [comment]
Preach!

Patrick Burns has my favourite thoughts on this topic:

<img width="1038" alt="Screenshot 2023-01-12 at 23 35 39" src="https://user-images.githubusercontent.com/11330453/212196022-9e84086a-52b2-4522-941b-267c1f479e00.png">

**Comment by IndrajeetPatil** [comment]
> As a downstream user/developer I would like to push forward warnings to end users when numerical results may be inaccurate or problematic, but I would have to silence all warnings if they are too frequent.

Yepp, the same here. 

I created this issue because I am facing overload of warnings in _ggstatsplot_ and _statsExpressions_, which are coming from _performance_.

**Comment by vincentarelbundock** [comment]
Aaaah, i see!

**Comment by strengejacke** [comment]
We could extend the docs and then completely remove the warning

**Comment by IndrajeetPatil** [comment]
Yeah, that sounds like a good option to me, but we are typically slow to close documentation related issues, so, as a temporary workaround, would you be open to just using `format_message()` instead of `format_warning()`?

**Comment by strengejacke** [comment]
I just looked at the example, I think this case justifies at least a warning, if not even an error.

**Comment by IndrajeetPatil** [comment]
> I just looked at the example, I think this case justifies at least a warning, if not even an error.

I would disagree. You are guaranteed to get a warning for most regression models here, since not all measures are going to be available for them.

But, if you feel strongly about this, can we at least wrap these up in `verbose` so that developers can toggle these according to their preferences?

**Comment by strengejacke** [comment]
Maybe the message text is misleading. But what actually happens is that `model_performance()` fails, because such BF objects are not supported.

**Comment by strengejacke** [comment]
I changed it to warning with verbose, like in the default method.

**Comment by IndrajeetPatil** [comment]
Can confirm it works as expected. Thanks!

``` r
library(BayesFactor)
library(performance)

mod <- ttestBF(mtcars$wt, mu = 3)

options(warn = 2L)
performance(mod, verbose = FALSE)
#> NULL
```

<sup>Created on 2023-01-13 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
