### ISSUE TITLE
CRAN submission 0.2.0

### ISSUE THREAD

**Issue by strengejacke** [easystats/performance#54]
Anything to do? I think we have a nice set of new functions and features, I would say, if at all, we could add a vignette (https://github.com/easystats/performance/issues/47).

Any bayestestR must be submitted before.

**Comment by pdwaggoner** [comment]
Are we including epcp/fit for logistic regressions? If so, should I open a PR adding myself as a contributor? Just trying to keep up a little from afar...

**Comment by strengejacke** [comment]
Yes! Please add yourself as contributor.

**Comment by strengejacke** [comment]
@pdwaggoner I reverted the version number, mainly for two reasons:

1) The next "official" version on CRAN will be 0.2.0 - if someone now installs the pkg from GitHub and it has version number 0.2.0, they will not get the CRAN version from "updating packages" (due to same version number), altough the CRAN version may contain new features or final fixes.

2) I usually have some tests that are too long for CRAN, and thus are only run locally. The condition to run local tests is a pkg with a version number with three parts. I.e. tests will run for `0.1.0.9000` or similar, but not for `0.2.0`.

**Comment by pdwaggoner** [comment]
Makes good sense - apologies for the change. Thanks!
