### ISSUE TITLE
docs: check_sphericity()

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/performance#551]
![image](https://user-images.githubusercontent.com/8875533/221404838-ab1db033-f737-491e-afca-8e0b455e0a60.png)

I was looking for the easystats wrapper for sphericity test for correlation matrices, stumbled on this, and then was like wait a second it doesn't work for correlation matrices. After digging up I remembered that it the other test is implemented in [check_sphericity_bartlett](https://easystats.github.io/performance/reference/check_sphericity_bartlett.html?q=check_sphericity_bartlett), and not mentioned from each others docs. Should we unify this by merging the two tests generic functions? Or at least mention and document a bit better

**Comment by mattansb** [comment]
I don't think they should be merged - they have different purposes. 

But perhaps we can link to one another right under of the title. Something along the lines "for Bartlett's test of sphericity see..."

**Comment by DominiqueMakowski** [comment]
I'll open a PR

**Comment by strengejacke** [comment]
_bump_

**Comment by DominiqueMakowski** [comment]
it has been merged no?

**Comment by strengejacke** [comment]
ah, ok. so why is this still open? :curious
