### ISSUE TITLE
glmmTMB with argument rank_check yields "Error in R[subs, subs] : subscript out of bounds"

### ISSUE THREAD

**Issue by GuillaumeA2** [easystats/performance#557]
Hi maintainers,

The function glmmTMB of the glmmTMB package now features an argument rank_check which allows to handle rank deficiency.
See [https://github.com/glmmTMB/glmmTMB/issues/522] for further information.
The functions from the performance package work fine when this argument is not included but yield "Error in R[subs, subs] : subscript out of bounds" when it is included in the function.
I suspect that this changes the model output and that it is not recognized by functions from the performance package afterwards (I actually have the same problems with DHARMa or car::Anova()).

Here is a small reprex :

#install development version of glmmTMB
remotes::install_github("glmmTMB/glmmTMB/glmmTMB")

#load required packages
require(glmmTMB)
require(performance)

#create dataset
set.seed(22380)
dat <- data.frame(
  y = rnorm(100),
  x1 = rnorm(100),
  x2 = rnorm(100)
)

#create two linearly dependent predictor variables
dat$x3 <- with(dat, x1 + 3*x2)

dat$x4 <- with(dat, x2 + 5*x3)

#model fitting and investigation
mod=glmmTMB(y ~ x1 + x2 + x3 + x4, data=dat, control=glmmTMBControl(rank_check='adjust'))
check_collinearity(mod) #Error in R[subs, subs] : subscript out of bounds

Thanks a lot for your help. I appreciate it.
Guillaume ADEUX

**Comment by bbolker** [comment]
This is 99% a `glmmTMB` issue; we are/I am working to make sure that everything is consistent. In particular, I think that `model.matrix(fitted_model)` returns the full (unadjusted) matrix.  Fixing this and/or padding the coefficient vector *and* the covariance matrix with  appropriate `NA`s should solve the problem ...

**Comment by bbolker** [comment]
This is fixed in the `rankdef_NA` branch of `glmmTMB`, soon to be merged (and eventually on its way to CRAN)
