### ISSUE TITLE
Which is the correct test for mixed effects zero-inflated negative binomial pseudo R2?

### ISSUE THREAD

**Issue by clairerichardsRN** [easystats/performance#561]
Greetings, is there a correct command for a pseudo R2 for a mixed effects ZINB? I see one command in performance for zero-inflated models and one for mixed effects (Nakagawa) but it's not clear if the mixed effects command will accommodate the zero-inflated part. I found this [other question about mixed effects ZIP](https://github.com/glmmTMB/glmmTMB/issues/821.) When I do the r2(model) command as posted there, I also have similar output to the OP there, but I only get a R2: 1.000 and adj. R2 of 1.000 which is the same as what I get if I run a zero-inflated R2 command-- with no conditional vs. marginal R2 output. The output changes a lot (to 0.0116) if I modify the method to correlation.
This is the regression formula modeling outages by rurality and offsetting by population size.

m1a<- glmmTMB(OUTAGES~RURAL+ (1| COUNTYNAME)+ offset(log(TOT_COUNTY)), ziformula=~RURAL + (1| COUNTYNAME)+ offset(log(TOT_COUNTY)),  data=ME_county, family=nbinom2)

I think the r2_nakagawa may be correct, it gives a conditional R2 of 0.092 and Marginal R2 of 0.071. But it also returns a warning "mu of 0.4 is too close to zero, estimate of random effect variances may be unreliable."
Thank you!

**Comment by strengejacke** [comment]
We have largely revised the code for computing R2 for mixed models (you need to update to _insight 0.20.2_) and the docs as well: https://easystats.github.io/performance/reference/r2_nakagawa.html

Currently, we have no perfectly reliable estimate of R2 for zero-inflated mixed models. It is on our todo-list, but for now, we cannot provide a 100% validated and accurate measure.
