### ISSUE TITLE
BF in compare_models

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/performance#58]
I am not really sure *how*, but it might be relevant to make `compare_models` compatible with `bayesfactor_models`

**Comment by mattansb** [comment]
I can't seem to find the `compare_models`  function...

**Comment by DominiqueMakowski** [comment]
yes it is model_performance, but I was just thinking that we would indeed put it in its own file (please feel free to do it as I am on my way to a Wakeboarding session, so no access to computer ;)

**Comment by mattansb** [comment]
For some reason `compare_performance` errors... But looking as the code, I think (?) this would be as simple as adding at the end of the code:

```R
BFs <- bayesfactor_models(..., denominator = denominator, verbose = TRUE)
BFs$Model <- object_names
merge(dfs, BFs, by.x = "name", by.y = "Model")
```

**Comment by DominiqueMakowski** [comment]
@strengejacke what do you think of this?

**Comment by strengejacke** [comment]
Sounds good, I'm on vacation until Sunday, so expect me to be active again next week.

**Comment by strengejacke** [comment]
What about this?

``` r
library(performance)
data(iris)

lm1 <- lm(Sepal.Length ~ 1, data = iris)
lm2 <- lm(Sepal.Length ~ Species, data = iris)
lm3 <- lm(Sepal.Length ~ Species + Petal.Length, data = iris)
lm4 <- lm(Sepal.Length ~ Species * Petal.Length, data = iris)

compare_performance(lm1, lm2, lm3, lm4)
#>   name class    AIC    BIC   R2 R2_adjusted RMSE  Bayesfactor
#> 1  lm1    lm 372.08 378.10 0.00        0.00 0.83 1.000000e+00
#> 2  lm2    lm 231.45 243.49 0.62        0.61 0.51 1.695852e+29
#> 3  lm3    lm 106.23 121.29 0.84        0.83 0.33 5.843105e+55
#> 4  lm4    lm 106.77 127.84 0.84        0.83 0.33 2.203243e+54
```

<sup>Created on 2019-06-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by strengejacke** [comment]
In case models are not of same class, the BF column is not shown.

**Comment by DominiqueMakowski** [comment]
I would rename the column as BF for consistency with bayestestR.

Also, and that's something to be dealt with in bayestestR, but I am wondering if we should change the BF of the "reference" model (the denominator) from 1 to NA. Although 1 is statistically correct, it might be clearer for the user and more explicit that one model has NA *because* it is the reference model. Otherwise, the fact that BFs are comparisons and depend on the first provided model might be overlooked.

**Comment by mattansb** [comment]
> I am wondering if we should change the BF of the "reference" model (the denominator) from 1 to NA.

I think this is a good idea to do here (the printing method in `bayestestR` does not show the BF for the reference model, and the reference model can also be changed in `bayestestR`, e.g. `update(x, reference = 2)`)

**Comment by strengejacke** [comment]
If you have any good idea how a `print()`-output could look like, let me know. I think, `compare_performance()` can benefit from a nice print-method.

**Comment by DominiqueMakowski** [comment]
And 1) a meta index corresponding to the average rank from different indices and 2) options to arrange models based on this meta-index or any other particular index ☺️ 

Let's schedule that for v3 :)

**Comment by DominiqueMakowski** [comment]
Also, related to the column names guidelines, maybe renaming the two first columns (`name` -> `Model` and `class` -> `Class` (or `Type`?))

**Comment by mattansb** [comment]
> In case models are not of same class, the BF column is not shown.

Why is this? For it is possible (and plausible) to compare BICs for different models type for the same data - currently `bayestestR::bayesfactor_models` tests to see if the DV is the same across all compared models:

``` r
library(lme4)
#> Loading required package: Matrix

m1 <- lm(Sepal.Width ~ 1, iris)
m2 <- lmer(Sepal.Width ~ 1 + (1|Species), iris)
m3 <- lmer(Sepal.Width ~ Sepal.Length + (1|Species), iris)

performance::compare_performance(m2,m3) # has BF
#>   Model    Type       AIC       BIC R2_conditional R2_marginal       ICC
#> 1    m2 lmerMod 119.88538 128.91729      0.4906288   0.0000000 0.4906288
#> 2    m3 lmerMod  79.80352  91.84606      0.8296941   0.1658588 0.7958309
#>        RMSE        BF
#> 1 0.3363202        NA
#> 2 0.2851333 112179958

performance::compare_performance(m1,m2,m3) # No BF
#>   Model    Type       AIC       BIC      RMSE R2_conditional R2_marginal
#> 1    m1      lm 179.55228 185.57355 0.4344110             NA          NA
#> 2    m2 lmerMod 119.88538 128.91729 0.3363202      0.4906288   0.0000000
#> 3    m3 lmerMod  79.80352  91.84606 0.2851333      0.8296941   0.1658588
#>         ICC R2 R2_adjusted
#> 1        NA  0           0
#> 2 0.4906288 NA          NA
#> 3 0.7958309 NA          NA

bayestestR::bayesfactor_models(m1,m2,m3) # can compare models of different classes
#> # Bayes Factors for Model Comparison
#> 
#>   Model                            Bayes Factor
#>   [2] 1 + (1 | Species)                2.01e+12
#>   [3] Sepal.Length + (1 | Species)     2.25e+20
#> 
#> * Against Denominator: [1] (Intercept only)
#> *   Bayes Factor Type: BIC approximation
```

<sup>Created on 2019-08-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mattansb** [comment]
In fact... I think `performance::compare_performance` should also test if the DV is the same, as if it is not, it is not correct to actually compare models, as they model the same data (at the very least give a warning when running the function and/or printing?):

``` r
library(lme4)
#> Loading required package: Matrix

m2 <- lmer(Sepal.Width ~ 1 + (1|Species), iris)

# different data!
m3 <- lmer(Sepal.Width ~ Sepal.Length + (1|Species), iris[-1,])

performance::compare_performance(m2,m3) # has BF
#>   Model    Type      AIC       BIC R2_conditional R2_marginal       ICC
#> 1    m2 lmerMod 119.8854 128.91729      0.4906288   0.0000000 0.4906288
#> 2    m3 lmerMod  80.4021  92.41788      0.8284971   0.1659694 0.7943686
#>        RMSE
#> 1 0.3363202
#> 2 0.2860707

bayestestR::bayesfactor_models(m1,m2,m3) # cam compare models of different classes
#> Error in bayestestR::bayesfactor_models(m1, m2, m3): object 'm1' not found
```

<sup>Created on 2019-08-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

`bayestestR::bayesfactor_models` tests this like so:

```R
mods <- list(...)
resps <- lapply(mods, insight::get_response)
if (!all(sapply(resps[-denominator], function(x) identical(x, resps[[denominator]])))) {
  stop("Models were not computed from the same data.")
}
```

**Comment by strengejacke** [comment]
Thanks! I think you can shorten your code:

```r
resps <- lapply(list(...), insight::get_response)
if (!Reduce(identical, resps)) {
  stop("Models were not computed from the same data.")
}
```

I will integrate this as warning, I think.

**Comment by mattansb** [comment]
That code doesn't seems to do what it should...
``` r


lm1 <- lm(Sepal.Length ~ 1, data = iris)
lm2 <- lm(Sepal.Length ~ Species, data = iris)
lm3 <- lm(Sepal.Length ~ Species + Petal.Length, data = iris)
lm4 <- lm(Sepal.Length ~ Species * Petal.Length, data = iris)

mods <- list(lm1,lm2,lm3,lm4)
resps <- lapply(mods, insight::get_response)
Reduce(identical, resps) # should be ture
#> [1] FALSE
all(sapply(resps[-1], function(x) identical(x, resps[[1]]))) # should be true
#> [1] TRUE
```

<sup>Created on 2019-08-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by strengejacke** [comment]
hm, damn... Not sure which code I ran and that stated that everything worked :-/

**Comment by strengejacke** [comment]
AND OF COURSE THIS ALWAYS HAPPENS 5 MINUTES AFTER ACCEPTANCE ON CRAN!!!

![image](https://user-images.githubusercontent.com/26301769/62466760-6474df80-b792-11e9-85dd-9f3feed4e92d.png)

**Comment by DominiqueMakowski** [comment]
> AND OF COURSE THIS ALWAYS HAPPENS 5 MINUTES AFTER ACCEPTANCE ON CRAN!!!

classic. It's like discovering this massive typo right after sending this very important email 😅

**Comment by strengejacke** [comment]
But... it just affects if the warning is shown or not, and the warning can be turned of via `verbose`, so it's not critical. The BF is still shown, despite the wrong warning.
