### ISSUE TITLE
Improved q-q plot error bands? 

### ISSUE THREAD

**Issue by bwiernik** [easystats/performance#599]
https://www.jstatsoft.org/article/view/v106i10

**Comment by mattansb** [comment]
We currently use `qqplotr`. Should we switch? This should be easy to implement, but the package doesn't seem to have a function to generate pp-bands (only to plot them), right (so we would still need to rely on `qqplotr` for those).

**Comment by mattansb** [comment]
So apparently this option is already available in `qqplotr`. See update in `see` https://github.com/easystats/see/pull/299

**Comment by mattansb** [comment]
lol okay, qqplotr was updated to use qqconf.
Since qqlotr uses ggplot, I suggest we keep using it instead of having to wrap qqconf functions ourselves.

**Comment by bwiernik** [comment]
Great!

I just came across the article talking about more accurate error bands today. Didn't have a chance to read in detail yet
