### ISSUE TITLE
Check Cooks distance

### ISSUE THREAD

**Issue by strengejacke** [easystats/performance#61]
This is some great stuff - I really like the new `check_*` family. In this vein, I wrote a function to check for influential observations via cook's distance. Its in a similar flavor as your measures @strengejacke , and also includes options to print names of outliers, drop outliers (and write a new df), and plot cook's distance.

I would welcome any thoughts here or whether this is even a desired "check". Thanks all!

``` r
check_outliers <- function(model, print_outliers = TRUE, drop_outliers = FALSE, plot = TRUE) {
  data <- insight::get_data(model)
  n <- nrow(data)
  
  #calculate cook's distance
  cook <- stats::cooks.distance(model)
  o <- length(as.numeric(names(cook)[(cook > (4/n))]))
  outliers <- ifelse(o >= 1, 1, 0)
  
  # check for outliers via cook's distance
  if (outliers >= 1) {
    insight::print_color(sprintf("Warning: Outliers detected.\n"), 'red')
  } else insight::print_color(sprintf("OK: No outliers detected.\n"), 'green')
  
  #option to print names of outliers
  if (print_outliers == TRUE) {
    print((names(cook)[(cook > (4 / n))]))
  }
  
  # option to drop outliers and write a new data frame (- outliers)
  if (drop_outliers == TRUE) {
    data_dropped <- data[!(cook > (4 / n)), ]
    return(data_dropped)
  }
  
  # option to plot cook's distance values, with line denoting likely outliers
  if (plot == TRUE){
    plot(cook, pch = 19, 
         main = "Check for Influential Observations\n(Cook's Distance)",
         ylab = "Cook's Distance Value")
    abline(h = (4 / n), 
           col = "red",
           cex = 4)
    text(x = 1:length(cook) + 1, 
         y = cook, 
         labels = ifelse(cook > (4 / n), 
                         names(cook), ""), 
         col = "red")
  }
}

# example
mt1 <- mtcars[, c(1,3)]  # select only mpg and disp (continuous)
oo <- data.frame(mpg = c(37, 40), # create some fake outliers
                 disp = c(300, 400))
mt2 <- rbind(mt1, oo)  # attach outliers to main df
model <- lm(disp ~ mpg, data = mt2) # fit model with outliers

# call the function
check_outliers(model, print_outliers = TRUE, drop_outliers = FALSE, plot = TRUE)
#> Warning: Outliers detected.
#> [1] "1" "2"
```

![](https://i.imgur.com/Dafuo2Q.png)

<sup>Created on 2019-06-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

_Originally posted by @pdwaggoner in https://github.com/easystats/performance/issues/31#issuecomment-498401089_

**Comment by pdwaggoner** [comment]
Thanks (sorry?) for opening a new issue here. Happy to explore how this might fit into `performance`

**Comment by strengejacke** [comment]
Yes, that would fit nicely into performance! I would rather put the plot method into _see_. 

Is this 4/n a general rule? If I draft a function based on your code, could you provide some details for the docs?

**Comment by strengejacke** [comment]
Or simply use [this file](https://github.com/easystats/performance/blob/master/R/check_autocorrelation.R) as template, draft your function and submit a PR. The plot code still goes into _see_, we just need to save the plot data and/or model name as attribute to the return value.

**Comment by strengejacke** [comment]
Maybe `check_outlier()` is a good name? And I think this should be included before we submit 0.2.0 to CRAN.

**Comment by pdwaggoner** [comment]
Absolutely - I am working on it now. I will use the template and submit the PR shortly. 

And for the plotting option, it's pretty "low-fi", almost to be used as a secondary check. Do you think you'd still like it in "see"? Or should it stay in this function? Your call completely. 

If you want it in see, should I just keep it in the single PR for the performance package? Or did you want a second PR in the see package? Thanks!

**Comment by strengejacke** [comment]
I'd say remove it from the code in performance. For see, I would re-implement it using ggplot. but we have the code here as basis for _see_, if we need it. We only need to save the data for the plot (`cook`) as attribute here in _performance_, so we have everything we need when we want a plot function in the future.

**Comment by pdwaggoner** [comment]
Sounds great! Finished now and about to open the PR.

**Comment by pdwaggoner** [comment]
Just merged - if that was too hasty, feel free to revert and give it a closer look. Thanks!

**Comment by strengejacke** [comment]
Looks good! Thanks!
