### ISSUE TITLE
revdepcheck error

### ISSUE THREAD

**Issue by mebrooks** [easystats/performance#617]
I'm using `revdepcheck` to check reverse dependencies in preparation for sending a new version of `glmmTMB` to CRAN. It tells me there is a new error in this package, but it doesn't appear to involve `glmmTMB`. I'm just doing my duty.

<details>

* Version: 0.10.5
* GitHub: https://github.com/easystats/performance
* Source code: https://github.com/cran/performance
* Date/Publication: 2023-09-12 08:50:02 UTC
* Number of recursive dependencies: 265

Run `revdepcheck::revdep_details(, "performance")` for more info

</details>

## Newly broken

*   checking examples ... ERROR
    ```
    Running examples in ‘performance-Ex.R’ failed
    The error most likely occurred in:
    
    > ### Name: r2_bayes
    > ### Title: Bayesian R2
    > ### Aliases: r2_bayes r2_posterior r2_posterior.brmsfit
    > ###   r2_posterior.stanreg r2_posterior.BFBayesFactor
    > 
    > ### ** Examples
    > 
    ...
    https://mc-stan.org/misc/warnings.html#tail-ess
    [1] "Error in sampler$call_sampler(args_list[[i]]) : "
    [2] "  c++ exception (unknown reason)"                
    error occurred during calling the sampler; sampling not done
    Error in check_stanfit(stanfit) : 
      Invalid stanfit object produced please report bug
    Error in rstan::summary(stanfit, probs = probs, digits = 10)$summary : 
      $ operator is invalid for atomic vectors
    Calls: stan_lmer ... eval -> eval -> stan_glmer -> stanreg -> make_stan_summary
    Execution halted
    ```

**Comment by strengejacke** [comment]
Could this be your local setup? Else, I wonder why CRAN checks are not failing...
https://cran.r-project.org/web/checks/check_results_performance.html
