### ISSUE TITLE
r2: unreliable random effect variances for beta model 

### ISSUE THREAD

**Issue by Franelizabethgalvez** [easystats/performance#618]
We have this fitted model:

`m2<-glmmTMB(FvFm ~ hora*temperatura + (1|Experimento),
     data=d, family=beta_family(link="logit"))`

but when we evaluate its quality, we get this warning:

`> performance::r2(m2)`
`# R2 for Mixed Models`
`Conditional R2: 1.000`
     `Marginal R2: 0.973`
`Warning message:`
`mu of 1.0 is too close to zero, estimate of random effect variances may be unreliable. `

`> icc(m2)`
`# Intraclass Correlation Coefficient`
`Adjusted ICC: 0.983`
`Unadjusted ICC: 0.026`
`Warning message:
mu of 1.0 is too close to zero, estimate of random effect variances may be unreliable`

Given the warning and considering that the random variable (Experimento) explains only 3% of the variance, it would be better to reformulate the model and remove experiment? which would lead us to betareg, but this model is apparently not better enough either:  `(m3<-glmmTMB(FvFm ~ hora*temperatura, data=d, family=beta_family(link="logit")))`

`> compare_performance(m2,m3, rank = TRUE, verbose = FALSE)`
`# Comparison of Model Performance Indices`

`Name |   Model | R2 (marg.) |  RMSE |   Sigma | AIC weights | AICc weights | BIC weights | Performance-Score`
`------------------------------------------------------------------------------------------------------------`
`m2   | glmmTMB |      0.973 | 0.027 | 262.038 |       1.000 |        1.000 |       1.000 |            83.33%`
`m3   | glmmTMB |      0.942 | 0.037 | 162.736 |    1.67e-15 |     1.79e-15 |    8.25e-15 |            16.67%`

if anyone has any suggestions or light on this, please, it would be greatly appreciated!!
Thank you..

`> summary(m2)`
`Family: beta  ( logit )`
`Formula:          FvFm ~ hora * temperatura + (1 | Experimento)`
`Data: d`
       ` AIC      BIC   logLik deviance df.resid `
    `-730.4   -711.2    371.2   -742.4      174`

`Random effects:`
`Conditional model:`
`Groups      Name        Variance Std.Dev.`
`Experimento (Intercept) 0.0099   0.0995 `
`Number of obs: 180, groups:  Experimento, 5`

`Dispersion parameter for beta family ():  262 `

`Conditional model:`
                                      ` Estimate Std. Error z value Pr(>|z|)`
           `(Intercept)          0.26960    0.04821    5.59 2.24e-08 ***`
             `hora4                0.03181    0.02627    1.21   0.2260`
     `temperatura20        0.05626    0.02630    2.14   0.0324 *`
`hora4:temperatura20 -1.44971    0.03859  -37.56  < 2e-16 ***`
`hora4:temperatura20 -1.44971    0.03859  -37.56  < 2e-16 ***`
`---`
`Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1`

**Comment by bbolker** [comment]
@Franelizabethgalvez , this is a really tiny point, but your example will be easier to read if you delimit the entire code chunk with triple-backticks rather than putting backticks around each line separately ...

```
## this is some code
x +  y + z
```

`this is one line of code`
`this is another`

**Comment by Franelizabethgalvez** [comment]
We have checked the model with the functions you suggested and everything seems to be fine. So according to our design, we have decided to keep the experimental factor. 

Thank you for your time!!
