### ISSUE TITLE
JOSE Review - 221: Statement of Need 

### ISSUE THREAD

**Issue by nniiicc** [easystats/performance#619]
In the 'Statement of Need' 
- Refer the reader to the github repository where they can find dependency information and installation instructions. 
- Add one sentence about the intended audience for the instructional materials that follow. "Researchers" are clearly the broad audience, but at what level (undergraduate, graduate, professional, all of the above?)

https://github.com/openjournals/jose-reviews/issues/221

**Comment by bwiernik** [comment]
@rempsyc

**Comment by rempsyc** [comment]
Fixed, thank you @nniiicc !
