### ISSUE TITLE
JOSE Review - 221: Community Contribution (to learning modules) 

### ISSUE THREAD

**Issue by nniiicc** [easystats/performance#620]
The paper includes excellent instructions for how to identify and handle statistical outliers.  

I can imagine someone working with researchers new to stats or easystats in R wanting to build off of your content for a classroom activity, or even an extended written tutorial. 

To turn this content into something that could be reused I would suggest publishing the modules as a notebook, or a set of `.rmd` files. [Note: You may already have this content somewhere in the repo but I could not find it with a quick scan] 

In the same directory where you place these files you can add a small note on how to contribute to this content.  This would allow me to check off two remaining boxes in my review:
- Usage: Does the documentation explain how someone would adopt the module, and include examples of how to use it?
- Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the module 2) Report issues or problems with the module 3) Seek support

https://github.com/openjournals/jose-reviews/issues/221

**Comment by bwiernik** [comment]
@rempsyc

**Comment by rempsyc** [comment]
What I am thinking now is making a vignette out of it. We had already discussed this idea to make a more extended version. A vignette would also not be too much trouble and feat neatly on our website with other similar content.

**Comment by rempsyc** [comment]
I have created a vignette with the extended paper and included a new section about reusing the educational module for teaching purposes at the beginning, which also includes a link to the community contribution guidelines.

It is available here: https://github.com/easystats/performance/blob/JOSE_paper/vignettes/check_outliers.Rmd

It is not up on the site yet as we still have to merge that branch on which we work on the JOSE paper. You can still knit the file locally to test it should you wish so. So closing this issue for now but of course let me know if there are any other issue.

**Comment by DominiqueMakowski** [comment]
nice one congrats!
