### ISSUE TITLE
JOSE Review - 221: Previous Use / Instruction 

### ISSUE THREAD

**Issue by nniiicc** [easystats/performance#621]
The final remaining box for me to tick is "Does it describe how it has been used in the classroom or other settings, and how someone might adopt it?" ... You can address this with a short line in the paper, or you can just tell me via the issue that this is not applicable to your submission. 

https://github.com/openjournals/jose-reviews/issues/221

**Comment by bwiernik** [comment]
@rempsyc

**Comment by bwiernik** [comment]
@nniiicc if possible, could you please keep discussion of this paper on the issue in the JOSE repository? This repo is much broader and encompasses the full performance package and all of its features, not just outlier analysis

**Comment by nniiicc** [comment]
Creating an issue in the repository's tracker is what the review instructions say to do. It's not my individual practice - comment there if you don't want other reviewers don't do the same thing

**Comment by nniiicc** [comment]
Nbd - I just don't want you to get further bombarded by issues from a 2nd review

**Comment by rempsyc** [comment]
@nniiicc regarding this issue, I believe as you suggest that is not applicable to our submission, so closing this issue first. We have not had previous use of this module before this publication.
