### ISSUE TITLE
JOSE Review - 221: Text Clarity

### ISSUE THREAD

**Issue by lebebr01** [easystats/performance#634]
Overall, I enjoyed the JOSE paper. It was well-written and offered great insights. 

For the review checklist element, "Instructional Design," a few small pieces are overstated in the JOSE paper. I would like to hear your thoughts on these. 

1. pg 2, lines 43 - 46: There is a discussion of the mean and standard deviation not being robust, which is great. I was surprised to see the second part regarding these statistics assuming a Normal distribution. I agree and understand your point, but this is overstated for those learning statistics. 
2. pg 7, lines 244 - 247: I liked this example and appreciate the idea of thinking about research context for extreme values/outliers. Would it be worth adding/framing this idea into statistical terms and being very explicit about what you mean by context?

https://github.com/openjournals/jose-reviews/issues/221

**Comment by rempsyc** [comment]
Here is the revised paragraph for point 2 (updated on the JOSE branch):

> We should also keep in mind that there might be error outliers that are not detected by statistical tools, but should nonetheless be found and removed. For example, if we are studying the effects of X on Y among teenagers and we have one observation from a 20-year-old, this observation might not be a _statistical outlier_, but it is an outlier in the _context_ of our research, and should be discarded. We could call these observations *undetected* error outliers, in the sense that although they do not statistically stand out, they do not belong to the theoretical or empirical distribution of interest (e.g., teenagers). In this way, we should not blindly rely on statistical outlier detection methods; doing our due diligence to investigate undetected error outliers relative to our specific research question is also essential for valid inferences.

**Comment by lebebr01** [comment]
Thanks! Looks great. The added piece to being explicit about the method's assumptions is helpful, I misread/misunderstood that.
