### ISSUE TITLE
check_outlier

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/performance#64]
@pdwaggoner @strengejacke 
That's a great idea, a awesome implementation here and in see 🎉 .

Few minor things that came through my mind:

- `check_outlier` -> `check_outliers`? 🤔 (plural)
- Add distance type as a `method` argument (allowing for other types of distances, e.g. Mahalanobis etc)
- This function could be extended to dataframes and single vectors, for which it could return the outliers based on a traditional threshold of SD (e.g., 1.96 SD etc)
- Make the threshold explicit and changeable with a `threshold` argument (currently is it for Cook's distance `(4 / n)`  or `4`, for example). We could provide a `"default"` mode that would pick a reasonable default depending on the distance method.
- how should we deal with Bayesian models? since they usually have their own measure (the pareto k) should we wrap around this method? 

I can't wait to have vignettes and posts presenting all of these cool functions ☺️

**Comment by strengejacke** [comment]
Ok, I think we have it for now, I addressed some of the suggestions mentioned from you all. Further enhancements, e.g. data frames or Bayesian, is something for 0.3.0 I would say.

**Comment by DominiqueMakowski** [comment]
👍

**Comment by pdwaggoner** [comment]
Sounds good to me. I like the idea of these extensions, though, @DominiqueMakowski . We can never have enough checks for models, in my opinion.

**Comment by strengejacke** [comment]
https://stat.ethz.ch/R-manual/R-devel/library/stats/html/mahalanobis.html

https://www.r-bloggers.com/outlier-detection-with-mahalanobis-distance/

**Comment by DominiqueMakowski** [comment]
Recently I've found myself trying the new ICS method for multivariate outlier detection based on Invariant Coordinate Selection [(Archimbaud, Nordhausen, & Ruiz-Gazen, 2016)](https://www.researchgate.net/profile/Klaus_Nordhausen/publication/311736765_Multivariate_Outlier_Detection_With_ICS/links/586eaf3508ae6eb871be1de2/Multivariate-Outlier-Detection-With-ICS.pdf) which gave some interesting results.

The pipeline looked like this:

```r
library(ICS)

# Finding outliers
outliers <- df %>%
  purrr::keep(is.numeric) %>%
  ICS::ics2() %>%
  ICSOutlier::ics.outlier(ncores=parallel::detectCores(), iseed = 123)  # This can take some time

# Checking outliers
print(outliers)
summary(outliers)
plot(outliers)

# Removing outliers
df <- df %>%
  dplyr::mutate(Outlier = outliers@outliers) %>%
  dplyr::filter(Outlier == 0)
```

I reckon that implementing wrappers to easily switch between methods would be super useful. Moreover, we could also compute a "composite index" based on methods-agreement. People could then decide to be very conservative, i.e., remove outliers that are detected by *all* methods, or liberal, removing outliers detected by at least one method. This could give some nuance to outliers processing.

**Comment by strengejacke** [comment]
I'm currently struggling with a useful threshold for Mahalanobis... Would you measure it in SD? Then we would beed to standardize the variables.

**Comment by strengejacke** [comment]
Ok, just saw that standardizing etc. is not necessary if we define the `center`-argument (which I actually do). Now we need a sensible threshold.
