### ISSUE TITLE
posterior predictive check for binomial glm with matrix response

### ISSUE THREAD

**Issue by richardjtelford** [easystats/performance#644]
I've noticed that the posterior predictive check for a binomial glm is different depending on whether the response variable is a vector of proportions or a matrix of successes and failures.

Minimal reprex
```
tot <- rep(10, 100)
suc <- rbinom(100, prob = 0.9, size = tot)

df <- data.frame(tot, suc)

df$prop <- suc/tot

mod1 <- glm(cbind(suc, tot - suc) ~ 1 ,
            family = binomial,
            data = df)

#performance::check_model(mod1)
performance::check_posterior_predictions(mod1)

mod2 <- glm(prop ~ 1 ,
            family = binomial,
            data = df, 
            weights = tot)


performance::check_posterior_predictions(mod2)
```
I was, perhaps mistakenly, expecting these plots to look the same.

In `performance::pp_check.glm`, the result is calculated as 

```
sapply(matrix_sim, function(i) i[, 1]/i[, 2], simplify = TRUE)
```
This is generating lots of Inf where the number of failures is zero.

Should this code not be calculating the  proportion, with code such as

```
sapply(matrix_sim, function(i) i[, 1]/rowSums(i), simplify = TRUE)
```

**Comment by strengejacke** [comment]
This is what I get right now:

``` r
tot <- rep(10, 100)
suc <- rbinom(100, prob = 0.9, size = tot)
df <- data.frame(tot, suc)
df$prop <- suc / tot

mod1 <- glm(cbind(suc, tot - suc) ~ 1,
  family = binomial,
  data = df
)

performance::check_posterior_predictions(mod1)
```

![](https://i.imgur.com/zq2JKtG.png)

``` r

mod2 <- glm(prop ~ 1,
  family = binomial,
  data = df,
  weights = tot
)

performance::check_posterior_predictions(mod2)
```

![](https://i.imgur.com/Y5ou0Z4.png)

``` r

mod3 <- glm(cbind(suc, tot) ~ 1,
  family = binomial,
  data = df
)

performance::check_posterior_predictions(mod3)
```

![](https://i.imgur.com/MU5rEg1.png)

And this is when I change the code to your suggestion:

``` r
tot <- rep(10, 100)
suc <- rbinom(100, prob = 0.9, size = tot)
df <- data.frame(tot, suc)
df$prop <- suc / tot

mod1 <- glm(cbind(suc, tot - suc) ~ 1,
  family = binomial,
  data = df
)

performance::check_posterior_predictions(mod1)
#> Warning: Maximum value of original data is not included in the
#>   replicated data.
#>   Model may not capture the variation of the data.
```

![](https://i.imgur.com/SRYc0fh.png)

``` r

mod2 <- glm(prop ~ 1,
  family = binomial,
  data = df,
  weights = tot
)

performance::check_posterior_predictions(mod2)
```

![](https://i.imgur.com/rbjD7iJ.png)

``` r

mod3 <- glm(cbind(suc, tot) ~ 1,
  family = binomial,
  data = df
)

performance::check_posterior_predictions(mod3)
#> Warning: Maximum value of original data is not included in the
#>   replicated data.
#>   Model may not capture the variation of the data.
```

![](https://i.imgur.com/bs7Ej4N.png)

I'll look into this, but right now I'm not sure which approach is more appropriate.

**Comment by richardjtelford** [comment]
Thanks for having a look at this. I appear to have given a partial fix. Looking again line 288

```
  out$y <- response[, 1] / response[, 2]
```

would also need to become

```
  out$y <- response[, 1] / rowSums(response)
```
so that it was calculated in the same way

**Comment by strengejacke** [comment]
Ok, this would be the result:

``` r
set.seed(123)
tot <- rep(10, 100)
suc <- rbinom(100, prob = 0.9, size = tot)
df <- data.frame(tot, suc)
df$prop <- suc / tot

mod1 <- glm(cbind(suc, tot - suc) ~ 1,
  family = binomial,
  data = df
)

mod2 <- glm(prop ~ 1,
  family = binomial,
  data = df,
  weights = tot
)

mod3 <- glm(cbind(suc, tot) ~ 1,
  family = binomial,
  data = df
)

mod4 <- glm(am ~ 1,
  family = binomial,
  data = mtcars
)

performance::check_predictions(mod1)
```

![](https://i.imgur.com/KaAxvJv.png)

``` r
performance::check_predictions(mod2)
```

![](https://i.imgur.com/Q86OkMx.png)

``` r
performance::check_predictions(mod3)
```

![](https://i.imgur.com/B8Libjj.png)

``` r
performance::check_predictions(mod4)
```

![](https://i.imgur.com/lcW19cj.png)

**Comment by richardjtelford** [comment]
Thank you. That looks how I would expect it to.

Would be nice to improve the x-axis label, but not sure what would work and be easy

**Comment by strengejacke** [comment]
``` r
set.seed(1)
tot <- rep(10, 100)
suc <- rbinom(100, prob = 0.9, size = tot)
df <- data.frame(tot, suc)
df$prop <- suc / tot

mod1 <- glm(cbind(suc, tot - suc) ~ 1,
  family = binomial,
  data = df
)

mod2 <- glm(prop ~ 1,
  family = binomial,
  data = df,
  weights = tot
)

mod3 <- glm(cbind(suc, tot) ~ 1,
  family = binomial,
  data = df
)

mod4 <- glm(am ~ 1,
  family = binomial,
  data = mtcars
)
```

# Mod1

## Curent (mod1)

![](https://i.imgur.com/YfFzIp1.png)

## New (mod1)

![](https://i.imgur.com/GQOPQFq.png)

# Mod2

## Curent (mod2)

![](https://i.imgur.com/Y06Gp3R.png)

## New (mod2)

![](https://i.imgur.com/RaVF6O7.png)

# Mod3

## Curent (mod3)

![](https://i.imgur.com/vPW3Sm0.png)

## New (mod3)

![](https://i.imgur.com/izvwKYD.png)

# Mod4

## Curent (mod4)

![](https://i.imgur.com/vn1HBD7.png)

## New (mod4)

![](https://i.imgur.com/55El38X.png)
