### ISSUE TITLE
marginal/conditional R2 terminology

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/performance#66]
Just wanted to complain a bit ^^: I really find the marginal/conditional terms confusing, especially for non-experts. It would have been so much simpler IMHO to originally call these R2s something like "total" and "fixed"...

**Comment by strengejacke** [comment]
![image](https://user-images.githubusercontent.com/26301769/59691145-dabd8280-91e2-11e9-9994-34d5287fa7ca.png)

**Comment by strengejacke** [comment]
You may complain about that with Nakagawa et al. who introduced this terminology ;-)
https://royalsocietypublishing.org/doi/10.1098/rsif.2017.0213

I would say we stick with that convention.

**Comment by DominiqueMakowski** [comment]
Yes yes I know I did not even dream of changing... just wanted to complain 😬 

We can close this issue now 😅
