### ISSUE TITLE
Errors in using r2_kullback

### ISSUE THREAD

**Issue by gxxin1994** [easystats/performance#667]
Hi, thanks a lot for this great package! In learning zero-inflated regression models, I found an error when using r2_kullback to evaluate R2 of the model. I'm reporting this error here in the hope of getting help. Here are my commands and the errors I'm getting from running them, thanks again!

```r
library(performance)
library(pscl)
data("bioChemists", package = "pscl")
 fm_zinb <- zeroinfl(art ~ . | 1, data = bioChemists, dist = "negbin")
r2_kullback(zinb, adjust = TRUE)
Error in names(klr2) <- "Kullback-Leibler R2" : 
  'names' attribute [1] must be the same length as the vector [0]

``` 

```[tasklist]
### Tasks
```

**Comment by strengejacke** [comment]
Thanks! `r2_kullback()` only works for models of class `glm`. I added an informative message, so it becomes clear whether or not a model is supported.
