### ISSUE TITLE
difficult-to-diagnose errors using "difftime" response in a linear model

### ISSUE THREAD

**Issue by bbolker** [easystats/performance#678]
```r
dd <- data.frame(y = as.difftime(0:5, units = "days"))
m1 <- lm(y ~ 1, data = dd)
check_model(m1)
```

> Error: `check_model()` not implemented for models of class `lm` yet.

OK, let's try to convert to numeric on the fly:

```r
m2 <- update(m1, as.numeric(y) ~ .)
```

Same error (although reflecting a different underlying problem, I think ...)

```r
m3 <- update(m1, data = transform(dd, y = as.numeric(y)))
check_model(m3)
```

This works.

**Comment by strengejacke** [comment]
Error occurs here:

``` r
library(performance)
dd <- data.frame(y = as.difftime(0:5, units = "days"))
m1 <- lm(y ~ 1, data = dd)

check_collinearity(m1)
#> Error in Ops.difftime((f - mean(f)), 2): '^' not defined for "difftime" objects
```

<sup>Created on 2024-02-03 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by strengejacke** [comment]
More precise, the error comes from `vcov()` inside `check_multicollinearity()`.

``` r
library(performance)
dd <- data.frame(y = as.difftime(0:5, units = "days"))
m1 <- lm(y ~ 1, data = dd)
vcov(m1)
#> Error in Ops.difftime((f - mean(f)), 2): '^' not defined for "difftime" objects
```

<sup>Created on 2024-02-03 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

Any suggestions how to handle this? @easystats/core-team

**Comment by bbolker** [comment]
More specifically it happens [here](https://github.com/r-devel/r-svn/blob/5f19008a3c7ee423eb44b5ad2bda7b746cb0f501/src/library/stats/R/lm.R#L310) (i.e. within `stats:::summary.lm()`. A few more comments:

* we could say that this should be dealt with better in base R, e.g. by coercing the response variable to be numeric. On the other hand, `?lm` does say "‘response’ is the (numeric) response vector", so technically this could be classified as a RTFM problem. Factors and difftime objects (both of which *could* be coerced to numeric) behave slightly differently here:
   * with a difftime response, the linear model runs with no warning, we don't run into trouble until we try to run `summary()` (or anything downstream, such as `vcov()`
   * with a factor response, we get warnings when two warnings when fitting the model,  and slightly different errors when running `summary()`.
* for me, the weirdest part of what `performance` is doing is that model 2 above (where we use `as.numeric(y) ~ 1`) creates a well-formed linear model (`summary()` and `vcov()` work fine), 

> Error in stats::qf(0.5, ncol(x), nrow(x) - ncol(x)) :  Non-numeric argument to mathematical function

which comes from `check_outliers(model, method = "cook")`

And the problem ultimately comes from the fact that internally we have

```r
data <- insight::get_data(x, verbose = FALSE)
data <- datawizard::data_select(data, select = is.numeric)
```
which ends up creating a NULL matrix, because `insight::get_data` doesn't get the model frame (where the transformation to numeric has happened), but the data frame specified by `data` ...

All this is made harder to debug because a lot of warnings and errors are caught/suppressed deep in the call stack ...

**Comment by strengejacke** [comment]
We _could_ change the code to `data <- insight::get_data(x, source = "mf", verbose = FALSE)`, so data is retrieved from the model frame at first attempt, however, this would only work when the user did `m2 <- update(m1, as.numeric(y) ~ .)` before.

> because insight::get_data doesn't get the model frame

We had a long discussion here (https://github.com/easystats/insight/issues/689) and finally decided to change the default to retrieve data from environment first. What we could do for `check_outliers()` is to look for special classes (like difftime, logical, ...) and then yield a warning? Furthermore, we could check that after removing non-numerics, we still have data left?

**Comment by strengejacke** [comment]
What about this?

``` r
dd <- data.frame(y = as.difftime(0:5, units = "days"))
m1 <- lm(y ~ 1, data = dd)

performance::check_collinearity(m1)
#> Could not extract the variance-covariance matrix for the conditional
#>   component of the model.
#> NULL

performance::check_outliers(m1)
#> Date variables are not supported for outliers detection. These will be
#>   ignored.
#> Error: No numeric variables found. No data to check for outliers.
```

<sup>Created on 2024-02-04 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by bbolker** [comment]
Hmm. This is certainly an improvement, but 

(1) `check_model()` error message is (IMO) still problematic: **any** problem with the model seems to cause a "not implemented for models of class `foo`" error, which was challenging for me and would have been impossible for my students [is there any way to make this a "something bad happened"-type error, and allow retrieval of underlying warnings/errors?]

(2) the "could not extract variance-covariance matrix" is still opaque (i.e., users will still have no idea *why* extraction wasn't possible)

(3) the `check_outliers()` test still fails for the model with `as.numeric(...)`, which will again be difficult for users to understand ("but I explicitly told the model to convert this to numeric!)

I realize that I'm being demanding here, but again &mdash; I'd love to see this get to the point where my students would have a hope of understanding what was going wrong without me around. Some combination of more reporting of buried errors/warnings (point 1 above) and a troubleshooting/FAQ vignette ("if you get this error, here's what might being going wrong") would mitigate these issues/make it less critical to find a complete solution to these admittedly challenging problems ...

---

```r
remotes::install_github("easystats/performance", ref = "strengejacke/issue678")
performance::check_model(m1)
```


> Date variables are not supported for outliers detection. These will be
  ignored.<br>
> Error: `check_model()` not implemented for models of class `lm` yet.

**Comment by strengejacke** [comment]
This is how it looks now. Requires _insight 0.19.8.2_, which should be possible to install from r-universe in some minutes.

``` r
dd <- data.frame(y = as.difftime(0:5, units = "days"))
m1 <- lm(y ~ 1, data = dd)

insight::get_varcov(m1)
#> Error: Can't extract variance-covariance matrix. `get_varcov()` returned
#>   following error: '^' not defined for "difftime" objects
#>   A reason might be that your model includes dates or times. Please
#>   convert them to numeric values before fitting the model.

performance::check_model(m1)
#> Error: `check_model()` returned following error: Can't extract
#>   variance-covariance matrix. `get_varcov()` returned following error: '^'
#>   not defined for "difftime" objects A reason might be that your model
#>   includes dates or times. Please convert them to numeric values before
#>   fitting the model.
#>   
#> If the error message does not help identifying your problem, another
#>   reason why `check_model()` failed might be that models of class `lm` are
#>   not yet supported.

performance::check_collinearity(m1)
#> Error: Can't extract variance-covariance matrix. `get_varcov()` returned
#>   following error: '^' not defined for "difftime" objects
#>   A reason might be that your model includes dates or times. Please
#>   convert them to numeric values before fitting the model.

performance::check_outliers(m1)
#> Date variables are not supported for outliers detection. These will be
#>   ignored. Make sure any date variables are converted to numeric or factor
#>   before fitting the model.
#> Error: No numeric variables found. No data to check for outliers.
```

<sup>Created on 2024-02-05 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by strengejacke** [comment]
I think there still might be some situations where the original error message is not helpful (in particular to new users), so any reports about opaque error message are highly appreciated!

**Comment by strengejacke** [comment]
No need to close manually, this issue would have been closed after merging the PR automatically :-)
