### ISSUE TITLE
`icc` doesn't work for `glmmTMB`

### ISSUE THREAD

**Issue by raffaem** [easystats/performance#682]
I think `icc` doesn't work for `glmmTMB` as well:

```
r$> m2 <- glmmTMB(model,
      data = findf,
        family = nbinom2
    )
r$> icc(m2)
[1] NA
```

**Comment by raffaem** [comment]
It looks like `sjstats` used to advertise compatibility of `icc` with `glmmTMB` models tough

**Comment by raffaem** [comment]
I can try to make a reproducible example, but I have to use some other dataset as unfortunately I cannot share the current one.

Does it depend on a particular specification or it doesn't work with all and any glmmTMB?

I mean, is it supposed to work with glmmTMB?

**Comment by bwiernik** [comment]
I can't reproduce this problem, so I would need to see an example where it occurs to investigate
