### ISSUE TITLE
Error checking normality for t.test

### ISSUE THREAD

**Issue by cmartin** [easystats/performance#689]
Trying this piece of code from the examples : 
```
library(performance)
t.test(mtcars$mpg, mtcars$hp, var.equal = TRUE) |> check_normality()
```
Produces the error 
Error in eval(predvars, data, env) : object 'Value' not found

I did a bit of digging and the error seems to come from this performance line : 

`m <- stats::lm(formula = Value ~ factor(Name), data = datawizard::data_to_long(data))`

Apparently, my version of data_to_long now return Value and Name in lowercase

I'm using R 4.3.0 on Mac, with performance 0.10.9 and datawizard 0.9.1

Thank you for your time and great package!

**Comment by strengejacke** [comment]
Thanks, should be fixed
