### ISSUE TITLE
check_model "Error in match.arg"

### ISSUE THREAD

**Issue by dpmoriarity** [easystats/performance#695]
Hello,

I am investigating an lmer object that worked with "compare_performance(x)", but when I put the same object into "check_model(x)" I get the below error. I installed the latest version of the performance package and that didn't solve it. Is this a bug or am I missing something? Thank you for your help!

Error in match.arg(bandType, c("pointwise", "boot", "ts", "ks")) : 
  'arg' should be one of “pointwise”, “boot”, “ts”, “ks”

**Comment by strengejacke** [comment]
Do you have a reproducible example?

**Comment by dpmoriarity** [comment]
library(lmerTest)
library(performance)

set.seed(42)  ## for sake of reproducibility
n <- 200
dat <- data.frame(ID=1:n, 
                  group=sample(1:5, n, replace=TRUE),
                  x=rnorm(n),
                  y=rnorm(n))

model<-lmer(y~x+(1|group), data = dat) 
check_model(model, panel =FALSE)

**Comment by strengejacke** [comment]
After the code failed, can you run `traceback()` and post the output here? (or: create a reproducible example using the _reprex_ package, which should include some information, too - but the traceback is probably more helpful)

**Comment by dpmoriarity** [comment]
Hello,

My apologies for the delay, lost sight of this while I was traveling. I did a full R system and package update and it is working now!
