### ISSUE TITLE
Clean up my mess...

### ISSUE THREAD

**Issue by strengejacke** [easystats/performance#7]
@DominiqueMakowski Due to this unfortunate setup of Github, cloud sync and two PCs for working at packages I tried to commit via webinterface, which completely messed up the file structure (with R files put in the root folder).

I now cloned the repo here, cleaned up everything and commited via GitHub app again (hope that my sync understands that it doesn't have revert the sync from GitHub after syncing from cloud at home...).

Please check the spelling, some of the `performance_*` functions have lower case, other upper case **R**.

**Comment by strengejacke** [comment]
I merged the PR, so the `r2()` branch now is merged into master. But that did not affect your methods (except that I have replaced the code in `performance_loo()` with the call to the `loo()`-function, which also contained the same code).

**Comment by DominiqueMakowski** [comment]
Ok let us unify this a bit :) 

What about the prefix "perf_*" instead of "performance_"? This could be short enough (perf_r2 vs. r2?) and consistent with the implementation of other methods (perf_aic, perf_loo, perf_superduperindex)?

**Comment by DominiqueMakowski** [comment]
And yes, we should keep all the names in lower cases, my bad :)

**Comment by strengejacke** [comment]
It depends on the scope of the functions. If `aic()` calculates the AIC for new models, so it enhances other packages, I would keep the R stats name (`AIC()` I think), so users can use the generic function call.

`r2()` isn't taken yet, so we don't have to care about existing generics, but then we would break with our design-choice if one function is called `AIC()` and others `perf_r2()`.

If, however, `perf_aic()` does something different that `AIC()` we could think about a naming convention we want.

**Comment by DominiqueMakowski** [comment]
hum, I think you've managed to convince me again :)

Let's remove all the `performance_*` in favour of direct metrics name calls
