### ISSUE TITLE
Problems using `r2_nakagawa()`

### ISSUE THREAD

**Issue by Franelizabethgalvez** [easystats/performance#726]
I have been evaluating the quality of modelfit with the easystats package (0.7.1.2). Since I have mixed models I use the r2_nakagawa() function and since the last update I did (easystats::install_latest(force = TRUE)) this function gives me strange values. 

**For example for this model:** 
`m2<-glmmTMB(FvFm ~ hora*temperatura + (1|Experimento),
     data=d, family=beta_family(link="logit"))`

**I used to get these values:** 
`r2_nakagawa(m2)`
`# R2 for Mixed Models`
`Conditional R2: 1.000`
       `Marginal R2: 0.973`

**and now it gives me these values:**

`# R2 for Mixed Models`
`Conditional R2: 1.341`
       `Marginal R2: 1.306`

I don't know what's wrong, but I have the latest version of easystats and performance and insight. 

Someone is having these problems, I think it is not code. 
any help is welcome and appreciated!!

**Comment by strengejacke** [comment]
This issue is probably fixed in https://github.com/easystats/insight/pull/883.
Do you have a reproducible example?

**Comment by strengejacke** [comment]
Closing this, as it should be fixed in _insight_ and _performance_ meanwhile.

**Comment by Franelizabethgalvez** [comment]
Thanks for the help, I know this question was closed, but I leave this link https://stackoverflow.com/questions/78557157/strange-values-for-r2-nakagawa-with-easystats/78667344#78667344. 

I also leave my reproducible example: first I did this: 
`install.packages("insight", repos = "https://easystats.r-universe.dev")` 
`install.packages("performance", repos = "https://easystats.r-universe.dev")`

then I restarted R. 
I ran my model: `d<-read.delim("ice20Chloromi6M_5exp_2.txt", header=T)`
`m2<-glmmTMB(FvFm ~hora*temperatura + (1|Experimento),data=d, family=beta_family(link="logit"))`

and I got these new values for `r2_nakagawa(m2)` 

`Conditional R2: 0.990`
`Marginal R2: 0.963`

I hope you get the same values!!
[ice20Chloromi6M_5exp_2.txt](https://github.com/user-attachments/files/16169582/ice20Chloromi6M_5exp_2.txt)
