### ISSUE TITLE
R2 Bayes: SE or SD?

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/performance#73]
``` r
library(performance)
library(rstanarm)

model <- stan_glm(mpg ~ wt + cyl, data = mtcars, chains = 1, iter = 500)
r2_bayes(model)
#> # Bayesian R2 with Standard Error
#> 
#>   Conditional R2: 0.821 [0.029]
```

<sup>Created on 2019-07-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I just noticed that in the current printing of bayes R2, we say we report standard errors, and the attribute is indeed named `std.error` (should we make it consistent with the other pkgs and name it SE?) 

```r
structure(
      class = "r2_bayes",
      lapply(r2_bayesian, ifelse(robust, stats::median, mean)),
      "std.error" = lapply(r2_bayesian, ifelse(robust, stats::mad, stats::sd))
    )
```

However, looking at the code, it seems that we are in fact computing the SD (or MAD) rather than SE. Should we fix the printing and the reporting?

`model_performance` also gives a `R2_SE` column.

**Comment by strengejacke** [comment]
The SD of a bootstrap sample is the standard error. I think this is in line with the `summary()` output.

**Comment by DominiqueMakowski** [comment]
I wonder if a bayesian posterior is the same as a bootstrap sample tho :thinking but anyway we could add in the docstrings that the SE is actually the SD here. I'll make this minor addition

**Comment by DominiqueMakowski** [comment]
and btw, welcome back :relaxed:

**Comment by strengejacke** [comment]
> I wonder if a bayesian posterior is the same as a bootstrap sample

No, true, but I _think_ the SD of a sample is the SE of the related estimate. So, "SE" would be appropriate.

**Comment by strengejacke** [comment]
For population confint, you take 1.96 * _SD_, while for samples (estimates), you take 1.96 * _SE_ for confint. So, SD of population is SE of samples, that's why SE should be correct.

**Comment by strengejacke** [comment]
> and btw, welcome back

thanks, but too early, actually. ;-)
