### ISSUE TITLE
Remove unnecessary `tryCatch()` statements targeting `insight::download_model()`

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/performance#732]
There are many such instances in this test file:

https://github.com/easystats/performance/blob/c8977486a8f61e8de76840eb29bafb16c0925a6b/tests/testthat/test-model_performance.bayesian.R#L7

`insight::download_model()` will anyway return `NULL` in case of an error.

**Comment by strengejacke** [comment]
Yeah, that stems from times where we did not have the sanity checks in `insight::download_model()`.

**Comment by IndrajeetPatil** [comment]
Makes sense.

Might be a good opportunity to search for this pattern across all of our repos.
