### ISSUE TITLE
Bayesian testing of reliability in repeated measure designs (alternative to ICC using the Bayes Factor?)

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/performance#74]
This showed up in my twitter feed: https://psyarxiv.com/hpq7w

Didn't read it in details, but it might be interesting

@mattansb I've seen Bayes factors mentioned in it 😁

**Comment by mattansb** [comment]
Saw this yesterday 😊 - they're not really proposing a BF alternative to the ICC, but just a methods of (Bayesian) modelling the scale factor (which we usually ignore) in a mixed design fashion, allowing it to vary by individual - and so one could measure ICC's per subject / test if there is variation in the ICC.

If we want to support this, we would need to support `vICC` models (could not find the package anywhere...)

(They for some reason frame the ICC as only valid under the assumption of equal within-person variance across individuals, but the overall mean is valid regardless of equal means across individuals, so...? 🤷‍♂️)

**Comment by strengejacke** [comment]
Anyone interested in implementing this?

**Comment by mattansb** [comment]
We can't really take an existing Bayesian model and compute this measure - we'd need to rebuild the model (in `vICC` or probably `brms`?),
So this seems like this is a modelling issue (which `easystats` doesn't normally deal with?) more than a parameter / performance issue...
