### ISSUE TITLE
CRAN 0.3.0

### ISSUE THREAD

**Issue by strengejacke** [easystats/performance#75]
This is what we have added and changed so far:
https://github.com/easystats/performance/blob/master/NEWS.md

Should we plan an update to CRAN in the near future, or are there urgent features that need to be added or fixed?

@DominiqueMakowski @pdwaggoner

**Comment by DominiqueMakowski** [comment]
i am in the process of slowly updating report, which might need some updates (exporting R2 attribute etc.) :)

**Comment by strengejacke** [comment]
Ok. Could you provide some more details on the required changes?

**Comment by DominiqueMakowski** [comment]
that's the thing, I don't know yet :/ one of the thing I can forsee is to allow and export in attributes of a particular CI lvl for the bayesian R2

**Comment by strengejacke** [comment]
> particular CI lvl for the bayesian R2

We have no CI-level, just the SD (standard error), I think. :-)

**Comment by strengejacke** [comment]
Ok., #76 is addressed now (except for printing, which can wait some time, I think...).
I'd love to submit to CRAN in the beginning of August.

**Comment by pdwaggoner** [comment]
Per my other response, I’m a little out of commission at the moment due to moving. Will get back in the loop in a week or so. Upon a quick look, I think a CRAN submission looks good as long as everything is synced with report... let me know how I can help.

**Comment by strengejacke** [comment]
performance 0.3.0 is on CRAN.
