### ISSUE TITLE
Bayesian posterior of R2, allow for CI

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/performance#76]
#75 

> We have no CI-level, just the SD (standard error), I think. :-)

Currently yes I know but I think it would make sense to allow the possibility of obtaining a CI: people might want to use them as an alternative to SEs, as they are more intuitive and as their computation is legit in the Bayesian framework. 

We could have a third argument:

```r
r2_bayes <- function(model, robust = TRUE, ci = NULL){
...
}
```

NULL by default but that can take ci values like `ci = 0.89`.

**Comment by strengejacke** [comment]
Would you suggest _replacing_ the se by the ci?

**Comment by strengejacke** [comment]
Well, adding this information is fairly easy... The difficulties come with printing, especially for multiple CI values...

**Comment by DominiqueMakowski** [comment]
Nah, the current consistency across R2 functions is okay ☺️ (although I was [and still am a bit] confused about why calling the index SE since it is really the SD (although I understand that the two are in this case equivalent... but it's like the Millenium Falcon, although coined by Rey as *equivalent* to "garbage" in SW 7, you wouldn't call it garbage *would you*??))

I would rather opt to provide the user with options

**Comment by DominiqueMakowski** [comment]
> The difficulties come with printing, especially for multiple CI values...

Good point, multiple CIs were a pain to address in `model_parameters`.

Maybe we could find an even more systematic way that would basically go through all the columns names, detect instances of `*CI_low_*` and `*CI_high_*` etc., collect them, dissect them and pass them to `format_ci` (currently in parameters). As this could be used by parameters, performance (and possibly report), it could potentially fit in insight.

**Comment by IndrajeetPatil** [comment]
> Well, adding this information is fairly easy... The difficulties come with printing, especially for multiple CI values...

I am a bit confused here. 
I can see this being an issue in `model_parameters` output, but why would there be multiple CI values in `model_performance` output?

**Comment by strengejacke** [comment]
For `model_performance()`, the design is actually not focusing on CIs. I would say an `r2()` with CI is comparable to the `hdi()`, where we have multiple CI values. Maybe this is rather something for _report_? Or we could just allow one CI level value, and if not NULL, it will replace the SE in the output.

**Comment by IndrajeetPatil** [comment]
I see. I am so hung up on this because I'd like to mimic here `JASP`'s behavior, which I find to be very informative way to present `BayesFactor` results. 

![96881071-2b4f8a80-147e-11eb-8f0c-ef9f32098f84](https://user-images.githubusercontent.com/11330453/96881596-ba5ca280-147e-11eb-9c1d-916d4610dc65.png)

But if this is going to require design changes and a ton of other work that might make it difficult for us to retain the overall design and scope of the package, I will accept that and will find some alternative.

**Comment by strengejacke** [comment]
At the moment, the `r2()` function for Bayesian objects only returns the R2 - all other information is included as attributes. So it's really just the `print()` method, that prints the related SE (or SD). There's no big design change. If you would like to have the attributes as data, I could add an `as.data.frame()` method.

**Comment by IndrajeetPatil** [comment]
Yes, having a `as.data.frame()` method would do the job for me!

**Comment by DominiqueMakowski** [comment]
If I remember correctly we had a similar discussion a while ago, because I wanted to report the R2 median + CI in report but somehow Daniel you preferred the SD (I think it was in this same discussion that we went over SD =/= SE 😁)

Afaic I too prefer to see the CI than the SD :)

and yeah no need for multiple cis let's enforce having one value for now and we'll see how it goes

**Comment by strengejacke** [comment]
Yes, if you look at the top of this page, you'll find the discussion ;-)

**Comment by strengejacke** [comment]
``` r
library(performance)
library(rstanarm)
#> Loading required package: Rcpp
#> This is rstanarm version 2.21.1
#> - See https://mc-stan.org/rstanarm/articles/priors for changes to default priors!
#> - Default priors may change, so it's safest to specify priors, even if equivalent to the defaults.
#> - For execution on a local, multicore CPU with excess RAM we recommend calling
#>   options(mc.cores = parallel::detectCores())
#> 
#> Attaching package: 'rstanarm'
#> The following object is masked from 'package:performance':
#> 
#>     pp_check
library(BayesFactor)
#> Loading required package: coda
#> Loading required package: Matrix
#> ************
#> Welcome to BayesFactor 0.9.12-4.2. If you have questions, please contact Richard Morey (richarddmorey@gmail.com).
#> 
#> Type BFManual() to open the manual.
#> ************

m1 <- stan_glm(mpg ~ wt + cyl, data = mtcars, chains = 1, iter = 500, refresh = 0)
#> Warning: Bulk Effective Samples Size (ESS) is too low, indicating posterior means and medians may be unreliable.
#> Running the chains for more iterations may help. See
#> http://mc-stan.org/misc/warnings.html#bulk-ess
r_1 <- r2_bayes(m1)
  
m2 <- stan_lmer(
  Petal.Length ~ Petal.Width + (1 | Species),
  data = iris,
  chains = 1,
  iter = 500,
  refresh = 0
)
#> Warning: Bulk Effective Samples Size (ESS) is too low, indicating posterior means and medians may be unreliable.
#> Running the chains for more iterations may help. See
#> http://mc-stan.org/misc/warnings.html#bulk-ess
#> Warning: Tail Effective Samples Size (ESS) is too low, indicating posterior variances and tail quantiles may be unreliable.
#> Running the chains for more iterations may help. See
#> http://mc-stan.org/misc/warnings.html#tail-ess
r_2 <- r2_bayes(m2)

mtcars$gear <- factor(mtcars$gear)
m3 <- generalTestBF(mpg ~ hp + cyl + gear + gear:wt, mtcars, progress = FALSE, whichRandom = c("gear", "gear:wt"))
r_3 <- r2_bayes(m3)
#> Multiple `BFBayesFactor` models detected - posteriors are extracted from the first numerator model.
#> See help("get_parameters", package = "insight").

r_1
#> # Bayesian R2 with Standard Error
#> 
#>   Conditional R2: 0.809 [0.047]
as.data.frame(r_1)
#>          R2        SD CI    CI_low   CI_high
#> 1 0.8086667 0.0472224 89 0.7243531 0.8713272

r_2
#> # Bayesian R2 with Standard Error
#> 
#>   Conditional R2: 0.953 [0.005]
#>      Marginal R2: 0.825 [0.045]
as.data.frame(r_2)
#>          R2          SD CI    CI_low   CI_high   Component
#> 1 0.9532537 0.005311973 89 0.9434112 0.9610537 conditional
#> 2 0.8253300 0.045023733 89 0.7442191 0.8818157    marginal

r_3
#> # Bayesian R2 with Standard Error
#> 
#>   Conditional R2: 0.581 [0.082]
as.data.frame(r_3)
#>          R2         SD CI    CI_low   CI_high
#> 1 0.5807376 0.08198759 89 0.4390848 0.6973944
```

<sup>Created on 2020-10-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by strengejacke** [comment]
``` r
library(performance)
library(rstanarm)
#> Loading required package: Rcpp
#> This is rstanarm version 2.21.1
library(BayesFactor)

m1 <- stan_glm(mpg ~ wt + cyl, data = mtcars, chains = 1, iter = 500, refresh = 0)
r_1 <- r2_bayes(m1)
  
m2 <- stan_lmer(
  Petal.Length ~ Petal.Width + (1 | Species),
  data = iris,
  chains = 1,
  iter = 500,
  refresh = 0
)
r_2 <- r2_bayes(m2)

mtcars$gear <- factor(mtcars$gear)
m3 <- generalTestBF(mpg ~ hp + cyl + gear + gear:wt, mtcars, progress = FALSE, whichRandom = c("gear", "gear:wt"))
r_3 <- r2_bayes(m3)

r_1
#> # Bayesian R2 with Standard Error
#> 
#>   Conditional R2: 0.821 89% CI [0.739, 0.891]
as.data.frame(r_1)
#>          R2         SD CI    CI_low   CI_high
#> 1 0.8208757 0.04248459 89 0.7394921 0.8910708

r_2
#> # Bayesian R2 with Standard Error
#> 
#>   Conditional R2: 0.953 89% CI [0.944, 0.961]
#>      Marginal R2: 0.818 89% CI [0.744, 0.885]
as.data.frame(r_2)
#>          R2          SD CI    CI_low   CI_high   Component
#> 1 0.9530013 0.005681007 89 0.9436821 0.9612573 conditional
#> 2 0.8184476 0.039290994 89 0.7439847 0.8850910    marginal

r_3
#> # Bayesian R2 with Standard Error
#> 
#>   Conditional R2: 0.578 89% CI [0.430, 0.691]
as.data.frame(r_3)
#>          R2         SD CI    CI_low   CI_high
#> 1 0.5780156 0.08511441 89 0.4302185 0.6905162
```

<sup>Created on 2020-10-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
