### ISSUE TITLE
ICC per random factor

### ISSUE THREAD

**Issue by mattansb** [easystats/performance#78]
I think it would be useful to get ICCs per random factor - useful for nested random factors, *or* crossed random factors (this will also probably require dealing with non-correlated (`||`) cases?

``` r
library(lme4)
#> Loading required package: Matrix

iris_2 <- iris
iris_2$Species2 <- ifelse(iris_2$Species=="setosa","A","B")

fit <- lmer(Sepal.Length ~ Sepal.Width + (Sepal.Width||Species2) + (1|Species),
            data = iris_2)

performance::icc(fit)
#> # Intraclass Correlation Coefficient
#> 
#>      Adjusted ICC: 0.596
#>   Conditional ICC: 0.477

insight::get_variance(fit) # is this an `insight` related question?
#> $var.fixed
#> [1] 0.1193409
#> 
#> $var.random
#> [1] 0.2828283
#> 
#> $var.residual
#> [1] 0.1913624
#> 
#> $var.distribution
#> [1] 0.1913624
#> 
#> $var.dispersion
#> [1] 0
#> 
#> $var.intercept
#>    Species   Species2 Species2.1 
#> 0.11004709 0.01811884 0.82006024
```

<sup>Created on 2019-08-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by strengejacke** [comment]
There's a short section on that in the help:
https://easystats.github.io/performance/reference/icc.html
(ICC for specific group-levels)

**Comment by strengejacke** [comment]
We could add an argument that would calculate the ICC for specific levels, or maybe even a new function?

**Comment by mattansb** [comment]
I think this should be an argument in `icc`, maybe `group = TRUE / FALSE` or something of the like?

(BTW I've sent the `icc` documentation to the professor who will be teaching LMM by us in the spring - go easystats!)

**Comment by cimentadaj** [comment]
I agree with @mattansb. I'm actually just searching for this. Perhaps `group = TRUE` would return the same output but broken down for each separate random effect.

**Comment by strengejacke** [comment]
I'm not sure adding a `group` argument would be enough. Take the example [shown here](https://easystats.github.io/performance/reference/icc.html), section _ICC for specific group-levels_. You can calculate ICCs referring to different levels, depending on the model. But what would you expect to get when you request ICC per random factor? All combinations of levels (e.g. level 1 to 2, 2 to 3, 1 to 3)? Or just all levels with reference to level 1?

In the simplest case, the random effects variance = the random intercept variance:

``` r
library(insight)
library(lme4)
data(sleepstudy)
m <- lmer(Reaction ~ Days + (1 | Subject), data = sleepstudy)

get_variance(m)
#> $var.fixed
#> [1] 908.9534
#> 
#> $var.random
#> [1] 1378.179
#> 
#> $var.residual
#> [1] 960.4566
#> 
#> $var.distribution
#> [1] 960.4566
#> 
#> $var.dispersion
#> [1] 0
#> 
#> $var.intercept
#>  Subject 
#> 1378.179
```

The ICC from `performance::icc()` is:

```r
icc_adjusted <- vars$var.random / (vars$var.random + vars$var.residual)
icc_conditional <- vars$var.random / (vars$var.fixed + vars$var.random + vars$var.residual)
```

In the initial example, however, the three values for `$var.intercept` do _not_ sum up to `$var.random`.  So when random slopes are includes, things become probably difficult. Ignoring random slopes would yield incorrect ICCs, I guess. So the function should at least throw a warning, when ICCs per random factor are returned.

**Comment by strengejacke** [comment]
``` r
library(performance)
library(lme4)
#> Loading required package: Matrix

data(sleepstudy)
set.seed(12345)
sleepstudy$grp <- sample(1:5, size = 180, replace = TRUE)
sleepstudy$subgrp <- NA
for (i in 1:5) {
  filter_group <- sleepstudy$grp == i
  sleepstudy$subgrp[filter_group] <-
    sample(1:30, size = sum(filter_group), replace = TRUE)
}
model <- lmer(
  Reaction ~ Days + (1 | grp / subgrp) + (1 | Subject),
  data = sleepstudy
)
icc(model, by_group = TRUE)
#> # ICC by Group
#> 
#> Group   |   ICC
#> ---------------
#> subgrp  | 0.017
#> grp     | 0.589
#> Subject | 0.001
#> 
#> # ICC between Groups
#> 
#> Group1 |  Group2 |   ICC
#> ------------------------
#> subgrp |     grp | 0.027
#> subgrp | Subject | 0.921
#> grp    | Subject | 0.998
```

<sup>Created on 2020-04-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mattansb** [comment]
@strengejacke 
Not sure what to make of the `# ICC between Groups` section... 
Why is it `var(x) / (var(x) + var(y))` and not `var(x) / var(y)`? When is this information useful? (I'm not familiar with this measure)

**Comment by strengejacke** [comment]
> Why is it var(x) / (var(x) + var(y)) and not var(x) / var(y)? When is this information useful? (I'm not familiar with this measure)

I thought about this, as well. However: the ICC is a ratio from 0 to 1. If var(y) < var(x), then ICC > 1. That's why I thought of this as "proportion of explained variance from level x in relation to the "complete" variance of level x and y"... Not sure if this is useful? We can probably remove that second part.

**Comment by strengejacke** [comment]
> "proportion of explained variance from level x in relation to the "complete"

Or: from the proportion of explained variance by level x and level y (out of levels x, y, and z), x accounts for ...% of this proportion.

**Comment by mattansb** [comment]
Maybe in relation to *all* other randoms?
Like `var(x) / (var(x) + var(y) + ... + var(z))`?

**Comment by strengejacke** [comment]
well, that's actually almost what the first part does (except that it add the residual variance to the denominator as well)... So just skip the 2nd part?

**Comment by mattansb** [comment]
>  So just skip the 2nd part?

I'd say yes.
