### ISSUE TITLE
compare_performance for lavaan models, a wrapper for anova() + BF?

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/performance#83]
``` r
library(lavaan)
#> Warning: package 'lavaan' was built under R version 3.6.1
#> This is lavaan 0.6-4
#> lavaan is BETA software! Please report any bugs.
HS.model <- '
    visual  =~ x1 + b1*x2 + x3
    textual =~ x4 + b2*x5 + x6
    speed   =~ x7 + b3*x8 + x9
'
fit1 <- cfa(HS.model, data = HolzingerSwineford1939)
fit0 <- cfa(HS.model, data = HolzingerSwineford1939, 
            orthogonal = TRUE)
lavaan::anova(fit1, fit0)
#> Chi Square Difference Test
#> 
#>      Df    AIC    BIC   Chisq Chisq diff Df diff Pr(>Chisq)    
#> fit1 24 7517.5 7595.3  85.305                                  
#> fit0 27 7579.7 7646.4 153.527     68.222       3  1.026e-14 ***
#> ---
#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
```

<sup>Created on 2019-08-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

It would be nice to add a wrapper around `lavaan::anova` as `compare_performance`, moreover @mattansb do you think we could add the BF BIC approx?

**Comment by mattansb** [comment]
Shouldn't be a problem (: Let me know when you have the wrapper done and I'll add it 👍

**Comment by mattansb** [comment]
I've extended `bayesfactor_models.default`'s support to any object with a `BIC` method, so it now also works with `lavaan` models:

``` r
library(bayestestR)
library(lavaan)
#> Warning: package 'lavaan' was built under R version 3.6.1
#> This is lavaan 0.6-4
#> lavaan is BETA software! Please report any bugs.
HS.model <- '
    visual  =~ x1 + b1*x2 + x3
    textual =~ x4 + b2*x5 + x6
    speed   =~ x7 + b3*x8 + x9
'
fit1 <- cfa(HS.model, data = HolzingerSwineford1939)
fit0 <- cfa(HS.model, data = HolzingerSwineford1939, 
            orthogonal = TRUE)

bayesfactor_models(fit1, denominator = fit0)
#> Warning: Unable to extract terms or validate that all models use the same data - following objects are not (supported) model objects (yet!): 
#> fit1, fit0
#> # Bayes Factors for Model Comparison
#> 
#>   Model    Bayes Factor
#>   [1] fit1     1.25e+11
#> 
#> * Against Denominator: [2] fit0
#> *   Bayes Factor Type: BIC approximation
```

<sup>Created on 2019-09-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by strengejacke** [comment]
Currently, `compare_performance()` just "rbinds" the output from multiple `model_performance()´ calls. Do you want to make an exception here for lavann, so it just calls anova and bf?

**Comment by DominiqueMakowski** [comment]
I think we have to decide on a generic design for `compare_performance`: it could be a big feature of the package if it allowed for a smart, comprehensive and flexible comparison of models.


I think some of the steps would be:

- Make the function aware of within-model indices (e.g. R2, AIC, ..., i.e., indices that are contained within a model itself) vs. between-models indices (e.g., Chisq, BFs, i.e., indices that are related to some sort of comparison)
- For the first category, it's easy to just rbind them as we do. The complex stuff starts with the second category, as we would need to find/know the "reference" model (for instance, the first model passed (for BFs) or some sort of null model (sometimes used for Chisq test)
- In a first iteration, it wouldn't really change anything, we could still rbind these and just mention in the docs to what these indices refer (i.e., what is the reference model used). In the future, we could allow the user to tweak the reference. 
- Once the table is there, one of the very cool feature (that we could add in `report`) would be to summarise it, i.e., for each model get the number of times that the model is considered as the best, and then allow to arrange the dataframe by model performance, by some sort of "meta-index" of performance

Writing, I realize that it is not that much of a hassle, nothing insurmountable it seems...

**Comment by DominiqueMakowski** [comment]
- One of the things would be also to differentiate between absolute indices, such as R2, that allow comparing between all different kinds of models, and relative indices (such as AIC), that only makes sense for similar models. In the future, we could allow detecting, for each index, models that are comparable and allow to filter them or such

**Comment by strengejacke** [comment]
> Make the function aware of within-model indices (e.g. R2, AIC, ..., i.e., indices that are contained within a model itself) vs. between-models indices (e.g., Chisq, BFs, i.e., indices that are related to some sort of comparison)

Isn't AIC related to comparison, i.e. between models?

**Comment by DominiqueMakowski** [comment]
Maybe it's internally based on a comparison with some "null" model or something similar but to my knowledge, it's "attached" to a given model (for which you have one value, independently from what you compare it with)

**Comment by strengejacke** [comment]
> (for which you have one value, independently from what you compare it with)
True, but there is no reference for the AIC in a single model, so it only makes sense when comparing _between_ models. But this is now more a question of how we "characterize" those indices...

**Comment by DominiqueMakowski** [comment]
correct

**Comment by mattansb** [comment]
I feel like #28 falls under @DominiqueMakowski idea for a major overhaul of `compare_performance`...

**Comment by mattansb** [comment]
Should this issue be named "between-models indices in compare_performance"?

**Comment by strengejacke** [comment]
Isn't this sufficient?

``` r
library(lavaan)
#> This is lavaan 0.6-5
#> lavaan is BETA software! Please report any bugs.
library(performance)

HS.model <- '
    visual  =~ x1 + b1*x2 + x3
    textual =~ x4 + b2*x5 + x6
    speed   =~ x7 + b3*x8 + x9
'
fit1 <- cfa(HS.model, data = HolzingerSwineford1939)
fit0 <- cfa(HS.model, data = HolzingerSwineford1939, 
            orthogonal = TRUE)

performance_lrt(fit1, fit0)
#> # Likelihood-Ratio-Test for Model Comparison
#> 
#> Model |   Type | Df |      AIC |      BIC | Statistic |     p
#> -------------------------------------------------------------
#> fit1  | lavaan | 24 | 7517.490 | 7595.339 |    85.306 |      
#> fit0  | lavaan | 27 | 7579.711 | 7646.439 |   153.527 | 0.000
#> 
#> Model 'fit0' seems to have the best model fit.

compare_performance(fit1, fit0)
#> # Comparison of Model Performance Indices
#> 
#> Model |   Type |  Chisq | Chisq_df | Chisq_p | Baseline | Baseline_df | Baseline_p |  GFI | AGFI |  NFI | NNFI |  CFI | RMSEA | RMSEA_CI_low | RMSEA_CI_high | RMSEA_p |  RMR | SRMR |  RFI | PNFI |  IFI |  RNI | Loglikelihood |     AIC |     BIC | BIC_adjusted | BF
#> ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#> fit1  | lavaan |  85.31 |       24 |       0 |   918.85 |          36 |          0 | 0.94 | 0.89 | 0.91 | 0.90 | 0.93 |  0.09 |         0.07 |          0.11 |    0.00 | 0.08 | 0.06 | 0.86 | 0.60 | 0.93 | 0.93 |      -3737.74 | 7517.49 | 7595.34 |      7528.74 |   
#> fit0  | lavaan | 153.53 |       27 |       0 |   918.85 |          36 |          0 | 0.90 | 0.83 | 0.83 | 0.81 | 0.86 |  0.12 |         0.11 |          0.14 |    0.00 | 0.20 | 0.16 | 0.78 | 0.62 | 0.86 | 0.86 |      -3771.86 | 7579.71 | 7646.44 |      7589.35 |  0
```

<sup>Created on 2020-04-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mattansb** [comment]
Maybe when `compare_performance(..., test = TRUE)` the additional columns from `performance_lrt`, together with `BF` and `R2_delta` could be appended? 🤔

**Comment by strengejacke** [comment]
closing this now, as lavaan support is implemented now. I would not add the LRT to the performance output, because it not just returns an index, but rather a significance test for only a _specific_ measure of all reported measures. This makes the idea of `compare_performance()` somewhat inconsistent, is my feeling.

The issue on R2 delta remains open.
