### ISSUE TITLE
check_homogeneity bug

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/performance#91]
```r
model <- lm(Sepal.Length ~ .*., data=iris)
check_homogeneity(model)
```
```
Error in bartlett.test.default(c(5.1, 4.9, 4.7, 4.6, 5, 5.4, 4.6, 5, 4.4,  : 
  there must be at least 2 observations in each group
```
🤔

**Comment by strengejacke** [comment]
I don't think it's actually a bug, but rather that this test is very limited. Maybe we should include a warning... (I don't see really great benefits from this test anyway...)

**Comment by DominiqueMakowski** [comment]
```
check_homogeneity(model, method = "fligner")
OK: Variances in each of the groups are the same (Fligner-Killeen Test, p = 0.333).
```

It works with another method though (should we improve the p value printing?), maybe a more informative warning (suggesting to try out the other method) could indeed be useful

**Comment by mattansb** [comment]
Different methods require different data structure 🤷‍♂️, so this really *isn't* a bug...
