### ISSUE TITLE
Docs building warning

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/performance#92]
Warnings upon docs building related to crossref. I'll try giving it a look later
 
![image](https://user-images.githubusercontent.com/8875533/66092043-dd3ebf00-e5bc-11e9-88d9-9acd6694a943.png)

**Comment by strengejacke** [comment]
These warnings are not unusual?

**Comment by DominiqueMakowski** [comment]
well they are not needed

**Comment by strengejacke** [comment]
I thought linking to other packages generally yield this warning?

**Comment by DominiqueMakowski** [comment]
Hum, you're right, I thought the links were mispecified or something but no
