### ISSUE TITLE
r2_coxsnell missing

### ISSUE THREAD

**Issue by bbjonz** [easystats/performance#97]
Seems the most recent version of performance is missing the r2_coxsnell() function.  I'm on R 3.6.1 via RStudio on Mac Catalina.

**Comment by strengejacke** [comment]
It's still there, I think:
https://cran.r-project.org/web/packages/performance/performance.pdf

**Comment by bbjonz** [comment]
Hi Daniel,

Thanks for your reply.  Was using Rbookdown and it gave an error that r2_coxsnell wasn't part of the performance package, but others (e.g., McFadden) worked fine.  Ran another model outside of that project and it worked fine.  Will explore and report.

**Comment by strengejacke** [comment]
any news on this?
