### ISSUE TITLE
Specific docs for compare_performance

### ISSUE THREAD

**Issue by DominiqueMakowski** [easystats/performance#98]
Currently, the doc is the same than for `model_performance()`, thus missing on some specificities (e.g., Bayes factor for frequentist models etc.). Maybe we should provide this awesome function (I am using it now 😋) with special treatment?

**Comment by strengejacke** [comment]
> this awesome function

Whenever **I** write a function for an easystats-package, it's _of course_ awesome. That's the nature of all of my functions, awesomness... :princess:

**Comment by DominiqueMakowski** [comment]
I think we are discovering that awesomeness is a fundamental and ontological property of strengejackism. BTW, what does strengejacke mean 🤔 🤔 ??

**Comment by strengejacke** [comment]
> BTW, what does strengejacke mean

People were wondering this for generations (including me)

https://www.youtube.com/watch?v=Jk3Zarr1iIg
